### PR TITLE
Extended conversion based on inheritance

### PR DESCRIPTION
**Pull request by HansOlsson**
Since it is not specified that conversions are inherited (and it would be complicated to implemented) 
I thought it best to auto-generate them (based on inheritance in MSL 3.2.3).
This, together with the correction for #3181, should make the conversions to 4.0.0 ok.

### CODE REVIEW

**Comment by dietmarw** [comment]
@HansOlsson My I ask how you can auto-generate those? Would be useful for future changes and other conversion projects.

**Comment by HansOlsson** [comment]
> @HansOlsson My I ask how you can auto-generate those? Would be useful for future changes and other conversion projects.

@dietmarw it will be a straightforward command in Dymola (and possibly in the 3D Experience platform); but unfortunately it will take awhile before it is released.
The issues in #3181 are also found.

**Comment by beutlich** [comment]
We should at least document in the [MSL release page of the wiki](https://github.com/modelica/ModelicaStandardLibrary/wiki/Generating-a-new-MSL-release) to not forget it.

**Comment by dietmarw** [comment]
The idea with the wiki is good since I'm still not 100% sure of what is exactly possible with conversion script and what not. Especially when I think of models that extend from a base class. So do I now have to specify the conversions for each extended class in addition to the base class? Did I understand that correctly @HansOlsson? And if this is the case how will this work for user models that are extending from base-classes that need conversion and have modifiers in place.

**Comment by HansOlsson** [comment]
> The idea with the wiki is good since I'm still not 100% sure of what is exactly possible with conversion script and what not. Especially when I think of models that extend from a base class. So do I now have to specify the conversions for each extended class in addition to the base class? Did I understand that correctly @HansOlsson? 

Yes, for inheritance in MSL 3.2.3.

> And if this is the case how will this work for user models that are extending from base-classes that need conversion and have modifiers in place.

User-written base-classes are no issue.

 It's just that when converting to MSL 4 we don't necessarily have access to inheritance within MSL 3.2.3. We could assume that both libraries have similar inheritance - but that is not necessarily true.
We could also require that people point to MSL 3.2.3 every time they want to convert, but it seemed better to update the conversion once.

**Comment by dietmarw** [comment]
I struggle to understand in what case the conversion would fail. Could you give a minimal example of what would fail so we can better understand the restrictions of the currently available conversion functionality?

**Comment by HansOlsson** [comment]
> I struggle to understand in what case the conversion would fail. Could you give a minimal example of what would fail so we can better understand the restrictions of the currently available conversion functionality?

I added a variant of one of the conversion examples to demonstrate this.
That example both tests conversion for a derived class in MSL (requiring the script additions), and also one in the conversion library (well, local record) - works without any changes in script.

**Comment by dietmarw** [comment]
So that test case is one that is covered. But I was more interested to see (and understand) what is **not** covered by current conversion.

**Comment by HansOlsson** [comment]
> So that test case is one that is covered. But I was more interested to see (and understand) what is not covered by current conversion.

To clarify: the example is covered by the _updated_ conversion in this PR.
If you remove the conversion script additions then Issue194_Derived is not converted (in Dymola).

**Comment by dietmarw** [comment]
@HansOlsson So could you please supply a sample of what is **not** supported?

**Comment by HansOlsson** [comment]
> @HansOlsson So could you please supply a sample of what is not supported?

I think we are talking past each other.

What I meant:
What is not supported is automatically converting user models using derived classes in MLS, where only the base-class has specified conversions of elements but they are not specified for the derived classes. An example is Issue194_Derived.

However, that can be handled by providing conversions for the elements of the derived class in MSL; that is part of this PR. 

If the derived class is outside of MSL everything can be automatically handled.

The part of #3181 that seems odd at the moment is something related to converting both an enumeration (possibly only in import-statements) and a member of that enumeration.

I'm sure there are some additional unsupported things, but would need more details.

**Comment by beutlich** [comment]
@HansOlsson After merging #3190, could you please repeat the automatic generation of the missing conversion rules.

**Pull request merged**
