### PR TITLE
Improved controller of AST_BatchPlant example case

### LINKED ISSUE #2686: Incorrect flow direction in Modelica.Fluid.Examples.AST_BatchPlant.BatchPlant_StandardWater?
In this model I noticed that B2 has a few drops of water flowing out of the port at the top of the tank, which is plain weird!  I don't think it is any error in symbolic processing in Dymola.

Specifically B2.top_ports[1].m_flow (same as V6.port_a.m_flow) has a negative dip at 741.5878891772804s (followed by a larger positive flow. note: there is a also  a positive "dip" at 3262.7830640209s). 
Physically that should not happen, and top_ports.m_flow has a min-value of 0. 

You have to zoom in to notice that B2.m also decreases slightly at that time from 4.972674415057601 to 4.972673539863315 (so about 13 drops of water).

As far as I can tell the model does not directly try to prevent this flow-situation.

Results using Dymola 2019 (and turning off equidistant time grid and storing in double precision).
(Still present in current beta, and could be reproduced with other solvers as well.)

### PR DESCRIPTION
**Pull request by casella**
This PR improves the controller of AST_BatchPlant by adding a suitable delay between the activation of the pumps and valves upstream V3 and V6 and their actual opening. This is more realistic, as it allows the pressure to stabilize, and it avoids a very short, but quite large, unrealistic backflow through those valves.

A bit of backflow is still present, but that cannot be eliminated unless the valve opening is a ramp and is not governed by a boolean signal.

This PR fixes #2686

### CODE REVIEW

**Comment by casella** [comment]
The PR was tested successfully with Dymola. OpenModelica still fails at time=2083, but at least produces the expected result before that.

We'll try to address the failure at time=2083, which I guess is due to extreme model stiffness, during the beta release period.

**Comment by beutlich** [comment]
It also simulates in SimulationX with the following two "non-zero" regions:

grafik

grafik

**Comment by dietmarw** [comment]
I had another look at this "fix" and as @HansOlsson correctly pointed out it does not solve the original issue. So as I understand it the issue occurs because a "real" model of water is controlled by an "ideal" valve. So what about instead of manipulating the sequences so that the model works in exactly this setup (which is not even the case and is also not useful as example for other users then) to use this as valve instead:
image

**Comment by casella** [comment]
@dietmarw, sounds good to me. 

In fact, I wanted to do something similar, but I simply lacked the time to do that these days. I'll see what I can do tomorrow.

To be honest, I cannot guarantee that there won't be _any_ reverse flow by doing this, but I expect the glitch to be really minor at that point. In which case, I hope the "fix" will be good for you guys 😄

**Comment by dietmarw** [comment]
Excellent. If you think it's of general interest and not just for that example you might want to place that new `ValveRamp` (maybe?) next to `ValveLinear` and `ValveDiscrete`.

**Comment by casella** [comment]
Good idea

**Comment by dietmarw** [comment]
@casella That "tomorrow" was now about 4 days ago ;-)

**Comment by casella** [comment]
Ok, I just followed @dietmarw's advice:
- I added a ValveDiscreteRamp model which has the same boolean input as ValveDiscrete, but opens gradually using a trapezoid signal generator.
- I used that model instead of ValveDiscret in the AST_BatchPlant example
- I set the opening/closing times of the valves and the on/off times of the pumps, which were previously both zero, to realistic values: 0.1 s for the valves (solenoid-actuated) and 0.3 s for the pumps

Now the pressure profiles are correct, and the flows through V3 and V6 never get negative.

This hopefully fixes #2686 for good.

**Comment by HansOlsson** [comment]
I cannot see that problems are gone, I still get a negative dip for V6.m_flow around 741s.

(Tested with Dymola 2020x; double precision, non-equidistant time-grid and tolerance=1e-7 just in case. And I see that it is declared using Modelica.Fluid.Valves.ValveDiscreteRamp).

**Comment by casella** [comment]
@dietmarw never mind bothering the other library officers. It turns out V3 and V6 had a small leak when closed, which is sometimes added to avoid numerical issues when you have multiple valves which are series-connected and are all closed, because the pressure in-between becomes undetermined. 

In the case of V3 and V6 this was not really required, because the downstream pressure is fixed to the atmospheric value. I just reset `opening_min` to the default value of zero and even that tiny backflow is now gone, even with double precision and no equidistant time grid.

I hope this makes it work for you and for @HansOlsson and we can finally merge this PR into 4.0.0 😃

**Comment by hubertus65** [comment]
From the modeling point of view, I am fine with all changes. Here is my nitpicking: if I look at the result with this "numerical glitch" there, I can already smell the difficulties of obtaining numerically good enough equal results with another tool. We do that with all models in MSL, and OpenModelica is on the way there. The result in of V6.port_a.m_flow is a total nightmare to reproduce in another tool. Today it is not, but it should be our ambition for MSL testing. It may be possible to "hide" that glitch by an equidistant time grid (in several tools), but that is fragile and cheating. Both you @casella , and we at Modelon will burn unproductive hours to reproduce that crap. So the patch does not fulfill what should be our objective for MSL example models. The correct patch might be a different Medium model that fits better with basically incompressible assumptions, and this one just creates intermediate troubles. We should aim at example models that robustly run on multiple tools, this one will not. My perspective may be unique, but it shouls also be yours, Francesco @casella. @HansOlsson, I have an interesting challenge for you: produce results with both RadauIIa and Dassl in Dymola that compare as equal by cvscompare on this model. That is probably as difficult as with different tools. Have fun!

**Comment by casella** [comment]
I agree with @hubertus65 comments in general.

@hubertus65, I am convinced that the fixes I made make the model more robust w.r.t. different solvers and tools. You can test it, or take my word on it. Please just don't kill it in the cradle. There will be time during the RC1 period to test it with JModelica and report if you have problems with it.

**Comment by HansOlsson** [comment]
@hubertus65 I agree that this model is numerically challenging, and it may be that we should re-design it.

My concern was that it shows non-physical effects without any explanation - and that people building similar real models would get similar issues; and wonder what is happening.

However, digging deeper regarding actual models I now realize that Modelica.Fluid.Examples.AST_BatchPlant.BaseClasses.TankWithTopPorts does not check the flow at top-ports, whereas Modelica.Fluid.Vessels.OpenTank does (I assume there is some deeper explanation for this). It seems unlikely that people directly use Modelica.Fluid.Examples.AST_BatchPlant.BaseClasses.TankWithTopPorts - in their own models, so I think this is likely fine now.

**Comment by wischhusen** [comment]
I agree with @hubertus65. Moreover, I think we defined a bandwidth for differences in regression testing somewhere. I think that this quality measure should also hold to differences in tool result. In my personal opinion the potential for tool differences must be very low now and certainly below that limit. 

In the end, this model is a demonstrator and not used for design of batch plants. On the other hand people could come across the idea to reuse the base models for their purposes. Hence it would be required to check first if the base models can either substituted by the "standard" models of the Fluid. If not, potential failures (if any) must be corrected.

**Pull request merged**
