### PR TITLE
Update comparison signals for ModelicaTest.Fluid.TestComponents.Fittings.TestJunctionTraceSubstances

### PR DESCRIPTION
**Pull request by Esther-Devakirubai**
Backport #4427

### CODE REVIEW

**Review by casella — APPROVED** [review]
LGTM

**Review by arunkumar-narasimhan — APPROVED** [review]
LGTM

**Comment by casella** [comment]
@Esther-Devakirubai please sign the Contributor Licence Agreement - basically, a copyright transfer to the Modelica Association of everything which is pushed to the Modelica repositories. Strange that you managed without doing that until now or, if you've done it already, there is probably some glitch somewhere.

**Comment by Esther-Devakirubai** [comment]
> @Esther-Devakirubai please sign the Contributor Licence Agreement - basically, a copyright transfer to the Modelica Association of everything which is pushed to the Modelica repositories. Strange that you managed without doing that until now or, if you've done it already, there is probably some glitch somewhere.

@casella Did it. After that some checks are passed but still merge is blocked.

**Comment by casella** [comment]
Done, thanks!

**Pull request merged**
