### PR TITLE
Update wrapAngle.mo

### PR DESCRIPTION
**Pull request by lvanfretti**
Bracket typos in function description and documentation.

### CODE REVIEW

**Review by dietmarw — COMMENTED** [review]
I think this PR is invalid since the documentation is correct it with respect that the range does **not** include the lower -pi or the upper 2*pi. Hence `]-pi,pi]` and `[0,2*pi[`are correct.

**Comment by dietmarw** [comment]
One could argue though that the non-standard `]-pi,pi]` and `[0,2*pi[` should be changed to standard notation `(-pi,pi]` and `[0,2*pi)` but I'm not sure that this is really that important also since it means changing it in several other places in the MSL.

**Comment by HansOlsson** [comment]
> One could argue though that the non-standard `]-pi,pi]` and `[0,2*pi[` should be changed to standard notation `(-pi,pi]` and `[0,2*pi)` but I'm not sure that this is really that important also since it means changing it in several other places in the MSL.

**Both** variants are supposed to be standard notation.
https://en.wikipedia.org/wiki/Interval_(mathematics)#Including_or_excluding_endpoints
https://en.wikipedia.org/wiki/ISO_31-11

**Comment by dietmarw** [comment]
Ah ok, in that case Wolfram ought to update it's pages ;-) https://mathworld.wolfram.com/OpenInterval.html

Anyway, I would close this PR as invalid but leave the decision to the library officers @AHaumer and @MartinOtter

**Comment by lvanfretti** [comment]
> **Both** variants are supposed to be standard notation. https://en.wikipedia.org/wiki/Interval_(mathematics)#Including_or_excluding_endpoints https://en.wikipedia.org/wiki/ISO_31-11

As a plain vanilla user, the notation `(-pi,pi]` and `[0,2*pi)` is easier to understand. Most people are familiar with that one... that is what it confused me in the first place.

**Comment by dietmarw** [comment]
The point is that the wrap angle will **not** create "-pi" but anything **larger than** "-pi" (and the same for smaller than 2*pi). This is important since you do not want to have double identity conversions of a linear increasing angle.

**Comment by lvanfretti** [comment]
Yes, I understand. As I said, it is just a less common notation used in the documentation that what one would expect a normal user to know. Perhaps, adding a clarification could be better than modifying the existing text?

**Review by AHaumer — CHANGES_REQUESTED** [review]
[-pi,pi] is wrong. 
I'm comfortable both with ]-pi,pi] and (-pi,pi].
So use on of the two formulations.

**Comment by christiankral** [comment]
OK, depending on this discussion I propose:

1) to keep the original implementation
2) add a link to https://en.wikipedia.org/wiki/Interval_(mathematics)#Including_or_excluding_endpoints so that pepole not familiar with the used nomenclature can look it up

I am adding the link to the block and the function.

**Review by dietmarw — APPROVED** [review]

**Review by AHaumer — APPROVED** [review]

**Pull request merged**
