### PR TITLE
Avoid having both start-value and initial equation

### PR DESCRIPTION
**Pull request by HansOlsson**
Clearly having a value as both start-value and initial equation as in these models is a bit redundant.

However, it is not only a problem of being redundant, but can also lead to a very bad error when using `InitialOutput` since the start-value has normal priority and one may thus get both the initial equation for `InitialOutput` **and** the start-value corresponding to` InitialState`. (Note it shouldn't occur for InitialState, and doesn't occur for examples in MSL since all start-values are fixed in MSL.)

I will preliminary discuss this when presenting "Modelica 3.6 - Changes, Benefits and Implementation", at 15th International Modelica Conference, https://www.youtube.com/watch?v=yyPDFkldLN4&t=430s

### CODE REVIEW

**Comment by HansOlsson** [comment]
[TestPI.zip](https://github.com/modelica/ModelicaStandardLibrary/files/12879213/TestPI.zip)
A test-example showing bad selection of start-values.

Without changes we would get states as follows:

> 
> The initial conditions are not fully specified.
> Dymola has selected default initial conditions.
> 
> Assuming fixed start value for the continuous states:
> driveLine.spring.phi_rel(start = 0) At level 3. Original start-value at level 3 .
> driveLine.spring.w_rel(start = 0) At level 2. Original start-value at level 2 .
> PI.I.y(start = PI.I.y_start) At level 1. Original start-value at level 3.
> 
> There were 1 continuous states with start values that were not selected:
> driveLine.inertia1.w(start = 0) At level 2. Original start-value at level 2.

However, driveLine.inertia1.w should be prioritized over PI.I.y. Dymola 2024x has a special heuristic to avoid this case - but we should update the library.

**Comment by Harisankar-Allimangalath** [comment]
@AHaumer and @MartinOtter  can you please  review the changes . Thank you

**Comment by HansOlsson** [comment]
> @AHaumer and @MartinOtter can you please review the changes . Thank you

Please please, preferably so that it can merged before release-branch on Friday January 12th?

**Review by AHaumer — APPROVED** [review]
Fine with me

**Review by MartinOtter — APPROVED** [review]

**Review by hubertus65 — CHANGES_REQUESTED** [review]
I think this view may be a bit too simplistic. Both components can be part of large non-linear systems in case of being part of a controller, in a steady-state loop (i.e. der(y) = 0.0) with a non-linear plant. In that case, a start value for y is necessary, even a nominal value would be useful. The default start value of 0.0 might cause failure. That would be in combination with fixed= false, and only if InitType == Init.SteadyState. I think that is a doable change.

**Comment by MartinOtter** [comment]
> I think this view may be a bit too simplistic. Both components can be part of large non-linear systems in case of being part of a controller, in a steady-state loop (i.e. der(y) = 0.0) with a non-linear plant. In that case, a start value for y is necessary, even a nominal value would be useful. The default start value of 0.0 might cause failure. That would be in combination with fixed= false, and only if InitType == Init.SteadyState. I think that is a doable change.

The user has always the possibility to set start values as modifiers of iteration variables of a nonlinear loop. 
Since this is standard, it seems not necessary that particular parameters of a model are used in this very
special case. Since Hans pointed out that there might be a bad problem if InitialOutput is selected
and a start value for the state is set, then this looks more severe. So, I think this change is fine.

**Comment by hubertus65** [comment]
I still think that my suggestion is a better and more complete proposal. We don't have good test cases / examples for that case AFAIK, so it is easy to miss a newly introduced problem. For an end user, it can mean quite a bit of digging, and the parameter y_start, now unused, is still there, luring people to set it - to zero effect. From a UX-standpoint, quite bad for beginners.

**Comment by MartinOtter** [comment]
> I still think that my suggestion is a better and more complete proposal. We don't have good test cases / examples for that case AFAIK, so it is easy to miss a newly introduced problem. For an end user, it can mean quite a bit of digging, and the parameter y_start, now unused, is still there, luring people to set it - to zero effect. From a UX-standpoint, quite bad for beginners.

Sorry, did not recognize that you made a proposal, and when reading your text, I don't understand your proposal. Can you give your proposal in form of Modelica code.

**Comment by hubertus65** [comment]
I made a suggestion in a new pull request. Please test, since I didn't have a setup right now to test, but now you have a Modelica code suggestion to fix.

**Pull request merged**
