### PR TITLE
Rename mue to mu

### LINKED ISSUE #194: Change greek parameter name 'mue' to 'mu', 'nue' to 'nu' and 'lamda' to 'lambda' in MSL
**Reported by christiankral on 23 Jul 2009 15:07 UTC**
In the MSL the following packages are using a parameter called `mue`:

 * `Modelica.Mechanics.MultiBody`
 * `Modelica.Mechanics.Rotational` 
 * `Modelica.Mechanics.Translational`
 * `Modelica.Constants`

The intention was to represent the Greek letter for m (µ), but it is unfortunately spelled incorrectly. The correct spelling is "mu", not "mue". Therefore, these parameter names should be changed once the next conversion script is scheduled.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/194

### PR DESCRIPTION
**Pull request by tobolar**
close #194

### CODE REVIEW

**Comment by beutlich** [comment]
Let me fix the merge conflict.

**Comment by christiankral** [comment]
Shouldn't there also be a conversion command for the constant `Modelica.Constants.mu_0` itself, or did I overlook it.

**Comment by tobolar** [comment]
@christiankral Fixed, many thanks.

**Comment by tobolar** [comment]
Shall be covered with ModelicaTestConversion4. Or do you miss something particular?

**Pull request merged**
