### PR TITLE
Update matio library to 1.5.28

### PR DESCRIPTION
**Pull request by beutlich**
Follow-up of #4455.

### CODE REVIEW

**Comment by casella** [comment]
@beutlich do we have an established procedure to test these C-code updates? Do you have suggestions about that? Thanks!

**Comment by beutlich** [comment]
> @beutlich do we have an established procedure to test these C-code updates? Do you have suggestions about that? Thanks!

We have build and test stages (/.CI/Test/TablesFromMatFile.c) via CI.

**Review by casella — APPROVED** [review]
LGTM

**Comment by maltelenz** [comment]
I don't know enough about this part of MSL to make a sensible review.

**Review by HansOlsson — APPROVED** [review]
Ok, I noticed some interesting coding style changes - but it seems fine.

**Comment by beutlich** [comment]
> Ok, I noticed some interesting coding style changes - but it seems fine.

I guess it is addressed by #4506. Additionally I noticed some macro issue and compiler warnings.

**Pull request merged**
