### PR TITLE
Remove test for value of hashString

### PR DESCRIPTION
**Pull request by HansOlsson**
Part of #3415

### CODE REVIEW

**Comment by HansOlsson** [comment]
Hmm... Ok, tried to follow advice on
https://docs.gitlab.com/ee/topics/git/numerous_undo_possibilities_in_git/
Didn't work well.

**Comment by HansOlsson** [comment]
> Hmm... Ok, tried to follow advice on
> https://docs.gitlab.com/ee/topics/git/numerous_undo_possibilities_in_git/
> Didn't work well.

Ah, it was messed up in the other branch and merged incorrectly - ouch.

**Comment by beutlich** [comment]
Can do it later,

**Comment by HansOlsson** [comment]
The log is a mess, but it should be the correct changes; and with squash-merge it will be ok.

**Pull request merged**
