### PR TITLE
Add Include annotation for external function interface

### LINKED ISSUE #3446: External functions should specify 'Include' to make use of existing prototypes
The external function `Modelica.Utilities.Files.fullPathName` seems to be typical in the sense that it doesn't use the `Include` annotation, meaning that the function call isn't checked against the existing prototype in [ModelicaInternal.h](https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Resources/C-Sources/ModelicaInternal.h).

It would improve the quality of MSL if all external functions made use of the `Include` annotation.

More generally, the use of `Include` has a clear benefit in tools that call the external function from C++ code, as the presence of `Include` forbids the tool from generating a prototype based on how the function is called, meaning that the compiler will refuse to compile the call instead of compiling the call based on an incorrect automatically generated prototype (which will then likely cause a simulation crash).  In tools that call the external function from C code, there is no drawback of specifying `Include`, but the advantage is smaller as the compiler will still compile the call with a warning if the prototype is missing.

### PR DESCRIPTION
**Pull request by beutlich**
Resolves #3446 as proposed.

### CODE REVIEW

**Comment by HansOlsson** [comment]
Seems good, but we'll also check this. 
However, that check will likely be during the night; with review tomorrow.

**Comment by HansOlsson** [comment]
The first issue I found should be corrected in my branch of this branch in:
https://github.com/HansOlsson/Modelica/tree/beutlich-add-include-annotation
(need to figure out how to push that directly; but after coffee and meetings.)

**Comment by beutlich** [comment]
> 
> 
> The first issue I found should be corrected in my branch of this branch in:
> https://github.com/HansOlsson/Modelica/tree/beutlich-add-include-annotation
> (need to figure out how to push that directly; but after coffee and meetings.)

Yes, that should work.

I also noticed that Dymola generates every found Include annotation, no matter how often it is required. One other possibility would be to eliminate duplicated Include annotations and only print each unique annoation once.

**Comment by HansOlsson** [comment]
> > The first issue I found should be corrected in my branch of this branch in:
> > https://github.com/HansOlsson/Modelica/tree/beutlich-add-include-annotation
> > (need to figure out how to push that directly; but after coffee and meetings.)
> 
> Yes, that should work.
> 
> ~I also noticed that Dymola generates every found Include annotation, no matter how often it is required. One other possibility would be to eliminate duplicated Include annotations and only print each unique annotation once.~ Edit: OK, that will not help if different files define the same macro.

Exactly. But I see the other point as well, but that doesn't influence the MSL-release.

**Comment by beutlich** [comment]
> need to figure out how to push that directly

For now, I squash-merged your PR, which worked as expected. Direct push is also possible, but after coffee and meetings 😄

**Comment by beutlich** [comment]
> I have some linking issue for some (not all) table-examples

The usertab ones?

**Comment by beutlich** [comment]
> so it is likely the same in master.

Please confirm based on evidence.

**Comment by HansOlsson** [comment]
> > so it is likely the same in master.
> 
> Please confirm based on evidence.

Hmm.. You are right, I **cannot** confirm this issue in master.
And it is ModelicaTest.Tables.CombiTable1Dv.Test29 (and some more).

**Comment by HansOlsson** [comment]
> > > so it is likely the same in master.
> > 
> > 
> > Please confirm based on evidence.
> 
> Hmm.. You are right, I **cannot** confirm this issue in master.
> And it is ModelicaTest.Tables.CombiTable1Dv.Test29 (and some more).

I have now understood the issue (due to some local changes in another file (ModelicaInternal.c) causing linking problem), and it is not an issue with this PR.

It may be an issue for people testing with Dymola.

If so the following should work:
Advanced.PlaceDymolaSourceFirst=2
Remove Modelica/Resources/C-Sources/ModelicaInternal.c

**Comment by beutlich** [comment]
> Advanced.PlaceDymolaSourceFirst=2

Will be applied for the creation of the reference results, see https://github.com/modelica-tools/msl-release/pull/3/commits/f230d75a65cf49866062388b23e3c0cada70b547

> Remove Modelica/Resources/C-Sources/ModelicaInternal.c

Documented in the [Wiki](https://github.com/modelica/ModelicaStandardLibrary/wiki/Regression-testing-of-Modelica-and-ModelicaTest#run-the-pedantic-check-in-dymola)

**Pull request merged**
