### PR TITLE
Update CoupledClutches.mos 

### PR DESCRIPTION
**Pull request by Harisankar-Allimangalath**
backport #4350

### CODE REVIEW

**Review by HansOlsson — APPROVED** [review]

**Review by DagBruck — APPROVED** [review]

**Comment by Harisankar-Allimangalath** [comment]
@dietmarw can you please review the changes .

Thankyou

**Comment by dietmarw** [comment]
There is no need since it only needs 2 approved reviews.

**Comment by dietmarw** [comment]
What is missing is which milestone this should go into. Is this meant for 4.1.0 (probably to late now) or for 4.1.1. This is crucial also to mark before a review is triggered.

**Comment by Harisankar-Allimangalath** [comment]
Hi @dietmarw , Thankyou  for the information , I copied the settings , labels  from #4350 and kept the milestone blank as it was missing in the original PR . you are right , adding that would also have been better . @HansOlsson @DagBruck  can you please merge this . 

Thankyou

**Comment by dietmarw** [comment]
Not having a milestone set is a **HUGE** mistake. **EVERY** PR needs to have a milestone otherwise it is impossible to later find out which changes where done for which version. You should go through **all** PRs (open and closed and also closed issues) without an assigned milestone and assign them appropriately.

**Review by hubertus65 — APPROVED** [review]

**Pull request merged**
