### PR TITLE
Improve meaning of Modelica.Math.Nonlinear.Examples.QuadratureLobatto3

### PR DESCRIPTION
**Pull request by beutlich**
See #2636.

### CODE REVIEW

**Comment by beutlich** [comment]
Well, when removing dummy variable x, we also could remove dummy states q and qd, since only parameter s is of interest in this example.

**Comment by HansOlsson** [comment]
> Well, when removing dummy variable x, we also could remove dummy states q and qd, since only parameter s is of interest in this example.

Possibly, but the oscillator coupled to the result of integration at least looks normal - and illustrates that the quadrature can be used in a usual model. Obviously it would be better if the entire model was more meaningful.

**Comment by beutlich** [comment]
> Obviously it would be better if the entire model was more meaningful.

Agreed. The example topic is

> This example demonstrates how to utilize a function as input argument to a function in a model.

Hence, the oscillator is not required here.

**Comment by MartinOtter** [comment]
After removing the state equations, the result is that a parameter is computed once and the variables of the model are constant for the whole simulation. I do not see why this example model is more meaningful as the original model. Please, keep the state equations.

**Comment by beutlich** [comment]
The motivation was to drop all dummy parts form the example that are not required and solely focus on

> This example demonstrates how to utilize a function as input argument to a function in a model.

**Comment by MartinOtter** [comment]
The example is a very simplified model to show how elastic systems are modeled. Please, re-introduce the second order differential equation and add the following text to the info-layer:

_This example shows in a very simplified way the basic approach to model distributed systems with the Ritz method (for more details, see for example [The DLR FlexibleBodies Library to Model Large Motions of Beams and of Flexible Bodies Exported from Finite Element Programs ](https://www.modelica.org/events/modelica2006/Proceedings/sessions/Session1d1.pdf) ). The displacement field u(c,t) (c: undeformed position, t time) is hereby approximated with space dependent mode shapes Phi(c) and time-dependent modal amplitudes q(t), that is u = Phi(c)*q(t). When inserting this decomposition in the mechanical equations and then integrating over all particles, terms such as "integral(Phi(c)*dc)*q(t)" appear and the first term can be computed beforehand once with the Lobatto method. By this approach the partial differential equations  are transformed to differential equations._

**Comment by beutlich** [comment]
> Please, re-introduce the second order differential equation and add the following text to the info-layer:

Done by #3234. Please add your review.

**Pull request merged**
