### PR TITLE
Fix uninitialized memory

### PR DESCRIPTION
**Pull request by beutlich**
As reported by https://github.com/modelica/ModelicaSpecification/issues/2403

### CODE REVIEW

**Comment by henrikt-ma** [comment]
Why don't we wait and see whether `ModelicaAllocateString` is supposed to terminate these strings?

**Comment by beutlich** [comment]
> 
> 
> Why don't we wait and see whether `ModelicaAllocateString` is supposed to terminate these strings?

Because I consider it a bug. See #3004 for a similar issue.

**Comment by HansOlsson** [comment]
Note: I was going to comment on this - seems I was too late.

The most obvious solution would be to just `return "";` as the specification only states that non-literal return strings must be allocated with ModelicaAllocateString.

**Comment by henrikt-ma** [comment]
> The most obvious solution would be to just `return "";` as the specification only states that non-literal return strings must be allocated with ModelicaAllocateString.

Right, but in that case I would suggest to also make sure that we have test models that take these code paths, so that implementations really become aware that they must do the tedious analysis of what kind of pointer that is being returned.

**Pull request merged**
