### PR TITLE
Improved icons of shapes

### PR DESCRIPTION
**Pull request by AHaumer**
Refers to #3218.

### CODE REVIEW

**Comment by DrMartinKuhn** [comment]
The icon and description of the "Hollow cylinder with radial flux" is not very intuitive to me compared to the "(hollow) cylinder with axial flux". I recommend to rotate the figure in the documentation by 90°

**Comment by AHaumer** [comment]
Description and image are the same for a long time, I just implemented an icon. 
To me the icon is fine - it suggest a radial flow of flux. I wouldn't rotate the icon. 
Compare with axial flux ...

**Comment by christiankral** [comment]
@AHaumer Please consider https://github.com/AHaumer/ModelicaStandardLibrary/pull/4

- Some of the newly developed icons were not used in the `FluxTubes` library (fixed)
- `QuasiStatic.FluxTubes` wasn't updated in the same way (fixed)

**Comment by christiankral** [comment]
Once https://github.com/AHaumer/ModelicaStandardLibrary/pull/4 is accepted, I am fine with this PR.

**Pull request merged**
