### PR TITLE
Merge HeatingDiode with Diode

### PR DESCRIPTION
**Pull request by beutlich**
@christophclauss Can you pease work on the following TODOs

- [x] Description for useTemperatureDependency -> Done.
- [x] Utilize useTemperatureDependency in the equations -> Done.
- [x] Dialog.enable annotation for N, EG, TNOM and XTI? -> Done.
- [x] Rename TNOM to Tnom (to match the parameter name of HeatingNMOS/HeatingPMOS)? -> Suspended.

See #2899.

### CODE REVIEW

**Comment by christophclauss** [comment]
@beutlich 
Since I did not yet work on the files of a fork, but want to get experience, the question arises:
Where exactly can I find the text files of this pull request?

**Comment by beutlich** [comment]
Got to [Files changed](https://github.com/modelica/ModelicaStandardLibrary/pull/3010/files) and for each of the files, select from the three dots menu at the heading the View file option:
* [Modelica/Electrical/Analog/Examples/HeatingRectifier.mo](https://raw.githubusercontent.com/modelica/ModelicaStandardLibrary/f33689a7069deced8e268ff7e0df3d764e923739/Modelica/Electrical/Analog/Examples/HeatingRectifier.mo)
* [Modelica/Electrical/Analog/Semiconductors.mo](https://raw.githubusercontent.com/modelica/ModelicaStandardLibrary/f33689a7069deced8e268ff7e0df3d764e923739/Modelica/Electrical/Analog/Semiconductors.mo)

Or from the command line:
```
git remote add beutlich https://github.com/beutlich/ModelicaStandardLibrary.git
git fetch beutlich
git checkout -b merge-diode remotes/beutlich/merge-diode
```

**Comment by beutlich** [comment]
> Where exactly can I find the text files of this pull request?

@christophclauss Did you get on with the instructions?

**Comment by beutlich** [comment]
> @christophclauss Can you pease work on the following TODOs

Finally, I resolved the missing TODOs myself to get this PR in review state eventually.

> Rename TNOM to Tnom (to match the parameter name of HeatingNMOS/HeatingPMOS)?

I decided to leave it as is for now. We still might consider to harmonize the parameter names in a seprate pull request.

**Pull request merged**
