### PR TITLE
Fix syntax errors in ModelicaReference documentation snippets

### PR DESCRIPTION
**Pull request by Harisankar-Allimangalath**
backport of #4275

### CODE REVIEW

**Comment by Harisankar-Allimangalath** [comment]
back port of #4275

**Comment by beutlich** [comment]
@Harisankar-Allimangalath Please set summary, labels and milestone correctly.

**Review by beutlich — APPROVED** [review]

**Comment by Harisankar-Allimangalath** [comment]
> @Harisankar-Allimangalath Please set summary, labels and milestone correctly.

sure sir I shall check that from next time onwards , Thankyou .

**Review by maltelenz — APPROVED** [review]

**Comment by Harisankar-Allimangalath** [comment]
@beutlich @HansOlsson  can you please merge this . Thanks

**Comment by Harisankar-Allimangalath** [comment]
@AHaumer can you please merge this

**Pull request merged**
