### PR TITLE
Move ZeroForceAndTorque from Sensors to Forces

### LINKED ISSUE #2425: Move ZeroForceAndTorque into Modelica.Mechanics.MultiBody.Forces.Internal
The class `Modelica.Mechanics.MultiBody.Sensors.Internal.ZeroForceAndTorque` should be better placed in the package `Modelica.Mechanics.MultiBody.Forces.Internal`.

### PR DESCRIPTION
**Pull request by beutlich**
Close #2425.

### CODE REVIEW

**Comment by beutlich** [comment]
@tobola Please update your approval. Thanks.

**Comment by beutlich** [comment]
> There are no instances' annotations in the ModelicaTestConversion4 at the moment but I suppose it's fine to have some in a case the unit test has been composed in diagram layer.

Yes, Placement annotations are not required for a conversion test. I tried to keep the test model minimal.

**Comment by tobolar** [comment]
But this is no obligation, is it? It is easy in many cases to simply assembly a test unit in the diagram layer but tedious to delete the annotations after that.

**Comment by beutlich** [comment]
Right, no obligation.

**Comment by tobolar** [comment]
@HansOlsson Exactly.

**Pull request merged**
