### PR TITLE
Fix formula of LinearDependency

### LINKED ISSUE #1724: Modelica.Blocks.Math.LinearDependency has strange formulation
**Reported by Joe Riel on 1 Jun 2015 14:58 UTC**
The relatively new block LinearDependency seems strange. It's defining equation is `y = y0*(1 + k1*u1 + k2*u2);`. y0 is a parameter; its description says it is an initial value, which makes no sense.  It is a scale factor (with a useless default of 0).  However, if its value is nonzero, then one cannot produce an output with a non-zero offset.  I'm thinking the block would be slightly more useful if the defining equation were `y = y0 + k1*u1 + k2*u2`.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1724

### PR DESCRIPTION
**Pull request by beutlich**
Close #1724.

### CODE REVIEW

**Comment by beutlich** [comment]
I consider this as a bugfix, that will be well documented in the release notes. LinearDependency is not used in the MSL and probably also not elsewhere due to its non-intuitive behaviour.

**Comment by MartinOtter** [comment]
> I consider this as a bugfix, that will be well documented in the release notes. LinearDependency is not used in the MSL and probably also not elsewhere due to its non-intuitive behaviour.

Note, this is certainly no bug fix, because the model works exactly as stated in the documentation. 

As library officer of the Modelica.Blocks library, I forbid you to make this change.

If you want to improve the situation, make it in a way that the user can cope with it. For example:

- Move this model in the ObsoleteModelica libray and provide a conversion script. If your claim is correct, that no one is using this model, no one will notice it. 
- If necessary, provide a model with a different name and your desired behavior.

**Comment by beutlich** [comment]
@MartinOtter If you close a PR with unmerged commits you should also change the milestone to never and add the invalid label. Otherwise the PRs will shos up in the automatically generated release notes.

**Comment by beutlich** [comment]
Superseded by #3095 where I added conversion to keep the backward compatibility.

**Pull request closed without merging**
