### PR TITLE
Drop deprecated LAPACK apis

### PR DESCRIPTION
**Pull request by jschueller**
dgelsx, dgegv, dgeqpf are deprecated since lapack 3.1.1 (2007), remove them

### CODE REVIEW

**Comment by jschueller** [comment]
I dont know how to create packages, can you provide details ?

**Comment by beutlich** [comment]
@HansOlsson @MartinOtter This PR is now ready for your review.

**Comment by beutlich** [comment]
> 
> 
> The work-areas for dgeqp3 does not seem ideal since:
> 
>     * It is the minimum possible; which will not utilize the level-3 block algorithm in a good way. Would it be possible to have lwork as an optional input (with suitable default)?
> 

Hm, could do so. What would be a suitable default for lwork then? Leave it as `max(1, 3*size(A, 2) + 1)`?


>     * The work-area length is duplicated. If we cannot use work[lwork] would it be possible to not have "lwork" as a variable and instead replace lwork in the argument list by size(work,1)?

Many LAPACK functions do so (for example dgesvd_sigma) and I just adopted this style of implementation.

**Comment by HansOlsson** [comment]
> Hm, could do so. What would be a suitable default for lwork then? Leave it as max(1, 3*size(A, 2) + 1)?

Yes.

> Many LAPACK functions do so (for example dgesvd_sigma) and I just adopted this style of implementation.

You're right. That should likely be improved for more functions. 
However, it is related to the change in this PR, since level-3 routines need larger work-areas and we here switch to a level-3 implementation.

**Comment by beutlich** [comment]
>     * The work-area length is duplicated. If we cannot use work[lwork] would it be possible to not have "lwork" as a variable and instead replace lwork in the argument list by size(work,1)?

Note, that a an Integer variable lwork is mapped to `int` type in C, but size(work, 1) would map to `size_t` in C.

**Pull request merged**
