### PR TITLE
Made engine designs consistent w.r.t. the whole design scenario

### LINKED ISSUE #3132: Inconsistencies between engines of Mechanics.MultiBody.Examples.Loops
At the Modelica conference this year I presented a language extension for non-monotonic modeling (cf. [Modelica language extensions for practical non-monotonic modelling: on the need for selective model extension](https://modelica.org/events/modelica2019/proceedings/html/papers/Modelica2019paper3B1.pdf)). One of its running examples are the `Engine1a`, `Engine1b` and `Engine1b_analytic` models of `Mechanics.MultiBody.Examples.Loops` I used to demonstrate how easy consistency problems are introduced. The idea of these models is to design a final analytic engine model starting from an idealized model via one considering the gas force in the cylinder. They are inconsistent however, most likely because of _historically_ individual model-changes that have not been properly propagated throughout the whole design scenario.

The objective of this ticket is to fix these inconsistencies **by the ordinary means of Modelica 3.4 (i.e., not selective model extension, but simply manual fixing)**.

### PR DESCRIPTION
**Pull request by christoff-buerger**
This pull request fixes the inconsistencies between the `Engine1a`, `Engine1b` and `Engine1b_analytic` models of `Mechanics.MultiBody.Examples.Loops`. For details about these, please cf. Section 4.2 of [Modelica language extensions for practical non-monotonic modelling: on the need for selective model extension](https://modelica.org/events/modelica2019/proceedings/html/papers/Modelica2019paper3B1.pdf).

The pull request fixes #3132.

The changes are:
1. Consistent stop times:
   - Engine1b, Engine1b_analytic: stop time set from 0.5 to 5 (the time of Engine1a)
2. Consistent inertias:
   - Engine1bBase (=> Engine1b, Engine1b_analytic): set inertia(J = 1 "kg m^2") (the inertia of Engine1a)
3. Consistent FixedTranslation of cycle position:
   - Engine1bBase (=> Engine1b, Engine1b_analytic): set cylPosition(r = {0.15,0.45,0}) (the cycle position of Engine1a)
4. Consistent piston <-> cylinder connections:
   - Engine1b: connected pistion.a with cyclinder.b instead of rod3.a (the connection of Engine1a)
5. Consistent bearings:
   - Engine1b:
     - switched bearings b1 and b2 (according to Engine1a)
     - turned rod1 and connectingRod respectively
     - set rod1.r and connectingRod.r to {0,-0.2,0} (according to Engine1a)
6. Improved, consistent graphical layout

### CODE REVIEW

**Comment by beutlich** [comment]
@christoff-buerger Can we please have two separate fixes here:

1. First, the changes to MultiBody as I already reviewed.
2. Second, the changes targeting Modelica.Clocked which you can directly commit to the corresponding feature branch (since Modelica.Clocked is new in MSL anyway).

**Comment by christoff-buerger** [comment]
> @christoff-buerger Can we please have two separate fixes here:
 >   - One, targeting the existing models of MultiBody which I already reviewed.
 >   - Another one, targeting Modelica.Clocked which you can directly commit to the corresponding feature branch (since Modelica.Clocked is new in MSL anyway).

@beutlich: I am sorry for the chaos; I merged the synchronous stuff in by accident due to missing rights. It should be alright now again (I reverted the problematic commit for the pull-request).

**Comment by beutlich** [comment]
>  I am sorry for the chaos

I'll do a squash-merge later such that the back-and-forth commits will be removed from history,

**Comment by beutlich** [comment]
For the future, it is safer if you do not create PRs from master. You should use dedicated branches instead.

**Comment by christoff-buerger** [comment]
> Now I even changed Engine1a to extend from Engine1bBase as well.

@tobolar: I do not understand how that can be done? `Engine1a` is a model _without_ the gas force of the cylinder; the intention of `Engine1bBase` is to introduce the gas force such that `Engine1b` and `Engine1b_analytic` consider the gas-force.

I think your commit fa754542104e5042916d0cc5ef7c67dbd1033bbb is wrong and should be undone!

**Comment by christoff-buerger** [comment]
I checked now the version with the last changes of @tobolar, particular fa754542104e5042916d0cc5ef7c67dbd1033bbb.

We should revisit this. The now _common_ base model `Engine1bBase` has as description `"Model of one cylinder engine with gas force"`, but the gas-force has been removed in it. Instead, `Engine1b` and `Engine1b_analytic` individually reintroduce it.

I see two approaches to fix this:
 1. Undo fa754542104e5042916d0cc5ef7c67dbd1033bbb

or the following steps

 1. Change the description of `Engine1bBase` to `"Common model of one cylinder engine without gas force."`
 2. Introduce another new base-class, `Engine1bBase_GasForce`, which also includes the gas-force and inherits from `Engine1bBase`; its description would be  `"Common model of one cylinder engine with gas force."`
 3. Let `Engine1b` and `Engine1b_analytic` inherit from `Engine1bBase_GasForce` and `Engine1a` inherit from `Engine1bBase`.

@beutlich: How do you like us to proceed? New issue and branch and pull request?

**Comment by beutlich** [comment]
> New branch and pull request?

Exactly. Thank you.

**Pull request merged**
