### PR TITLE
Ensure that tests (via CTest) are built and run (CI)

### PR DESCRIPTION
**Pull request by beutlich**

### CODE REVIEW

**Comment by casella** [comment]
@beutlich what problem does this PR address? Any suggestion for reviewers?

**Comment by beutlich** [comment]
The ctest option [--no-tests](https://cmake.org/cmake/help/latest/manual/ctest.1.html#cmdoption-ctest-no-tests)=error was added to not silently accept CI builds with `-DBUILD_TESTING=OFF` (`ON` is default) (which happened to my accidently when working on CMake configs of other reprositories I was contributing).

**Review by casella — APPROVED** [review]
LGTM

**Review by maltelenz — APPROVED** [review]
Without having any deeper insight into how CI is used in this project, this seems sensible, and I trust @beutlich to know what is needed.

**Pull request merged**
