### PR TITLE
MSL v4.1.0-beta.1 feedback: Fix comparison signals

### PR DESCRIPTION
**Pull request by beutlich**
This an accumulated PR of all my findings when running the [ReleaseChecks](https://github.com/modelica-tools/msl-release)

* Remove empty lines in comparisonSignals.txt
* Remove unreferenced comparisonSignals.txt
* Fix signals names in comparisonSignals.txt (or rename in example model)
* ~Rename DemoSomething to DemonstrateSomething consistently (for all newly introduced example models)~

### CODE REVIEW

**Comment by henrikt-ma** [comment]
> * Rename DemoSomething to DemonstrateSomething consistently (for all newly introduced example models)

If we're in the process of renaming things, why don't just drop the `Demonstrate` prefix from a package name under `Examples`?

**Comment by HansOlsson** [comment]
> This an accumulated PR of all my findings when running the [ReleaseChecks](https://github.com/modelica-tools/msl-release)
> 
> * Remove empty lines in comparisonSignals.txt
> * Remove unreferenced comparisonSignals.txt
> * Fix signals names in comparisonSignals.txt (or rename in example model)
> * Rename DemoSomething to DemonstrateSomething consistently (for all newly introduced example models)

I don't consider using Demonstrate instead of Demo as an improvement; basically 'Demo' is well-known, even more used than Demonstrate and here it can also be seen as a noun, as a Demo(nstration) of Something.

**Comment by beutlich** [comment]
I have no strong opinion except than fixing the naming consistency and broken signalComparisons.txt that we have now. Feel free to push on this PR branch or file an alternative PR.

**Comment by beutlich** [comment]
Hm, seems to be closed by accident.

**Comment by beutlich** [comment]
@HansOlsson @henrikt-ma How to proceed? This PR holds some necessary fixes for the comparisonSignals.txt, but also some optional fixes for example naming.

**Comment by HansOlsson** [comment]
> @HansOlsson @henrikt-ma How to proceed? This PR holds some necessary fixes for the comparisonSignals.txt, but also some optional fixes for example naming.

I don't know. I would split off the Demo-naming part and just merge the rest now, and then discuss Demo.

**Comment by maltelenz** [comment]
> > @HansOlsson @henrikt-ma How to proceed? This PR holds some necessary fixes for the comparisonSignals.txt, but also some optional fixes for example naming.
> 
> I don't know. I would split off the Demo-naming part and just merge the rest now, and then discuss Demo.

Agreed, this could get us the uncontroversial fixes faster.

**Comment by AHaumer** [comment]
I'd be happy if you split this into 2 parts:
* change naming: IMHO unnecessary
* reference results
I don't understand: Is this fixing problems with some (not all) reference results, or just creating new ones?
If it's the second, I disagree (because that counteracts the idea of regression testing).

**Comment by beutlich** [comment]
PR contains only the required changes on the signal names. Please review again!

**Review by AHaumer — APPROVED** [review]
Looks ok

**Pull request merged**
