### PR TITLE
Update MultipleResonance.mo

### PR DESCRIPTION
**Pull request by Harisankar-Allimangalath**
backport invalid #4351 and its fix #4374

### CODE REVIEW

**Review by arunkumar-narasimhan — APPROVED** [review]

**Review by hubertus65 — APPROVED** [review]

**Review by HansOlsson — CHANGES_REQUESTED** [review]
This is not correct; it should also be corrected on master.

**Comment by hubertus65** [comment]
> This is not correct; it should also be corrected on master.
I am not so fluent in git as to know how to do that best: @HansOlsson, couldn't you take action?

**Comment by beutlich** [comment]
> This is not correct; it should also be corrected on master.

Addressed by #4374.

**Review by AHaumer — APPROVED** [review]
fine with me

**Review by HansOlsson — APPROVED** [review]
Ok

**Review by HansOlsson — APPROVED** [review]
Ok

**Pull request merged**
