### PR TITLE
Add format attributes to functions in ModelicaUtilities

### PR DESCRIPTION
**Pull request by beutlich**

### CODE REVIEW

**Comment by beutlich** [comment]
I somehow remember that having defined(__clang) && __has... on the same line did not succeed in clang.

**Comment by HansOlsson** [comment]
> I somehow remember that having defined(__clang) && __has... on the same line did not succeed in clang.

In that case I would propose adding a comment about this.

**Comment by beutlich** [comment]
At least that is/was the reason why I have it similar with the noreturn attribute for clang.

**Comment by beutlich** [comment]
Now, that I check again, GCC fails to compile if it sees __has_attribute.

I'll revise the PR.

**Comment by beutlich** [comment]
@HansOlsson Can you please review again. Thanks.

**Comment by beutlich** [comment]
Ah, 9 seconds too late.

**Pull request merged**
