### PR TITLE
First figure

### PR DESCRIPTION
**Pull request by Harisankar-Allimangalath**
back port of #4094

### CODE REVIEW

**Review by henrikt-ma — APPROVED** [review]
Looks good.

**Review by maltelenz — APPROVED** [review]

**Comment by Harisankar-Allimangalath** [comment]
@henrikt-ma @maltelenz I am not authorized to merge this PR ,  This is how it shows for me 

image

**Comment by maltelenz** [comment]
Same for me. I'm guessing @beutlich has more authorization, but @casella and @AHaumer (in their role as project leaders) may want to review the list of people authorized to merge to the maint branch (or decide not to, and take on the burden to press all the merge buttons themselves).

**Comment by maltelenz** [comment]
> But isn't one problem that this PR needs to be manually rebased first, since there are conflicts?

It merges cleanly for me in my local client. What makes you say there are conflicts?

**Comment by HansOlsson** [comment]
> > But isn't one problem that this PR needs to be manually rebased first, since there are conflicts?
> 
> It merges cleanly for me in my local client. What makes you say there are conflicts?

The GitHub UI saying: "This branch cannot be rebased due to conflicts" and dimming "Rebase and merge" etc.

I believe the issue is that the commits contain bumping language version to 3.5 and then reverting that, which conflicts with other changes of language version.

So, it is a matter of cherry-picking the other 3 commits.

**Comment by maltelenz** [comment]
> The GitHub UI saying: "This branch cannot be rebased due to conflicts" and dimming "Rebase and merge" etc.

Maybe I can't see that because I'm not authorized enough for the maint branch :)

I'll create a separate PR with a clean cherry-pick.

**Comment by maltelenz** [comment]
Replaced by #4291 . Closing.

**Pull request closed without merging**
