### PR TITLE
Refs #2654: Fix IdealIntermediateSwitch icon

### PR DESCRIPTION
**Pull request by christiankral**

### CODE REVIEW

**Comment by dietmarw** [comment]
What about all the remaining icons from #2654 ?

**Comment by beutlich** [comment]
According to https://github.com/modelica/ModelicaStandardLibrary/issues/2654#issuecomment-398714455 all other icons are by purpose.

**Comment by dietmarw** [comment]
Sorry I don't see any comment saying so. Also having now the Heating resistor looking identical to a normal resistor ... not sure if that is really good.

**Comment by HansOlsson** [comment]
> Also having now the Heating resistor looking identical to a normal resistor ... not sure if that is really good.

At some point I think we should consider merging the Resistor-models since they only differ in naming of parameters and defaults - they both have the same temperature dependency and heat-generation possibility. (As far as I can tell, if that's wrong it should be clarified.)

**Comment by eshmoylova** [comment]
I looked at IEEE standard for electrical diagrams: https://www.ee.iitb.ac.in/~spilab/Tips/ansii_graphic_symbols_for_electrical_and_electronics_daigrams_1993.pdf
They have the same icons for a regular and heating resistor. The arrow across indicates a variable resistor.

**Comment by christiankral** [comment]
I very much agree on removing the HeatingResistor in the next MAJOR release of the MSL, since it is not needed any more. We shall mark it as obsolete...

**Comment by beutlich** [comment]
> I very much agree on removing the HeatingResistor in the next MAJOR release of the MSL, since it is not needed any more. We shall mark it as obsolete...

Can you prepare a PR for it.

**Pull request merged**
