### PR TITLE
Add phase currents to comparisonSignals.txt to consistently cover zero sequence currents

### LINKED ISSUE #3476: Reference trajectories of some variables in MSL 3.2.3 reference files only contain numerical noise
We are testing the results obtained on MSL 3.2.3 models with StopTime annotation in OpenModelica, comparing the results to the reference files produced by MAP-LIB using the CSV compare tool.

In a number of electrical machine tests, we get verification failures because of a individual variables, named either `zeroInductor.i0` or `i_0_s,` that should probably be zero if an exact solution of the DAEs was computed, but instead fluctuate randomly close to zero due to the inevitable numerical noise of numerical integrators. Since the numerical noise is very close to zero, high and low limits based on relative tolerances end up being very close to the noisy trajectory, which is basically impossible to replicate unless one uses exactly the same tool and the very same solver settings that were used to generate the reference result.

This means that it makes no sense at all to include these variables in the reference file.

Here is a list of models and variables that show this issue:
- [Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_DOL](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.3/files/Modelica_3.2.3_Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_DOL.diff.html)
- [Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_Initialize](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.3/files/Modelica_3.2.3_Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_Initialize.diff.html)
- [Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_Transformer](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.3/files/Modelica_3.2.3_Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_Transformer.diff.html)
- [Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_YD](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.3/files/Modelica_3.2.3_Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_YD.diff.html)
- [Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_withLosses](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.3/files/Modelica_3.2.3_Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_withLosses.diff.html)
- [Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SMPM_Braking](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.3/files/Modelica_3.2.3_Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SMPM_Braking.diff.html)
- [Modelica.Magnetic.QuasiStatic.FundamentalWave.Examples.BasicMachines.InductionMachines.IMC_Conveyor](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.3/files/Modelica_3.2.3_Modelica.Magnetic.QuasiStatic.FundamentalWave.Examples.BasicMachines.InductionMachines.IMC_Conveyor.diff.html)
- [Modelica.Magnetic.QuasiStatic.FundamentalWave.Examples.BasicMachines.InductionMachines.IMC_Transformer](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.3/files/Modelica_3.2.3_Modelica.Magnetic.QuasiStatic.FundamentalWave.Examples.BasicMachines.InductionMachines.IMC_Transformer.diff.html)
- [Modelica.Magnetic.QuasiStatic.FundamentalWave.Examples.BasicMachines.InductionMachines.IMC_YD](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.3/files/Modelica_3.2.3_Modelica.Magnetic.QuasiStatic.FundamentalWave.Examples.BasicMachines.InductionMachines.IMC_YD.diff.html)

These results are basically impossible to replicate with the accuracy expected by the CVS compare tool. This doesn't mean that the simulation is wrong, it just means that those reference variables should really not be checked, because they are structurally unreliable.

@christiankral , @AHaumer, can you please confirm that those variables should indeed be zero in an exact solution?

@beutlich, @GallLeo , I would recommend to remove them at once from the reference results of MSL 3.2.3. Please also make sure the same problem is not present in the MSL 4.0.0 reference files.

### PR DESCRIPTION
**Pull request by AHaumer**
addresses #3472 and resolves #3476

### CODE REVIEW

**Comment by dietmarw** [comment]
@AHaumer I don't think you meant to add the `*.sav` files to the repo.

**Comment by christiankral** [comment]
I am perfectly fine with the proposed changes. 

@AHaumer I however noted that the induction machine instance names are still `aimc` instead of `imc` which is, however, not a problem. As we changed the original `AsynchronousInductionMachines` class names to `InductionMachines` it may not be intuitive to the users.

**Comment by christiankral** [comment]
I think everything is done now.

**Comment by beutlich** [comment]
@AHaumer OK for you?

**Comment by beutlich** [comment]
@AHaumer OK for you?

**Comment by AHaumer** [comment]
Looks ok for me.
We still need a second review ...

**Comment by beutlich** [comment]
> We still need a second review ...

I believe @christiankral was only waiting for your approval comment and will do so later.

**Pull request merged**
