### PR TITLE
Exclude regression issues from generated Release Notes

### PR DESCRIPTION
**Pull request by beutlich**

### CODE REVIEW

**Comment by beutlich** [comment]
It is `V: 3.2.2-XXX`, not `V: v3.2.2-XXX`.

**Comment by sjoelund** [comment]
But it seems that the currently closed issues include things like #1990 which is a bug intended to target the milestone 3.2.2 and is not a bug in 3.2.2, right?

**Comment by beutlich** [comment]
#1990 is a bug in v3.2.2 and targeted for v3.2.3. All fine.

**Comment by beutlich** [comment]
The idea is to exclude (once closed) https://github.com/modelica/ModelicaStandardLibrary/labels/V%3A%203.2.3-beta.2 from the Release Notes for v3.2.3.

**Pull request merged**
