### PR TITLE
comparisonSignals of PowerConverters

### PR DESCRIPTION
**Pull request by Harisankar-Allimangalath**
backport #4353  , backport to maint/4.0.x

### CODE REVIEW

**Review by beutlich — DISMISSED** [review]
PR target shall be maint/4.1.x instead of maint/4.0.x.

**Comment by beutlich** [comment]
Edit, there also is #4372. I thought that maint/4.0.x no longer gets updates.

**Review by hubertus65 — APPROVED** [review]

**Review by christiankral — APPROVED** [review]

**Review by AHaumer — APPROVED** [review]
fine with me

**Comment by casella** [comment]
@beutlich we are not planning any release of MSL 4.0.1, are we?

**Comment by beutlich** [comment]
> @beutlich we are not planning any release of MSL 4.0.1, are we?

That's what you wrote to MAP-Lib members on 2024-01-16:

> Regarding the MSL4.0.1 milestone <https://github.com/modelica/ModelicaStandardLibrary/milestone/62>, there were 27 merged PRs there, which were all back-ports from master (I checked them one by one, just in case). Since we are not going to release 4.0.1, I just closed that milestone.

**Comment by casella** [comment]
Closing this PR as it is no longer useful

**Pull request closed without merging**
