### PR TITLE
Fix position of component's and parameter's name according to icon conventions

### PR DESCRIPTION
**Pull request by tobolar**
This PR addresses changes commented in https://github.com/modelica/ModelicaStandardLibrary/pull/3634#pullrequestreview-550959385 and a bit more. Typical changes done here:
- change position of component name,
- change position of parameter name,
- resize component name (as for assemblies JointUPS, etc.)

Note: The name of `LineForceWithTwoMasses` was not resized as it actually complies to conventions.

Clipboard03

Clipboard01

### CODE REVIEW

**Review by maltelenz — APPROVED** [review]
Using test model that I believe contains the changed classes:
```
model IconConventionsTest
  Modelica.Mechanics.MultiBody.Forces.Damper damper1 annotation(Placement(visible = true, transformation(origin = {-90, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.LineForceWithTwoMasses lineForceWithTwoMasses1 annotation(Placement(visible = true, transformation(origin = {-50, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.Spring spring1 annotation(Placement(visible = true, transformation(origin = {-10, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.SpringDamperParallel springDamperParallel1 annotation(Placement(visible = true, transformation(origin = {30, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.SpringDamperSeries springDamperSeries1 annotation(Placement(visible = true, transformation(origin = {70, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointSSP jointSSP1 annotation(Placement(visible = true, transformation(origin = {-80, -20}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointSSR jointSSR1 annotation(Placement(visible = true, transformation(origin = {-20, -20}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUPS jointUPS1 annotation(Placement(visible = true, transformation(origin = {40, -20}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUSP jointUSP1 annotation(Placement(visible = true, transformation(origin = {-80, -60}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUSR jointUSR1 annotation(Placement(visible = true, transformation(origin = {-20, -60}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Prismatic constraint annotation(Placement(visible = true, transformation(origin = {-90, 60}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Revolute constraint1 annotation(Placement(visible = true, transformation(origin = {-50, 60}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Spherical constraint2 annotation(Placement(visible = true, transformation(origin = {-10, 60}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.RevolutePlanarLoopConstraint revolute annotation(Placement(visible = true, transformation(origin = {30, 60}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Spherical spherical1 annotation(Placement(visible = true, transformation(origin = {70, 60}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  annotation(Diagram(coordinateSystem(extent = {{-110, -80}, {90, 80}}, preserveAspectRatio = true, initialScale = 0.1, grid = {5, 5})), Icon(coordinateSystem(extent = {{-100, -100}, {100, 100}}, preserveAspectRatio = true, initialScale = 0.1, grid = {10, 10})));
end IconConventionsTest;
```
In System Modeler before:
image

In System Modeler after:
image

**Comment by tobolar** [comment]
@maltelenz Many thanks. It seems SystemModeler uses its own text size in icons. The changes are not so obvious then. But no problem, the other changes appear fine.

**Comment by maltelenz** [comment]
> @maltelenz Many thanks. It seems SystemModeler uses its own text size in icons. The changes are not so obvious then. But no problem, the other changes appear fine.

Yes, we have such a hack for text containing macros if I remember correctly, no doubt because of historic reasons where text sizes in models varied wildly. Pull requests such as these are working towards fixing this problem, so thank you for that!

**Comment by tobolar** [comment]
Credit goes to @beutlich for pointing this out.

**Review by beutlich — APPROVED** [review]
Here's how it looks in SimulationX.

grafik

**Pull request merged**
