### PR TITLE
Update matio library to 1.5.23

### PR DESCRIPTION
**Pull request by beutlich**

### CODE REVIEW

**Review by HansOlsson — APPROVED** [review]
Seems ok (well it compiles and test-cases seem to run).

**Review by HansOlsson — COMMENTED** [review]
Seems some issue

**Review by HansOlsson — APPROVED** [review]
seems ok. The issue is unrelated, will open PR
Added: #3983

**Review by sjoelund — APPROVED** [review]

**Comment by beutlich** [comment]
Superseded by #4222.

**Pull request merged**
