### PR TITLE
Implement ImpulseSources

### PR DESCRIPTION
**Pull request by AHaumer**
These sources are used as lightning in #3819 and should be merged before.
I consider these sources of broader interest and implemented electrical sources as well as an exmaple in Modelica.Test.

### CODE REVIEW

**Comment by christiankral** [comment]
Hmm... So this PR now replaces #3821 after some improvements of the curve.

**Comment by christiankral** [comment]
I wonder if `Impulse` (e.g., in `Modelica.Blocks.Sources.Impulse`) is clear and unique enough to all users of all MSL domains. I like the term as it is very short. Yet it may be more descriptive if we use `LightningImpulse` instead, as also the parameter `m` strictly follows a lightning current curve [Heidler2009]. 

@dietmarw and @AHaumer please comment.

For the sake of consistency, a possible name change shall be applied to current and voltage sources.

**Comment by AHaumer** [comment]
> 
> 
> I wonder if `Impulse` (e.g., in `Modelica.Blocks.Sources.Impulse`) is clear and unique enough to all users of all MSL domains. I like the term as it is very short. Yet it may be more descriptive if we use `LightningImpulse` instead, as also the parameter `m` strictly follows a lightning current curve [Heidler2009].
> 
Lightning might be misleading, because lightning is mostly used for current, but these trajectories are also used for impulse voltages (surge voltages).

**Comment by HansOlsson** [comment]
To me an impulse is a Dirac-impulse, and since it is infinite it cannot be represented in current Modelica.
(Some projects have worked on it.)

The simplest approximation of that is simply a very short rectangle with unit-area. Any other shape would indicate that the shape of the impulse matters and then you have so many other approximations that matter as much (inductances in resistors etc) that it becomes complicated.

Whether the approximate variant shall be added isn't clear to me.

**Comment by henrikt-ma** [comment]
> I wonder if `Impulse` (e.g., in `Modelica.Blocks.Sources.Impulse`) is clear and unique enough to all users of all MSL domains. I like the term as it is very short. Yet it may be more descriptive if we use `LightningImpulse` instead, as also the parameter `m` strictly follows a lightning current curve [Heidler2009].
> 
> @dietmarw and @AHaumer please comment.
> 
> For the sake of consistency, a possible name change shall be applied to current and voltage sources.

I also see problems with the name `Impulse`, as I think there could be a widespread expectation that this would actually be some sort of exact model of a Dirac delta distribution, similar to how the `Modelica.Blocks.Continuous.Der` models exact differentiation.  (I can see, though, that `Modelica.Blocks.Continuous.Derivative` also has a name that doesn't give any hint of giving an approximation.)

**Comment by dietmarw** [comment]
I think it would probably be easier and less controversial to add `Impulse` under the name `LightningImpulse` inside `Electrical.Analog.Sources` as the term "impulse" in the general application has different definitions as the discussion has shown above.

**Comment by AHaumer** [comment]
I understand that "Impulse" reminds on "Dirac". So another term woulb be "Surge", "SurgeVoltage", "SurgeCurrent".

**Review by christiankral — APPROVED** [review]
Looks good.

**Comment by christiankral** [comment]
Shall the type also be renamed, for the sake of consistency?

- `ImpulseApproximation.Heidler` => `LightningImpulseApproximation.Heidler`
- `ImpulseApproximation.DoubleExp` => `LightningImpulseApproximation.DoubleExp`

**Comment by dietmarw** [comment]
I don't think the general `Modelica.Blocks.Sources` is the right place for the very domain specific `LightningImpulse`. Hence my suggestion to place it into `Electrical.Analog.Sources` instead. Try to avoid mixing domains unless this block really has a more genral usage. But for now it looks like the usage is pretty much home in the electrical domain only.

**Comment by AHaumer** [comment]
> 
> 
> I don't think the general `Modelica.Blocks.Sources` is the right place for the very domain specific `LightningImpulse`. Hence my suggestion to place it into `Electrical.Analog.Sources` instead. Try to avoid mixing domains unless this block really has a more general usage. But for now it looks like the usage is pretty much home in the electrical domain only.

Well its a signal-oriented block, `Analog.Sources` is not the right place. It could be of more general usage - maybe force impulses.
@dietmarw suggest where to place the block, and I'll take that.

**Comment by AHaumer** [comment]
BTW, only mathematicians associate "impulse" with "dirac", mechanical engineers rather with "integral of force";
[https://en.wikipedia.org/wiki/Impulse_(physics)]

**Comment by AHaumer** [comment]
> 
> 
> I know and that's why I originally suggested to simply put it into `Sources` since nobody says that the sources here can not be of type signal. But if you want to be more consistent of course you should add `Blocks` and possibly even `Blocks.Sources` though I really don't think the latter is necessary.

Ok I did so but I have to perform some more testing.

**Comment by AHaumer** [comment]
For me it's fine. @dietmarw do you agree?
If yes, can we merge and then you would rebase #3819? If rebasing fails, I can reconstruct the PR.

**Comment by dietmarw** [comment]
I needed to clean up this PR since it contained all kinds of dummy changes to other sublibraries which are not related and should not be touched. Please take more care of what you commit in the future by looking at the changes before you stage them. See 33e19e7 to get an idea of how many file changes had to be reverted. I will now continue and review the relevant changes in more detail.

**Review by dietmarw — APPROVED** [review]
Looks good now. It needs to get squash-merged to avoid a strange change history of files which should not have been touched by this PR.

**Comment by AHaumer** [comment]
Thanks a lot @dietmarw for your help and cleaning up!

**Pull request merged**
