### PR TITLE
Delete obsolete Ground visualization from MultiBody examples

### LINKED ISSUE #2601: Examples using obsolete ground visualization
Several examples of this:

Checking model Modelica.Mechanics.MultiBody.Examples.Elementary.RollingWheel:
Warning: Component type specifier Ground specified an obsolete type: Obsolete model - use ground visualization feature in Modelica.Mechanics.MultiBody.World, or use model Modelica.Mechanics.MultiBody.Visualizers.Rectangle instead.

Checking model Modelica.Mechanics.MultiBody.Examples.Elementary.RollingWheelSetDriving:
Warning: Component type specifier Ground specified an obsolete type: Obsolete model - use ground visualization feature in Modelica.Mechanics.MultiBody.World, or use model Modelica.Mechanics.MultiBody.Visualizers.Rectangle instead.

Checking model Modelica.Mechanics.MultiBody.Examples.Elementary.RollingWheelSetPulling:
Warning: Component type specifier Ground specified an obsolete type: Obsolete model - use ground visualization feature in Modelica.Mechanics.MultiBody.World, or use model Modelica.Mechanics.MultiBody.Visualizers.Rectangle instead.

Checking model Modelica.Mechanics.MultiBody.Examples.Elementary.Surfaces:
Warning: Component type specifier Ground specified an obsolete type: Obsolete model - use ground visualization feature in Modelica.Mechanics.MultiBody.World, or use model Modelica.Mechanics.MultiBody.Visualizers.Rectangle instead.

### PR DESCRIPTION
**Pull request by tobolar**
Closes #2601

### CODE REVIEW

**Comment by beutlich** [comment]
Should World.groundColor be set to {0,255,0} = Ground.groundColor?

**Comment by tobolar** [comment]
This would be correct regarding Ground model settings in the original examples.
But to be honest, it seems to me like driving on a meadow, which is strange. A possibility is to set color={215,215,215} similar to Mechanics.MultiBody.Examples.Elementary.Surfaces, but it is rendered poorly in the default top view of Dymola.
So {130,200,130} is some kind of tradeoff.

**Comment by beutlich** [comment]
@HansOlsson OK for you?

**Comment by beutlich** [comment]
Either https://github.com/pulls/review-requested or by filtering: https://github.com/modelica/ModelicaStandardLibrary/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+milestone%3AMSL3.2.3+review-requested%3AHansOlsson

**Pull request merged**
