### PR TITLE
Fix syntax errors in ModelicaReference documentation snippets

### PR DESCRIPTION
**Pull request by maltelenz**

### CODE REVIEW

**Review by henrikt-ma — APPROVED** [review]
Looks good to me.

**Review by beutlich — APPROVED** [review]
LGTM

**Comment by tobolar** [comment]
There is also 
```
y = <strong>if abs</strong>(x) &lt; Modelica.Constants.eps...
```
in `ModelicaReference.Classes.'function'` to be fixed similarly.

**Review by tobolar — CHANGES_REQUESTED** [review]
There is also 
```
y = <strong>if abs</strong>(x) &lt; Modelica.Constants.eps...
```
in `ModelicaReference.Classes.'function'` to be fixed similarly.

**Comment by tobolar** [comment]
Btw. there are sometimes used spaces beneath the equal sign: ` = ` and ` := `. But sometimes not.

**Comment by maltelenz** [comment]
> There is also
> 
> ```
> y = <strong>if abs</strong>(x) &lt; Modelica.Constants.eps...
> ```
> 
> in `ModelicaReference.Classes.'function'` to be fixed similarly.

Fixed.



> Btw. there are sometimes used spaces beneath the equal sign: `=` and `:=`. But sometimes not. (Which this PR is not about)

Fixed these anyway.

**Comment by maltelenz** [comment]
@casella Since we are past the cutoff date for 4.1.0, I assume this should technically go in after the branching?

I'll leave this as is for @casella to decide when to push the merge button.

**Comment by beutlich** [comment]
> @casella Since we are past the cutoff date for 4.1.0, I assume this should technically go in after the branching?
> 
> I'll leave this as is for @casella to decide when to push the merge button.

Well, this is can be seen as a doc-fix and not as a new feature.

Can you resolve the merge conflict as well? Thanks.

**Comment by maltelenz** [comment]
> Well, this is can be seen as a doc-fix and not as a new feature.

The [wiki](https://github.com/modelica/ModelicaStandardLibrary/wiki/MSL-v4.1.0-release) page says: "no new PRs can be opened"

But if I was the project leader I would accept stuff like this regardless :)

> Can you resolve the merge conflict as well? Thanks.

Done.

**Review by beutlich — APPROVED** [review]

**Review by MartinOtter — APPROVED** [review]

**Comment by Harisankar-Allimangalath** [comment]
@casella  can you please review the changes .Thankyou

**Pull request merged**
