### PR TITLE
Check y - not internal state

### LINKED ISSUE #4296: MSL 4.1.0 Regressions - Blocks
The following models fail in result comparison.
Status: 7ac79067 (2024-01-30)

- [x] Modelica.Blocks.Examples.Noise.ActuatorWithNoise
      - Reason: Due to #3727. Invalid reference result.
      - Updated reference files? @GallLeo Yes, should update reference result
      
- [x] Modelica.Blocks.Examples.Noise.DrydenContinuousTurbulence
      - Reason: Due to #3727 (in text of issue). Invalid reference result.
      - Updated reference files? @GallLeo Yes, should update reference result
      
- [x] Modelica.Blocks.Examples.Noise.NormalNoiseProperties
      - Reason: Due to #4151 remove comparison
      - Updated reference files? Reduced comparison signals in linked PR; #4297. @GallLeo please update reference result
      - @HansOlsson ~~please back-port #4151 to maint/4.1.x and link the PR here~~; Back-port #4297 which is done in #4416
      
- [x] Modelica.Blocks.Examples.Noise.UniformNoiseProperties
      - Reason: Due to #4151 remove comparison
      - Updated reference files? Reduced comparison signals in linked PR; #4297. @GallLeo please update reference result
      - @HansOlsson ~~please back-port #4151 to maint/4.1.x and link the PR here~~; Back-port #4297 which is done in #4416

### PR DESCRIPTION
**Pull request by HansOlsson**
Closes #4296

### CODE REVIEW

**Review by beutlich — COMMENTED** [review]
What about the variance block? Should it be in a similar fashion?

**Comment by beutlich** [comment]
> > What about the variance block? Should it be in a similar fashion?
> 
> Ideally yes. But it can wait as that block wasn't updated for this release.

Hm, so it seems to me that we have some "immature" dev state where Mean was refactored and Variance not yet. That does not sound too promising. You still can prove me wrong here.

**Comment by HansOlsson** [comment]
> Hm, so it seems to me that we have some "immature" dev state where Mean was refactored and Variance not yet. That does not sound too promising. You still can prove me wrong here.

I see two possible answers:
- It's still a step in the right direction, and the Variance-model would require more time to get it right (the formulas are somewhat messy - just computing the integral of u^2 is likely to lead to round-off errors).
- The Variance model actually benefits from this rewriting.

**Review by hubertus65 — APPROVED** [review]

**Review by casella — APPROVED** [review]
LGTM

**Pull request merged**
