### PR TITLE
Rename specific gas constant R to R_s

### LINKED ISSUE #2438: Same name R used for universal and specific gas constant
The same name for the universal and specific gas constant can lead to errors, as we had in #2377. A name change of either the universal gas constant from R to R_m, or from the specific gas constant R to R_s. Both changes would touch a lot of points and could actually be disruptive for users even with good conversion scripts. Good unit checking would always detect it, good documentation could reduce errors. Therefore I'll pose this issue as discussion.

### PR DESCRIPTION
**Pull request by beutlich**
resolves #2438

### CODE REVIEW

**Comment by thorade** [comment]
This looks good, as far as I can see. How did you do it? Is there a way to test that `R` has unit J/(K.mol) and `R_s` has unit J/(K.kg) so that `R_s = R/MM`?

**Comment by beutlich** [comment]
> How did you do it?

I do all renaming tasks in Notepad++ using search and replace. This time it took me more than 4 hours.

**Comment by beutlich** [comment]
Note, that I did not touch any specific gas constant R_gas or RH20. I only touched R (in literally all occurrences of Media) if it was the specific gas constant.

**Comment by beutlich** [comment]
Thanks for reporting.

> Use of undeclared variable Constants.R_s

Yes, I also noticed that Constants is a problematic name, since it might refer to Modelica.Constants or  Modelica.Media.Air.ReferenceAir.Air_Utilities.Basic.Constants within the same context.

**Comment by beutlich** [comment]
> I believe that Modelica.Media.Air.ReferenceAir.Air_Base.BaseProperties

It looks like it is a real bug in current MSL already, since BaseProperties.R is the specific gas constant.

https://github.com/modelica/ModelicaStandardLibrary/blob/f7a45808a8ee87d759b9ac03f5cf192e74584897/Modelica/Media/Air/ReferenceAir.mo#L161

It shall be corrected to

```mo
        R = ReferenceAir.Air_Utilities.Basic.Constants.R;
```

@hubertus65 @thorade Can you please confirm?

**Comment by HansOlsson** [comment]
> I believe that Modelica.Media.Air.ReferenceAir.Air_Base.BaseProperties
> 
> It looks like it is a real bug in current MSL already, since BaseProperties.R is the specific gas constant.
> 
>   
>     
>       ModelicaStandardLibrary/Modelica/Media/Air/ReferenceAir.mo
>     
>     
>          Line 161
>       in
>       f7a4580
>     
>     
>     
>     
> 
>         
>           
>            R = Constants.R; 
>         
>     
>   
> 
> 
> It shall be corrected to
>         R = ReferenceAir.Air_Utilities.Basic.Constants.R;
> @hubertus65 @thorade Can you please confirm?

And to be clear: in this PR it should become `R_s = ReferenceAir.Air_Utilities.Basic.Constants.R_s;`, right? (We could drop the `ReferenceAir.` part as well, but it should be consistent with MM; so likely best to keep in both places.)

**Comment by beutlich** [comment]
> And to be clear: in this PR it should become `R_s = ReferenceAir.Air_Utilities.Basic.Constants.R_s;`, right?

Sure. `R = ReferenceAir.Air_Utilities.Basic.Constants.R;` is meant for current MSL v3.2.3.

**Comment by beutlich** [comment]
> We could drop the `ReferenceAir.`

Yes, good idea. Will do in both places.

**Pull request merged**
