### PR TITLE
Utilize ellipses' closure

### LINKED ISSUE #2474: Spherical, etc. render poorly on non-white backgrounds
Basically this is a copy of #2031 but this time for `Modelica.Mechanics.MultiBody` components, as e.g. for
- Modelica.Mechanics.MultiBody.Joints.Spherical,
- Modelica.Mechanics.MultiBody.Joints.SphericalSpherical,
- Modelica.Mechanics.MultiBody.Joints.UniversalSpherical or
- components from Modelica.Mechanics.MultiBody.Joints.Assemblies.

### PR DESCRIPTION
**Pull request by tobolar**
Closure introduced in Modelica Specification 3.4
closes #2474

### CODE REVIEW

**Review by maltelenz — CHANGES_REQUESTED** [review]
1. The new icons have flipped some of the ellipses, probably unintentionally. The extent seems to be flipped, but the specification does not say this should mean an `Ellipse` is flipped. Such a feature is only given for `Bitmap` and components.
Rendering of 4.0.0 in SystemModeler (so not including this pull request):
image
Rendering of this pull request in SystemModeler:
image
I used this model for the render:
```
model MultibodyEllipseClosures
  Modelica.Mechanics.MultiBody.Joints.Spherical spherical1 annotation(Placement(visible = true, transformation(origin = {-110, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.SphericalSpherical sphericalSpherical1 annotation(Placement(visible = true, transformation(origin = {-80, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.UniversalSpherical universalSpherical1 annotation(Placement(visible = true, transformation(origin = {-50, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.LineForceWithMass lineForceWithMass1 annotation(Placement(visible = true, transformation(origin = {-20, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.LineForceWithTwoMasses lineForceWithTwoMasses1 annotation(Placement(visible = true, transformation(origin = {15, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointSSP jointSSP1 annotation(Placement(visible = true, transformation(origin = {-100, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointSSR jointSSR1 annotation(Placement(visible = true, transformation(origin = {-50, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUPS jointUPS1 annotation(Placement(visible = true, transformation(origin = {0, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUSP jointUSP1 annotation(Placement(visible = true, transformation(origin = {50, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUSR jointUSR1 annotation(Placement(visible = true, transformation(origin = {100, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Spherical spherical2 annotation(Placement(visible = true, transformation(origin = {110, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Universal universal1 annotation(Placement(visible = true, transformation(origin = {50, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Universal constraint annotation(Placement(visible = true, transformation(origin = {80, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  annotation(Diagram(coordinateSystem(extent = {{-130, -15}, {130, 70}}, preserveAspectRatio = true, initialScale = 0.1, grid = {5, 5})), Icon(coordinateSystem(extent = {{-100, -100}, {100, 100}}, preserveAspectRatio = true, initialScale = 0.1, grid = {10, 10}), graphics = {Rectangle(visible = true, lineColor = {0, 114, 195}, fillColor = {255, 255, 255}, extent = {{-100, -100}, {100, 100}}, radius = 25), Text(visible = true, textColor = {64, 64, 64}, extent = {{-150, 110}, {150, 150}}, textString = "%name")}));
end MultibodyEllipseClosures;
```

2. Some of these classes have similar ellipses on the Diagram layer. Maybe they could be improved at the same time? An example is `Modelica.Mechanics.MultiBody.Forces.LineForceWithMass`.

**Comment by tobolar** [comment]
@maltelenz 
1. You are right, it is flipped -  intentionally. In Dymola, the flipping leads to desired effect, but it really doesn't seem to be the intention of the Modelica Specification (Section 18.6.5.4 Ellipse):
   > The extent attribute specifies the bounding box of the ellipse.

   I will fix the angles (must have negative values) for propper result.
2. I would separately check whether the diagram drawings are relevant at all since there was discussion on it in #3056

**Comment by maltelenz** [comment]
>     2\. I would separately check whether the diagram drawings are relevant at all since there was discussion on it in #3056

That makes sense, let's not do anything about them in this pull request.

**Comment by tobolar** [comment]
@maltelenz Please check my fix on ellipses flipping. Many thanks!

**Review by maltelenz — CHANGES_REQUESTED** [review]
The rendering in SystemModeler looks good now:

image

I have not reviewed the diff very thoroughly (annotation changes are hard to interpret manually).

There does seem to be a change in `Modelica/Mechanics/Rotational/Interfaces/PartialFriction.mo` that seems unrelated to this pull request? Maybe it got included by mistake?

**Comment by tobolar** [comment]
The icons look like as expected.

PartialFriction.mo: My mistake - it is a part of PR #3633 - so that PR shall be merged first.

**Comment by beutlich** [comment]
I removed the two irrelevant commits and rebased.

**Review by maltelenz — APPROVED** [review]
Looks good now, thanks!

**Comment by tobolar** [comment]
It would be nice if someone could check the icons in one more tool as well. SystemModeler and Dymola are done already.

**Comment by beutlich** [comment]
Can do for Simulationx with @maltelenz' demo model.

**Review by beutlich — APPROVED** [review]
Here are the screen shots from SimulationX using @maltelenz' demo model on a non-standard non-white background.

Old:
grafik

New:
grafik

**Review by beutlich — DISMISSED** [review]
There is some issue with the diagonal line in the universal joints:

grafik

**Comment by beutlich** [comment]
One more comment: Why is the universal grey in the stand-alone joint/constraint, but black in the asseembly joints? Seems arbitrary to me.

**Comment by tobolar** [comment]
> ... issue with the diagonal line in the universal joints.

@beutlich Good catch!

This seems to be an issue of priorising between angles and stretching.
In Dymola, IMO the ellipse's angles are realized prior to stretching - so setting an angle and stretching the ellipse results in right different angle. In WolframModeller this seems to be vice versa.

So what is the desired behaviour?

**Comment by tobolar** [comment]
> Why is the universal grey in the stand-alone joint/constraint, but black in the asseembly joints?

I will check it again.

**Comment by maltelenz** [comment]
> In WolframModeller this seems to be vice versa.

Just to clarify, in SystemModeler the diagonal line looks fine, see [earlier screenshot](https://github.com/modelica/ModelicaStandardLibrary/pull/3634#pullrequestreview-499400511). SimulationX seems to be the odd one out here?

**Comment by tobolar** [comment]
@maltelenz 
> in SystemModeler the diagonal line looks fine

Sorry, I will change it directly in my comment.

**Comment by beutlich** [comment]
> SimulationX seems to be the odd one out here?

Could be that there is some issue with angles in SimulationX.

Zooming into jointUPS icon:

Dymola:
grafik

SimulationX:
grafik

WSM:
grafik

**Comment by beutlich** [comment]
@tobolar: Please note that in JointUSP the vertical black line of the universal looks different from JointUPS. I guess it is not by design.

**Comment by tobolar** [comment]
> Why is the universal grey in the stand-alone joint/constraint, but black in the asseembly joints?

and 
> Please note that in JointUSP the vertical black line of the universal looks different from JointUPS.

@beutlich Please check my latest commits. If not resolved please mark the code lines concerned or explain in more detail.

**Comment by beutlich** [comment]
```
@tobolar pushed 9 commits.

825bacf862bce3b74a9c3673629cd73250843bfc  Documentation: Describe the effect of w_small in friction elements
be9a0b159a39ef8401406617fd4d74d0351bfee0  Documentation: References according to conventions
5531a9764c250b47df5022e0f98bea191a8750f8  Icon: Utilize ellipses' closure
f814fa3c697d43a2bd51cbf918de0da76f5e0a64  Icon: Utilize ellipses' closure in universal joints
eccc1186b8c4ecfccde87fe533418365bae11810  Icon: Fix false flipping of ellipses
439e53e470b2728498063d90b0bd426ba2c89a84  Icon: place component name according to design rule
c8bf191d8dc2dcf2398dd2a91e70240cb2d19b55  Use package's main color
d52f495f7c6611909a0b34f3ffb237b9061d2d09  Icon: Longer line of universal joint
4497b96a79b5943775eb91d39f65eded915c30e9  Merge branch 'issue2474_ellipsesClosure' of https://github.com/tobolar/ModelicaStandardLibrary into issue2474_ellipsesClosure
```

@tobolar Your merge again introduced the undesired documentation commits and reverted my commit to use Text.textcolor.

**Comment by tobolar** [comment]
@beutlich I'm very sorry. Any chance to revert this?

**Comment by beutlich** [comment]
> @beutlich Please check my latest commits.

@tobolar Please see my screen shot again.

grafik

**Comment by tobolar** [comment]
@beutlich Ok, seems reasonable to unify it.

**Comment by maltelenz** [comment]
Updated screenshot from SystemModeler after latest changes, still good:
image

**Comment by tobolar** [comment]
Dymola 2021x:
MultibodyEllipseClosures

@maltelenz I'm still slower then you ... :-)

**Comment by tobolar** [comment]
Dymola 2021x:
MultibodyEllipseClosures

**Comment by maltelenz** [comment]
And again with the most recent changes, added the newly modified components (I think):
```
model MultibodyEllipseClosures
  Modelica.Mechanics.MultiBody.Joints.Spherical spherical1 annotation(Placement(visible = true, transformation(origin = {-110, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.SphericalSpherical sphericalSpherical1 annotation(Placement(visible = true, transformation(origin = {-80, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.UniversalSpherical universalSpherical1 annotation(Placement(visible = true, transformation(origin = {-50, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.LineForceWithMass lineForceWithMass1 annotation(Placement(visible = true, transformation(origin = {-20, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.LineForceWithTwoMasses lineForceWithTwoMasses1 annotation(Placement(visible = true, transformation(origin = {15, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointSSP jointSSP1 annotation(Placement(visible = true, transformation(origin = {-100, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointSSR jointSSR1 annotation(Placement(visible = true, transformation(origin = {-50, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUPS jointUPS1 annotation(Placement(visible = true, transformation(origin = {0, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUSP jointUSP1 annotation(Placement(visible = true, transformation(origin = {50, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUSR jointUSR1 annotation(Placement(visible = true, transformation(origin = {100, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Spherical spherical2 annotation(Placement(visible = true, transformation(origin = {110, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Universal universal1 annotation(Placement(visible = true, transformation(origin = {50, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Universal constraint annotation(Placement(visible = true, transformation(origin = {80, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.RevolutePlanarLoopConstraint revolute annotation(Placement(visible = true, transformation(origin = {-110, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Prismatic constraint1 annotation(Placement(visible = true, transformation(origin = {-70, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Revolute constraint2 annotation(Placement(visible = true, transformation(origin = {-30, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Spherical constraint3 annotation(Placement(visible = true, transformation(origin = {10, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Universal constraint4 annotation(Placement(visible = true, transformation(origin = {50, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  annotation(Diagram(coordinateSystem(extent = {{-130, -55}, {130, 70}}, preserveAspectRatio = true, initialScale = 0.1, grid = {5, 5})), Icon(coordinateSystem(extent = {{-100, -100}, {100, 100}}, preserveAspectRatio = true, initialScale = 0.1, grid = {10, 10}), graphics = {Rectangle(visible = true, lineColor = {0, 114, 195}, fillColor = {255, 255, 255}, extent = {{-100, -100}, {100, 100}}, radius = 25), Text(visible = true, textColor = {64, 64, 64}, extent = {{-150, 110}, {150, 150}}, textString = "%name")}));
end MultibodyEllipseClosures;
```
System Modeler:
image

**Comment by tobolar** [comment]
@maltelenz Thanks. Looks still good for me.

**Comment by tobolar** [comment]
@beutlich Ok to you to merge this PR?

**Review by beutlich — COMMENTED** [review]
> 
> 
> @beutlich Ok to you to merge this PR?

Sorry, it took some more time to test it on dark background. Here's what I observe in dark mode of Dymola 2021x.

* The white ellipse covering the darker ellipse has larger angle extension which makes it only good looking on white background.
* There are some isues with the icon conventions regarding the name width and height, which still make it not that appealing in the overall model provided by @maltelenz. Some of the icons have a name height of only 25 units. For Modelica.Mechanics.MultiBody.Forces.LineForceWithTwoMasses, I believe we need to allow more than the 300 units of name width. Modelica.Mechanics.MultiBody.Joints.RevolutePlanarLoopConstraint and Modelica.Mechanics.MultiBody.Joints.Constraints.Revolute have primary parameter and name field swapped for no particular reason.

grafik

Here's a screenshot from SimulationX. Would be good to get some feedback from @gkurzbach's colleagues on the different ellipse display (see https://github.com/modelica/ModelicaStandardLibrary/pull/3634#issuecomment-703489473). I believe this should be either confirmed as SimulationX bug or clarified in the Modelica Language Specification first.

grafik

Would also be good to get some feedback from the OpenModelica product owner (@casella) and MapleSim dev team (@svorkoetter ).

**Comment by eshmoylova** [comment]
I noticed that in the test model in [the comment above](https://github.com/modelica/ModelicaStandardLibrary/pull/3634#issuecomment-725356306) there were 3 models missing corresponding to 3 other files that are part of the commit.
```
Modelica.Mechanics.MultiBody.Joints.Assemblies.JointRRR
Modelica.Mechanics.MultiBody.Joints.Assemblies.JointRRP
Modelica.Mechanics.MultiBody.Joints.GearConstraint
```

**Comment by maltelenz** [comment]
Here is an updated model with the above three mentioned models included:
```
model MultibodyEllipseClosures3
  Modelica.Mechanics.MultiBody.Joints.Spherical spherical1 annotation(Placement(visible = true, transformation(origin = {-110, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.SphericalSpherical sphericalSpherical1 annotation(Placement(visible = true, transformation(origin = {-80, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.UniversalSpherical universalSpherical1 annotation(Placement(visible = true, transformation(origin = {-50, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.LineForceWithMass lineForceWithMass1 annotation(Placement(visible = true, transformation(origin = {-20, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.LineForceWithTwoMasses lineForceWithTwoMasses1 annotation(Placement(visible = true, transformation(origin = {15, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointSSP jointSSP1 annotation(Placement(visible = true, transformation(origin = {-100, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointSSR jointSSR1 annotation(Placement(visible = true, transformation(origin = {-50, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUPS jointUPS1 annotation(Placement(visible = true, transformation(origin = {0, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUSP jointUSP1 annotation(Placement(visible = true, transformation(origin = {50, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointUSR jointUSR1 annotation(Placement(visible = true, transformation(origin = {100, 10}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Spherical spherical2 annotation(Placement(visible = true, transformation(origin = {110, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Universal universal1 annotation(Placement(visible = true, transformation(origin = {50, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Universal constraint annotation(Placement(visible = true, transformation(origin = {80, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.RevolutePlanarLoopConstraint revolute annotation(Placement(visible = true, transformation(origin = {-110, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Prismatic constraint1 annotation(Placement(visible = true, transformation(origin = {-70, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Revolute constraint2 annotation(Placement(visible = true, transformation(origin = {-30, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Spherical constraint3 annotation(Placement(visible = true, transformation(origin = {10, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Constraints.Universal constraint4 annotation(Placement(visible = true, transformation(origin = {50, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointRRR jointRRR1 annotation(Placement(visible = true, transformation(origin = {-50, -70}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.Assemblies.JointRRP jointRRP1 annotation(Placement(visible = true, transformation(origin = {-100, -70}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Joints.GearConstraint gearConstraint1 annotation(Placement(visible = true, transformation(origin = {90, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  annotation(Diagram(coordinateSystem(extent = {{-130, -95}, {130, 70}}, preserveAspectRatio = true, initialScale = 0.1, grid = {5, 5})), Icon(coordinateSystem(extent = {{-100, -100}, {100, 100}}, preserveAspectRatio = true, initialScale = 0.1, grid = {10, 10}), graphics = {Rectangle(visible = true, lineColor = {0, 114, 195}, fillColor = {255, 255, 255}, extent = {{-100, -100}, {100, 100}}, radius = 25), Text(visible = true, textColor = {64, 64, 64}, extent = {{-150, 110}, {150, 150}}, textString = "%name")}));
end MultibodyEllipseClosures3;
```
In System Modeler:
image

**Review by eshmoylova — APPROVED** [review]
Reviewed on behalf of @svorkoetter

**Comment by tobolar** [comment]
@beutlich 
> - The white ellipse covering the darker ellipse has larger angle extension which makes it only good looking on white background.

This was done on purpose to be sure the smaller white ellipses fully cover radial closures of (biger) dark ellipses. An option could be to set the same opening and closing angles for all ellipses AND to use line of double thickness of white ellipses. Not sure if this works for all tools.

This is how Dymola renders spherical joint's icon when all angles are the same (single line thickness):
grafik

&nbsp;
> - There are some isues with the icon conventions regarding the name width and height, ...

This is not what this PR is about. Shall be solved separately.

**Comment by maltelenz** [comment]
> This was done on purpose to be sure the smaller white ellipses fully cover radial closures of (biger) dark ellipses. An option could be to set the same opening and closing angles for all ellipses AND to use line of double thickness of white ellipses. Not sure if this works for all tools.

It makes a white line show up between the line added as a fake border, and the black outer ellipse, see on the upper part of this screenshot:
image

If we also increase the extent of the inner fake border by 0.25 in each direction it fixes this and looks OK in System Modeler.

An additional question is why this inner "fake border" has `lineColor = {128, 128, 128}`? If it is supposed to match the border of the black ellipse, it should be black?

> 
> This is how Dymola renders spherical joint's icon when all angles are the same (single line thickness):

System Modeler is the same.

**Comment by tobolar** [comment]
> An additional question is why this inner "fake border" has lineColor = {128, 128, 128}? If it is supposed to match the border of the black ellipse, it should be black?

I think this is because of the sphere fill pattern which changes the color of the inner ellipse. 

The requirement to nicely render on a gray background is challenging. In fact, the "clean" solution is to define joint's outer shell by means of a polygon, i.e. without using the inner white ellipse (providing we render a symbol of the sperical joint, not the real cut through it). This is how Dymola renders it for some 30 polygon's points:

grafik

**Comment by maltelenz** [comment]
> I think this is because of the sphere fill pattern which changes the color of the inner ellipse.

But it doesn't match the inner part of the ellipse filling in all tools, and maybe not even a majority of tools, see https://github.com/modelica/ModelicaStandardLibrary/pull/3634#issuecomment-703665882 for examples of how the sphere filling is interpreted in various tools.
The rules for how the spherical fill pattern should be painted are not clear enough in the specification to say either is wrong, so I guess that should be taken into account when drawing icons.

But I don't want to drag this pull request on even longer, so pretend I didn't say anything...

**Comment by tobolar** [comment]
My last commit using ellipses with solid fill pattern as the sphere pattern makes actually no sense. I don't suppose any more changes on it, so this PR can be merged.

**Comment by beutlich** [comment]
> > * There are some isues with the icon conventions regarding the name width and height, ...
> 
> This is not what this PR is about. Shall be solved separately.

@tobolar Do you think you could create such a PR. Thank you!

**Comment by tobolar** [comment]
> Do you think you could create such a PR.

@beutlich Will do.

**Comment by beutlich** [comment]
Why closing w/o merging? 😕

**Comment by tobolar** [comment]
@beutlich By mistake!!! Sorry.

**Pull request merged**
