### PR TITLE
Add problem matchers for GitHub Actions (CI)

### PR DESCRIPTION
**Pull request by beutlich**

### CODE REVIEW

**Review by dietmarw — COMMENTED** [review]
Could you explain a bit more about the background of this change?
Also the unrelated change in ModeliaReference (though trivial) should probably not be part of this PR, right?

**Comment by beutlich** [comment]
> Could you explain a bit more about the background of this change?

Problem Matchers are a way to scan the output of actions for a specified regex pattern and surface that information prominently in the UI. Currently, failing CI tasks are only reported as part of the Actions tab in the PR. With this change, the failures are directly reported on the files. For example, see `https://github.com/conan-io/conan-center-index/pull/10227/files`

image

> Also the unrelated change in ModeliaReference (though trivial) should probably not be part of this PR, right?

OK.

**Comment by beutlich** [comment]
@sjoelund Can you please review! Thanks!

**Comment by beutlich** [comment]
> Also the unrelated change in ModeliaReference (though trivial) should probably not be part of this PR, right?

Done. There now is #3980 for that trivial correction.

**Review by dietmarw — APPROVED** [review]

**Pull request merged**
