### PR TITLE
Silence clang warning -Wtautological-pointer-compare

### LINKED ISSUE #2109: Should external C functions check their external object pointer for non-null?
**Reported by beutlich on 14 Nov 2016 07:03 UTC**
It is neither specified nor clear to me. Should the void pointer of the external object passed to external C functions be checked for non-null. There are three options here:

1. Do not check pointers.

    Advantage: Short and clear code
    Disadvantage: Apllication may crash with null-pointer access violation.

2. Silently accept if the pointer is non-null.

    Advantage: Application no longer crashes with null-pointer access violation.
    Disadvantage: There might be some kind of undefined behavior in case of a null-pointer.

3. Do error handling if pointer is null.

    Advantage: Application no longer crashes with null-pointer access violation and no undefined behavior.
    Disadvantage: Long code and not clear yet, if really necessary.

See also #1436 for a similar issue on character pointer arguments. The question on external object pointers was not yet asked and answered there.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2109

### PR DESCRIPTION
**Pull request by beutlich**
See [this](https://travis-ci.org/tbeu/ModelicaStandardTables/jobs/550118968) CI run compared to the [previous one](https://travis-ci.org/tbeu/ModelicaStandardTables/jobs/549928952).

Close #2109.

### CODE REVIEW

**Comment by HansOlsson** [comment]
Investigating more I don't think that this is the correct solution, and would either just disable the check - or see if it can be weakened in some other way.

The reason is that as far as I understand:
* These attributes/SAL only generate warnings, not hard errors, if used incorrectly. Thus removing the "tautological" check just removes defence in depth, and if someone calls with a null-pointer we have changed the code from doing nothing to crashing.
* These attributes/SAL are optional - so we cannot be sure that users of these will even have warnings enabled.
* Not all compilers support these attributes/SAL.

Note that Visual Studio C++ (2019 at least) has considered this - and I would say that most of these functions are part of the trust boundary:

"If a function appears at a trust boundary, we recommend that you use the _Pre_defensive_ annotation. The "defensive" modifier modifies certain annotations to indicate that, at the point of call, the interface should be checked strictly, but in the implementation body it should assume that incorrect parameters might be passed. In that case, _In_ _Pre_defensive_ is preferred at a trust boundary to indicate that although a caller will get an error if it attempts to pass NULL, the function body will be analyzed as if the parameter might be NULL, and any attempts to de-reference the pointer without first checking it for NULL will be flagged."

**Comment by beutlich** [comment]
OK, I updated the code to only silence the clang warning wihile not changing any nullptr checks. See [here](https://travis-ci.org/tbeu/ModelicaStandardTables/jobs/550668359) for the CI run.

**Comment by HansOlsson** [comment]
Hmm...

Actually it seems that disabling "-Wtautological-pointer-compare" only disables the warnings, but clang (and gcc) still optimizes away the null-pointer tests, which is kind of dangerous.
It is necessary to add "-fno-delete-null-pointer-checks" to get reliable results.

**Comment by beutlich** [comment]
I added `-fno-delete-null-pointer-checks` [here](https://github.com/tbeu/ModelicaStandardTables/commit/f26df2d2823572c44e716888f7f401a7626aa35a) such that this optimization is disabled whenever new binaries are built.

**Pull request merged**
