### PR TITLE
Replaced explicit syntax sections with link to Modelica Grammar

### LINKED ISSUE #2820: Update ModelicaReference to latest Modelica specification 3.4
ModelicaReference is based on MLS 3.2 (not even sure which revision), but should be updated to MLS 3.4.

### PR DESCRIPTION
**Pull request by dietmarw**
Ref #2820

### CODE REVIEW

**Comment by beutlich** [comment]
I believe https://github.com/modelica/ModelicaStandardLibrary/issues/2820#issuecomment-540949683 is not yet resolved. Thus, #2820 should not yet closed.

**Comment by dietmarw** [comment]
That's true. I missed that. @HansOlsson could you add those to this PR. I think as short a description as possible would suffice.

**Comment by beutlich** [comment]
> 
> 
> That's true. I missed that. @HansOlsson could you add those to this PR. I think as short a description as possible would suffice.

@HansOlsson Can you please add the sections on synchronous language elements. Thanks.

**Comment by HansOlsson** [comment]
> 
> 
> > That's true. I missed that. @HansOlsson could you add those to this PR. I think as short a description as possible would suffice.
> 
> @HansOlsson Can you please add the sections on synchronous language elements. Thanks.

I tried to do that in https://github.com/modelica/ModelicaStandardLibrary/pull/3443
Obviously one could add more.

**Pull request merged**
