### PR TITLE
Updates for latest changes to 3.4 grammar

### PR DESCRIPTION
**Pull request by beutlich**
Modified from https://github.com/modelica-tools/ModelicaSyntaxChecker/pull/1 by @svorkoetter . See #2820.

### CODE REVIEW

**Comment by beutlich** [comment]
@maltelenz Please note that the anchor links of the Modelica Grammar do not work in WSM 12. See the screen shot.

grafik

**Comment by maltelenz** [comment]
> @maltelenz Please note that the anchor links of the Modelica Grammar do not work in WSM 12. See the screen shot.
> 

@beutlich Thank you for the bug report! We independently discovered this last week, and it will be fixed in the next SystemModeler release.

**Comment by svorkoetter** [comment]
Anchor links don't work in MapleSim either. It seems to be a side-effect of the third party HTML engine used (perhaps several of us use the same one).

**Comment by beutlich** [comment]
At least they work in the MapleSim generated HTML documentation: [doc.modelica.org](https://doc.modelica.org/ModelicaReference%203.2.3/Resources/helpMapleSim/index.html#ModelicaGrammar)

**Comment by svorkoetter** [comment]
> At least they work in the MapleSim generated HTML documentation: [doc.modelica.org](https://doc.modelica.org/ModelicaReference%203.2.3/Resources/helpMapleSim/index.html#ModelicaGrammar)

Yes, the generate HTML is correct, and the anchors work in all stand-alone web browsers. It just seems that most or all tools' built-in HTML browser engines don't support them.

**Comment by sjoelund** [comment]
Works fine for OMEdit (Qt 5.9-based HTML rendering when using Ubuntu 18.04 LTS) and Dymola 2020 (seems to be linked against my OS version of Qt, so same as OMEdit). Did not work with  Dymola 2018 (Qt 5.5 bundled with it)...

**Pull request merged**
