### PR TITLE
Update matio library to version 1.5.19

### PR DESCRIPTION
**Pull request by beutlich**
This updates ModelicaMatIO to the latest version 1.5.18 of the underlying matio library. The changes in the diff are hardly trackable, thus we probably should revert to use original matio source files one day.

Matio 1.5.8 supports HDF5 1.12.x, which might be relevant for OMC (see #2001 for some previous issue with HDF5 support).

Unfortunately, the new version no longer compiles with gcc 4.6 due an internal compiler error (see https://travis-ci.org/github/tbeu/ModelicaStandardTables/jobs/732885392#L463). This compiler error does not show up with gcc 4.4 or 4.8, thus workarounds are available.

I can provide the new binaries for testing in a separate commit using a dedicated branch.

### CODE REVIEW

**Comment by beutlich** [comment]
> I can provide the new binaries for testing in a separate commit using a dedicated branch.

Binaries for early testing have been rebuilt and are available from my branch [update-binaries-matio-1.5.18](https://github.com/beutlich/ModelicaStandardLibrary/tree/update-binaries-matio-1.5.18).

**Review by HansOlsson — APPROVED** [review]
Looks good to me.

**Comment by beutlich** [comment]
Will soon update to v1.5.19 (to be released tonight) due to one issue with undefined behaviour reported by @jnjaeschke.

**Review by sjoelund — APPROVED** [review]
Seems OK. Also works on gcc-4.6 (I found an unrelated issue with the configure.ac file that I will open a PR for)

**Comment by beutlich** [comment]
Supersedeb by #3785.

**Pull request merged**
