### PR TITLE
Split Electrical.{PolyPhase, PowerConverters, QuasiStatic} into single files

### PR DESCRIPTION
**Pull request by AHaumer**
Since no other PRs are affected, I'd like to grab the chance to split Electrical.{PolyPhase, PowerConverters, QuasiStatic} into single files.

### CODE REVIEW

**Comment by AHaumer** [comment]
@beutlich what's the reason?

**Comment by DrMartinKuhn** [comment]
I am a strong supporter of this change. Having everything in one file can lead to conflicts if there are multiple changes in the library and long-lasting pull requests.

**Comment by christiankral** [comment]
> I am a strong supporter of this change. Having everything in one file can lead to conflicts if there are multiple changes in the library and long-lasting pull requests.

@DrMartinKuhn In order to approve this pull request please click on "Add your review" and "Approve" (possibly add a comment). 

image

The "Add your review" button appears if you click on "Conversations"

image

**Comment by AHaumer** [comment]
Hm I've no idea how to resolve the conflicts. Seems to be the old "all-in-one" files that should be deleted, merging the directorires (with single files). Who could help me, please?

**Comment by beutlich** [comment]
> 
> 
> Hm I've no idea how to resolve the conflicts. Seems to be the old "all-in-one" files that should be deleted, merging the directorires (with single files). Who could help me, please?

Done.

**Comment by AHaumer** [comment]
@beutlich thanks a lot - just to learn: How did you do that?

**Comment by beutlich** [comment]
It worked out that smoothly since I remembered that only the merge of #3016 caused the conflict. Otherwise impossible to resolve using git tools. Thus I rebased, resolved the deletion conflicts from your branch and bulk-renamed the icons in Notepad++ later.

**Pull request merged**
