### PR TITLE
Add badges for regression tests run by LTX

### PR DESCRIPTION
**Pull request by beutlich**
Here's how they appear:

[Modelica v4.1.0-dev regression test](https://www.ltx.de/download/MA/Compare_MSL_v4.1.0/comparison_report_overview.html)
[ModelicaTest v4.1.0-dev regression test](https://www.ltx.de/download/MA/Compare_MSL_v4.1.0/comparison_report_overview.html)

@MatthiasBSchaefer If the regression test website layout changes, the badges gonna break.

### CODE REVIEW

**Review by AHaumer — APPROVED** [review]
ok

**Comment by tobolar** [comment]
How does the Increasing number of badges influence the website loading time?

**Comment by beutlich** [comment]
> How does the Increasing number of badges influence the website loading time?

I believe this is not an issue to take care of.

Did you try reloading https://github.com/beutlich/ModelicaStandardLibrary/blob/add-badges-regression-test-ltx/README.md ?

**Review by tobolar — APPROVED** [review]
Fine for me. 
Optionally, CI could be enhanced to check URL links also for this readme file. (of course not at every PR.)

**Pull request merged**
