### PR TITLE
Add unit="1" to quaternions.

### PR DESCRIPTION
**Pull request by HansOlsson**
Note that Modelica.Mechanics.MultiBody.Frames.Quaternions.der_Orientation already have a corresponding unit. That has two implications:
* It is the correct unit; as it cannot be anything else. (Also clear from the constraint that q*q=1.)
* In many cases we could already deduce the unit for the quaternion based on its derivative.

However, if we didn't compute the derivative in a specific model that deduction wouldn't happen. Additionally it seems a bit counter-intuitive to go that indirect route.

### CODE REVIEW

**Review by henrikt-ma — APPROVED** [review]
Looks excellent to me. I'm approving with the caveat that we are currently not in a position where we can evaluate the implications for unit checking, since our implementation is currently not paying much attention to arrays.

**Review by casella — APPROVED** [review]
LGTM

**Comment by HansOlsson** [comment]
What should I do regarding the CLA-check?

**Comment by casella** [comment]
Looks stuck. No idea why.

**Comment by Esther-Devakirubai** [comment]
@casella Can this be backported to maint/4.1.0? No Milestone either

**Comment by casella** [comment]
> @casella Can this be backported to maint/4.1.0? No Milestone either

Please do.

**Comment by Esther-Devakirubai** [comment]
Backporting this to maintenance branch by #4445

**Pull request merged**
