### PR TITLE
Fix nontrivial typos

### LINKED ISSUE #940: Corrections to typos
**Reported by kdavies4 on 26 Dec 2012 15:50 UTC**
This ticket is to correct many typographical errors in the Modelica Standard Library.  The changes have been applied and listed against MSL 2010-10-25, build 5 (2010-10-25 21:19:49Z) at: https://github.com/kdavies4/Modelica/pull/1/files https://github.com/kdavies4/Modelica/pull/1/files

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/940

### PR DESCRIPTION
**Pull request by beutlich**
Preparation to fix #940.

Credits go to @kdavies4.

### CODE REVIEW

**Comment by beutlich** [comment]
@kristinmajetta Can you please check the changes for Spice3?

I noticed that mos2RenameParametersDev sets the obsolete variables m_drainPerimiter/m_sourcePerimiter. which looks like a real bug, not just a typo fix. It is changed to set m_drainPerimeter/m_sourcePerimeter. Is this fine for you?

**Comment by kristinmajetta** [comment]
> I noticed that mos2RenameParametersDev sets the obsolete variables m_drainPerimiter/m_sourcePerimiter. which looks like a real bug, not just a typo fix.

Yes, that was wrong. Resolved in master by 3ab3035a1ae0c5ff317e10a89018e075218e0eea and maint/3.2.2 by 16f3f22256c0e2180cb2092e0ed385c7147ed59d.

**Comment by kristinmajetta** [comment]
Yes, setting the variables m_drainPerimeter/m_sourcePerimeter is fine for me.

**Comment by beutlich** [comment]
> Yes, setting the variables m_drainPerimeter/m_sourcePerimeter is fine for me.

Yes, and was already dealt with in February 2017.

**Comment by kristinmajetta** [comment]
So? Can we close the ticket?

**Comment by beutlich** [comment]
No. This ticket is on the non-trivial typos (e.g., jucntioncap, united_converging_crossection and lamda) in Spice3, Fluid.Dissipation and Thermal.FluidHeatFlow and schedulded for the next major release. The Spice3 issue on m_drainPerimiter/m_sourcePerimiter was detected (and resolved) en passant.

**Comment by MartinOtter** [comment]
This is a non-backwards compatible change. Was there a decision that the next major MSL version will allow non-backwards compatible changes (and therefore support of the conversion annotations introduced in Modelica 3.4 is needed in the tools)

**Comment by beutlich** [comment]
@HansOlsson I am struggling on conversion scripts. Given a record where a component is removed (between two library releases), how can the record ctor call be converted. Currently, my conversion test model that runs in MSL v3.2.3, but no longer runs in MSL v4.0.0 is:

```mo
model Issue940 "Conversion test for #940"
  parameter Modelica.Electrical.Spice3.Internal.Mosfet.Mosfet r1 = Modelica.Electrical.Spice3.Internal.Mosfet.Mosfet(1, 2, 3, 4,5 ,6 ,7 , 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, true);
  parameter Modelica.Electrical.Spice3.Internal.Mosfet.Mosfet r2 = Modelica.Electrical.Spice3.Internal.Mosfet.Mosfet(1, 2, 3, 4,5 ,6 ,7 , 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, m_drainPerimiter=19, m_sourcePerimiter=20, m_uic=true);
  annotation(experiment(StopTime=1), Documentation(info="<html>
<p>
Conversion test for <a href=\"https://github.com/modelica/ModelicaStandardLibrary/issues/940\">#940</a>.
</p>
</html>"));
end Issue940;
```

**Comment by HansOlsson** [comment]
> @HansOlsson I am struggling on conversion scripts. Given a record where a component is removed (between two library releases), how can the record ctor call be converted. 

Record constructor calls should be similar to function calls, it's just that we have to consider that every record is potentially also a function.

However, looking closely it seems the problem is a record constructor (or function call) where elements in the record (or function) are removed, is that correct? 
That case wasn't considered for the design of the conversion scripts; and especially the positional argument case will take some thought.

**Comment by beutlich** [comment]
> However, looking closely it seems the problem is a record constructor (or function call) where elements in the record (or function) are removed, is that correct?

Yes, that is the case here. I believe it is rather impossible to convert record ctor calls for record classes where components have been removed or component types are changed.

I will simply add a convertMessage here. Since Mosfet.Mosfet is in Modelica.Electrical.Spice3.**Internal** and shall not be used by users, there is enough hope that no user is affected.

**Pull request merged**
