### PR TITLE
Unify Lines models

### PR DESCRIPTION
**Pull request by dietmarw**
This contains the enhancement commit which was accidentally committed to #3828

### CODE REVIEW

**Review by AHaumer — APPROVED** [review]
Fine with me, as long as these changes don't strikeover the bugfix #3828

**Comment by dietmarw** [comment]
I'm not sure what you mean with "strikeover".

**Comment by AHaumer** [comment]
> 
> 
> I'm not sure what you mean with "strikeover".

overwrite (take back the changes)

**Comment by dietmarw** [comment]
No they won't.

**Review by christiankral — APPROVED** [review]
Look good.

**Comment by christiankral** [comment]
One more change: Add start values of `es` and `er` as used in #3828

**Pull request merged**
