### PR TITLE
Replace Boolean parameter nonLinearPermeability by enumeration materialCharacteristic

### LINKED ISSUE #3323: Conversion from Boolean parameter to enumeration
Background:
In FluxTubes, I'd like to change `parameter Boolean nonLinearPermeability` to an enumeration (let's call it `matericalCharacteristic` with choices `{Linear, Approximation}` . This enables us in future to implement other types of approximation or interpolation functions. 

Nevertheless, for this change a conversion is needed - and I've no idea how to tackle this:
Parameter propagation:
replace `nonLinearPermeability=false` with `matericalCharacteristic=Linear`
replace `nonLinearPermeability=true` with `matericalCharacteristic=Approximation`
How to handle cases when the user evaluates the Boolean parameter (using it in an if-statement)?
What about the cases when a user propagates a user-defined Boolean parameter?

I'd apprecitae your help to implement a proper conversion script.

### PR DESCRIPTION
**Pull request by AHaumer**
,,, materialCharacteristic to enable other approxmation or interpolation functions for material characteristics provided by the user.
As explained in #3323, the only thing missing is a concersion script - I hope I get some help.

Closes #3323.

### CODE REVIEW

**Comment by beutlich** [comment]
> As explained in #3323, the only thing missing is a concersion script - I hope I get some help.

Let me have a look.

**Comment by beutlich** [comment]
Here's my dummy test model (using MSL 3.2.3):

```mo
      model Issue3323 "Conversion test for #3323"
        extends Modelica.Icons.Example;
        Modelica.Magnetic.FluxTubes.Shapes.FixedShape.GenericFluxTube generic;
        Modelica.Magnetic.FluxTubes.Shapes.FixedShape.Cuboid cuboid(
          nonLinearPermeability=false);
        Modelica.Magnetic.FluxTubes.Shapes.FixedShape.HollowCylinderAxialFlux cylinder1(
          nonLinearPermeability=true);
        Modelica.Magnetic.FluxTubes.Shapes.FixedShape.HollowCylinderRadialFlux cylinder2(
          nonLinearPermeability=cylinder1.nonLinearPermeability);
        Modelica.Magnetic.FluxTubes.Basic.Ground ground;
        connect(generic.port_p, ground.port);
        connect(generic.port_n, ground.port);
        connect(cuboid.port_p, ground.port);
        connect(cuboid.port_n, ground.port);
        connect(cylinder1.port_p, ground.port);
        connect(cylinder1.port_n, ground.port);
        connect(cylinder2.port_p, ground.port);
        connect(cylinder2.port_n, ground.port);
        annotation(experiment(StopTime=1), Documentation(info="<html>
<p>
Conversion test for <a href=\"https://github.com/modelica/ModelicaStandardLibrary/issues/3323\">#3323</a>.
</p>
</html>"));
      end Issue3323;
```

Testing with conversion script:

```
convertElement({"Modelica.Magnetic.FluxTubes.Shapes.FixedShape.GenericFluxTube",
                "Modelica.Magnetic.FluxTubes.Shapes.FixedShape.Cuboid",
                "Modelica.Magnetic.FluxTubes.Shapes.FixedShape.HollowCylinderAxialFlux",
                "Modelica.Magnetic.FluxTubes.Shapes.FixedShape.HollowCylinderRadialFlux",
                "Modelica.Magnetic.FluxTubes.Interfaces.PartialFixedShape"},
                "nonLinearPermeability", "materialCharacteristic");
convertModifiers({"Modelica.Magnetic.FluxTubes.Shapes.FixedShape.GenericFluxTube",
                  "Modelica.Magnetic.FluxTubes.Shapes.FixedShape.Cuboid",
                  "Modelica.Magnetic.FluxTubes.Shapes.FixedShape.HollowCylinderAxialFlux",
                  "Modelica.Magnetic.FluxTubes.Shapes.FixedShape.HollowCylinderRadialFlux",
                  "Modelica.Magnetic.FluxTubes.Interfaces.PartialFixedShape"},
                  {"nonLinearPermeability"}, {"materialCharacteristic=if %nonLinearPermeability% then Modelica.Magnetic.FluxTubes.Types.MaterialCharacteristic.ApproximationRo00 else Modelica.Magnetic.FluxTubes.Types.MaterialCharacteristic.Linear"}, true);
```

gets the literal modifiers right, but not the component reference to `cylinder1.nonLinearPermeability`.

**Comment by AHaumer** [comment]
Thanks a lot @beutlich I think I should proceed with this PR even if users have to apply some conversions manually ... however, a tool should throw a diagnistic message in the case you did show.
Workarounds (with both Boolean and enumeration parameter) are clumsy.

**Comment by AHaumer** [comment]
@beutlich I'm impressed even the following is handled correctly:
```
  parameter Boolean nonLinearPermeability=true;
  Modelica.Magnetic.FluxTubes.Shapes.FixedShape.GenericFluxTube generic1(
      nonLinearPermeability=nonLinearPermeability);
```

**Comment by beutlich** [comment]
@HansOlsson Can you please cross-check the proposed conversion and if we have to live with invalid conversions for component references? Thank you.

**Comment by HansOlsson** [comment]
> @HansOlsson Can you please cross-check the proposed conversion and if we have to live with invalid conversions for component references? Thank you.

I currently don't see a way to replace the component-reference with something correct; the problem is that convertElement only replaces the element with another one (which therefore must be compatible), and convertModifiers only changes what is modified; not expressions in general.
Obviously it could be improved in the future, but currently I don't see anything better.

BTW: This means that the convertElement-part can be removed.

**Comment by beutlich** [comment]
I do not feel confident then to merge this for MSL v4.0.0. As far as remember @casella asked for an all-automatic conversion w/o potential traps.

Checking the private mail communication from @AHaumer I can see that the motivation of this PR is the ability for future extensions. Strictly seen, it is not necessary for MSL v4.0.0 and only nice-to-have.

**Comment by casella** [comment]
> I do not feel confident then to merge this for MSL v4.0.0. As far as remember @casella asked for an all-automatic conversion w/o potential traps.

Yeah, for me this is a strict requirement. I spent quite some time manually adjusting code from MSL 2.x to MSL 3.x because of enumeration. It was appropriate to do that back then, because the "fake enumeration" implemented by integers were horrible, but I'd rather avoid this kind of pain for the MSL 3.2.x to MSL 4.0.0 conversion

**Comment by AHaumer** [comment]
Since no (fully) automatic conversion from Boolean parameter to enumeration is possible (now), let's shift that for later.

**Comment by HansOlsson** [comment]
> Since no (fully) automatic conversion from Boolean parameter to enumeration is possible (now), let's shift that for later.

An additional point is as @beutlich wrote it is currently not giving any benefits, but just preparing for a future change. And I realized that we could even do the planned future change in a backwards compatible way:
```
 parameter Boolean nonLinearPermeability=...;
 parameter Types.MaterialCharacteristic materialCharacteristic=if nonLinearPermeability then Modelica.Magnetic.FluxTubes.Types.MaterialCharacteristic.ApproximationRo00 else Modelica.Magnetic.FluxTubes.Types.MaterialCharacteristic.Linear;
```
And "hide" nonLinearPemeability in some way to indicate that it is deprecated.

**Pull request closed without merging**
