### PR TITLE
Splitting off UsersGuides/ReleaseNotes 

### PR DESCRIPTION
**Pull request by HansOlsson**
To make it easier to track changes.
As discussed at the MAP-Lib meeting.
Also to be cherry picked to maint/4.1.0

### CODE REVIEW

**Review by beutlich — COMMENTED** [review]
The disadvantage of such a file modularization is that we lose track of the git history. But given that we rather odd new classes to the ReleaseNotes.mo it might be accpetable.

**Comment by Harisankar-Allimangalath** [comment]
@casella @HansOlsson @beutlich so does the present structure looks good and can we proceed with an approval  ?

Thankyou

**Review by casella — APPROVED** [review]
This was automatically generated by Dymola, so I trust the content should be ok

**Review by GallLeo — COMMENTED** [review]
Fine, as discussed in MAP-LIB meeting.

**Review by GallLeo — APPROVED** [review]

**Comment by Harisankar-Allimangalath** [comment]
@HansOlsson @GallLeo @casella ,  we have to backport this to maint/4.1.x right , just a doubt as the milestone is changed . ?

Thanks

**Comment by beutlich** [comment]
> Also to be cherry picked to maint/4.1.0

I doubt it is necessary.

> as the milestone is changed

* If merged to master the milestone must not be MSL4.1.0.
* I merged to master and also cherry-picked to maint/4.1.x, the milestone must not be set at all (since it should only occure in the release notes of the release where it occurred first).

**Pull request merged**
