### PR TITLE
Fix derivatives in 2D-table for one-sided extrapolation by constant continuation

### LINKED ISSUE #3894: Derivative signal of combiTable2Ds is set to zero outside of table with HoldLastPoint
The derivative signal of a Modelica.Blocks.Tables.CombiTable2Ds with extrapolation set to HoldLastPoint is zero if extrapolation is required to calculate the output.

This is incorrect for example if the input signals to a combiTable2Ds component is set to
u1=time+1
u2 = -1 
is feed into a combiTable2Ds component with 
table = [0,1,2;
             1,2,3;
             2,3,4]
and is simulated for 1[s]

The derivative of the output is zero however the output of the signal changes from 2 to 3 and the derivative should be 1.

Steps to recreate the issue in Dymola:
1. clearFlags()
2. open the tabletest3.mo (the extension will have to be renamed to .mo) and simulate by pressing F10, this should simulate and generate the plots.
3. Compare der1.y and derivative.y

der1.y is the der() of the table and this is zero when run here, derivative.y is the estimate of the derivative and converges to 1.  der1.y should be 1
[tabletest3.txt](https://github.com/modelica/ModelicaStandardLibrary/files/7519068/tabletest3.txt)
.

### PR DESCRIPTION
**Pull request by beutlich**
Closes #3894.

@GarronFish You can test by cloning master branch of [ModelicaTableAdditions](https://github.com/tbeu/ModelicaTableAdditions) where I already updated the binaries.

### CODE REVIEW

**Comment by GarronFish** [comment]
> Closes #3894.
> 
> @GarronFish You can test by cloning master branch of [ModelicaTableAdditions](https://github.com/tbeu/ModelicaTableAdditions) where I already updated the binaries.

I've tested the functionality using tabletest4.txt attached.
[tabletest4.txt](https://github.com/modelica/ModelicaStandardLibrary/files/7532619/tabletest4.txt)

The input signals go "around" the table               0,1,2
                                                                              1,1,2
                                                                              2.2,3
to test the derivative calculation for each case.  
The test gave the expected results.

Functionally this appears to be working correctly now.  Thanks!

**Comment by beutlich** [comment]
> I've tested the functionality using tabletest4.txt attached.

Nice stimulation. I added it as new test model. Thanks.

> Functionally this appears to be working correctly now. Thanks!

Thanks for testing and confirmation.

**Comment by GarronFish** [comment]
> > I've tested the functionality using tabletest4.txt attached.
> 
> Nice stimulation. I added it as new test model. Thanks.
> 
> > Functionally this appears to be working correctly now. Thanks!
> 
> Thanks for testing and confirmation.

The test is better if the table is set so the derivative values are unique for example:
table=[0,1,2; 1,1,7; 2,2,4],

**Comment by HansOlsson** [comment]
I'm having a bit of trouble understanding how this is supposed to work. Basically I expected the getValue code to be matched by derivative code, but the codes are different and I only see how the new code matches linear interpolation in table and hold-extrapolation - but not for other interpolations for hold-interpolation. Am I missing something obvious?

**Comment by beutlich** [comment]
The change considers the cases to HOLD_LAST_POINT where there is one-sided extrapolation.

**Review by HansOlsson — APPROVED** [review]
Seems good now.

**Review by sjoelund — APPROVED** [review]

**Pull request merged**
