### PR TITLE
Use quoted section for preformated text

### LINKED ISSUE #2752: Use quoted section for preformated text
I suggest to quote sections of preformated text in the documentation, in HTML by `<blockquote> ... </blockquote>`. This is already established in plenty of classes, but not consequently in all classes.
If agreed, this should especially be documented in `Modelica.UsersGuide.Conventions.Documentation.Format.Code`.

### PR DESCRIPTION
**Pull request by beutlich**
@tobolar This is my brute-force search-and-replace. Not sure if it is good enough.

Resolves #2752.

### CODE REVIEW

**Comment by tobolar** [comment]
... and this my brute-force replacement of blanks in front of preformated text.
I will also update `Modelica.UsersGuide.Conventions.Documentation.Format.Code`in the next commit.

**Comment by tobolar** [comment]
@beutlich You didn't touch `<pre>` in `Modelica.UsersGuide.ReleaseNotes.Version_1_5`. On purpose? Or could I do it?

**Comment by beutlich** [comment]
I'll care for the merge-conflict in Semiconductors later.

**Comment by beutlich** [comment]
@christiankral Can you please approve or reject? Otherwise, we will risk to get more and more conflicts.

**Comment by tobolar** [comment]
> (at)christiankral Can you please approve or reject? Otherwise, we will risk to get more and more conflicts.

@beutlich We have changed a huge amount of files which is hart to review reliably anyway. So I would suggest to use the brute-force for the third time here and to merge the changes. I know this brakes the rule of two reviewers at least but in this case I guess we can only reach reliable review using an automation. And this is partly done by CI used.

**Comment by beutlich** [comment]
> 
> 
> > (at)christiankral Can you please approve or reject? Otherwise, we will risk to get more and more conflicts.
> 
> @beutlich We have changed a huge amount of files which is hart to review reliably anyway. So I would suggest to use the brute-force for the third time here and to merge the changes. I know this brakes the rule of two reviewers at least but in this case I guess we can only reach reliable review using an automation. And this is partly done by CI used.

Yes, I am in favour.

**Comment by beutlich** [comment]
@tobolar I resolved the merge conflicts once again (sigh). Can you please double-check, also in Modelica.Clocked. Thanks.

What still is strange is that there are 1629 occurences of `<blockquote><pre>` in MSL, but only 1627 occurences of `</pre></blockquote>`

**Comment by tobolar** [comment]
@beutlich 
> What still is strange is that there are 1629 occurences of `<blockquote><pre>` in MSL, but only 1627 occurences of `</pre></blockquote>`

Done.

> ...also in Modelica.Clocked.

Checked.

I guess you can really merge this now.

**Comment by tobolar** [comment]
@beutlich 
I guess you really shall merge this now.

**Comment by beutlich** [comment]
> 
> 
> @beutlich
> 
> > What still is strange is that there are 1629 occurences of `<blockquote><pre>` in MSL, but only 1627 occurences of `</pre></blockquote>`
> 
> Done.

Conformed. Thanks.

**Comment by beutlich** [comment]
> 
> 
> @beutlich
> I guess you really shall merge this now.

Doing so right now.

**Pull request merged**
