### PR TITLE
Utilize GitHub Actions for CI

### PR DESCRIPTION
**Pull request by beutlich**
This replaces Travis CI by GitHub Actions and has the advantage that the CI jobs run instantaneously and are visible as Checks directly in the PR.

This supersedes also #3701. Note, that no CI checks are removed, instead the OM checks are only run by Jenkins and no longer by Travis CI or GitHub Actions.

The one failing link check already is addressed by #3682. The link checks are run as weekly cron job and not with the CI for PRs.

I also set the Jenkins and GitHub Actions checks as required to pass.

### CODE REVIEW

**Review by dietmarw — APPROVED** [review]
Nice work.

**Review by sjoelund — APPROVED** [review]
Seems OK. Although I'd rather have it required to also pass compiling the C-sources.

**Comment by beutlich** [comment]
> 
> 
> Seems OK. Although I'd rather have it required to also pass compiling the C-sources.

jenkins/pr-merge is required. I will also see if I cann add it to GH Actions, too.

**Comment by sjoelund** [comment]
> jenkins/pr-merge is required. I will also see if I cann add it to GH Actions, too.

Oh, I must have been tired. Your first entry said it was so :D

**Pull request merged**
