### PR TITLE
Remove dead link to old OM wiki

### PR DESCRIPTION
**Pull request by beutlich**

### CODE REVIEW

**Review by casella — APPROVED** [review]

**Comment by casella** [comment]
In fact, all the information in that section of the documentation is completely obsolete, and should be either updated or removed

**Comment by casella** [comment]
I guess this should also be backported to maint/4.1.0

**Comment by casella** [comment]
In fact, changing history a-posteriori is kind of weird, but I guess in this case we have to.

**Comment by casella** [comment]
@beutlich would you mind back-porting this to maint/4.1.x? Thanks!

**Comment by beutlich** [comment]
> @beutlich would you mind back-porting this to maint/4.1.x? Thanks!

See #4501.

**Pull request merged**
