### PR TITLE
Fix icons of electrical sensors

### PR DESCRIPTION
**Pull request by christiankral**
Refs #3354 and extends it to transient electrical sensors. This PR fixes

- size of `%name`
- match color of connectors and connection lines of icon
- unify appearance of electrical flow sensors (current, flux) with one solid line from the left to right connector, indicating the there is no potential difference from one connector to the other (this was implemented for some electrical sensors already, and is unified now)

image

### CODE REVIEW

**Comment by beutlich** [comment]
Oops, why do I see the comparisonSignals.txt of #3348 here?

**Comment by christiankral** [comment]
Bad news :-( 

I created the branch not from master apparently. Definitely my fault. @beutlich Do you see a way to fix this issue in an elegant way or do I have to start over and re-apply all the changes manually.

**Comment by beutlich** [comment]
Hang on. Can do.

**Comment by christiankral** [comment]
Would cherry-picking help?

**Comment by christiankral** [comment]
Thanks

**Comment by beutlich** [comment]
Yes, that tis the way to go.

**Comment by beutlich** [comment]
Fixed.

**Comment by christiankral** [comment]
Thanks a lot!

**Pull request merged**
