### PR TITLE
Initialize output array C even when multiColoredSurface=false

### PR DESCRIPTION
**Pull request by tobolar**
Refs #3687

### CODE REVIEW

**Review by HansOlsson — APPROVED** [review]
Looks good.

**Review by beutlich — COMMENTED** [review]
Why not a `final` modification?

**Comment by tobolar** [comment]
> Why not a final modification?

Fine to me. But does `final` ever makes sense in function outputs?

**Comment by beutlich** [comment]
> Fine to me. But does `final` ever makes sense in function outputs?

Why not?

**Comment by tobolar** [comment]
Can the function's outputs be modified in function's extends? I would never come to the idea to modify output once set in the parent function.

**Comment by tobolar** [comment]
This merging is blocked now:
> New changes require approval from someone other than the last pusher.

@HansOlsson @beutlich @thorade Anyone can help here / redo approval?

**Review by HansOlsson — APPROVED** [review]
Looks good.

**Pull request merged**
