### PR TITLE
Just use "redeclare" instead of "redeclare final"

### PR DESCRIPTION
**Pull request by HansOlsson**
Otherwise the class will be final which in some cases lead to problems.
https://github.com/modelica/ModelicaSpecification/issues/2676

### CODE REVIEW

**Review by AHaumer — COMMENTED** [review]
I understand but I'm not involved in Fluid, so maybe ask someone more famailiar with Fluid?

**Comment by HansOlsson** [comment]
> I understand but I'm not involved in Fluid, so maybe ask someone more famailiar with Fluid?

Sorry, I got confused, one issue involved the Machines-library in the Fluid-library, not the Electrical.Machines-library.

**Review by thorade — APPROVED** [review]

**Review by henrikt-ma — COMMENTED** [review]
The changes look harmless to me, as they only remove the use of `final` when redeclaring classes.

However, I am not sure exactly what problem is being solved here.  My guess is that this is really just a matter of removing some `final` that are believed to have been added for the wrong reason (namely, to make sure that the redeclaration isn't treated as `redeclare replaceable`).  If my guess is wrong, however, I am unable to tell whether the proposed removal of `final` would have the desired effect, and it must be noted that the very meaning of a class being final is subject to ongoing discussion in #2719.

**Review by MartinOtter — APPROVED** [review]

**Comment by HansOlsson** [comment]
> However, I am not sure exactly what problem is being solved here. My guess is that this is really just a matter of removing some `final` that are believed to have been added for the wrong reason (namely, to make sure that the redeclaration isn't treated as `redeclare replaceable`). If my guess is wrong, however, I am unable to tell whether the proposed removal of `final` would have the desired effect, and it must be noted that the very meaning of a class being final is subject to ongoing discussion in #2719.

You mean https://github.com/modelica/ModelicaSpecification/pull/2719
However, that issue is now resolved and the impact on this use of `final redeclare` is that it goes from _a bit weird with unclear consequences_ to _bad and often making other models illegal._
Thus I will merge this PR soonish.

**Comment by beutlich** [comment]
Off-topic: I'll care for a clean commit history w/o merge commits.

**Comment by beutlich** [comment]
> 
> 
> Off-topic: I'll care for a clean commit history w/o merge commits.

Done.

**Comment by beutlich** [comment]
Should this be back-ported to the maintenance branches?

**Comment by HansOlsson** [comment]
> Should this be back-ported to the maintenance branches?

Yes.

**Comment by beutlich** [comment]
> 
> 
> > Should this be back-ported to the maintenance branches?
> 
> Yes.

Done by #3751 and #3752 before it will get forgotten.

**Pull request merged**
