### PR TITLE
Use one character instead of line drawings

### PR DESCRIPTION
**Pull request by HansOlsson**
This is more consistent with the name of the operator, and avoids graphical artifacts in some tools like Dymola.
(The new variant works with and without anti-aliasing, the old one worked with neither.)

I have not tested in other tools, but I notice that the old OpenModelica-variants are almost invisibly thin.

Was based on looking at #3637

### CODE REVIEW

**Comment by sjoelund** [comment]
Wasn't the problem that tools do not render text at all in the smaller icons?

**Comment by HansOlsson** [comment]
> Wasn't the problem that tools do not render text at all in the smaller icons?

_One_ character texts normally work, as I recall; and the function icon uses this for 'f'.

**Comment by sjoelund** [comment]
Yes, OMEdit also does 2-character icons. I don't know about the online documentation generator as it's third-party code.

Old icons in OMEdit:
Screenshot_20201002_142527
New one:
Screenshot_20201002_142819

**Review by beutlich — COMMENTED** [review]
This is how it looks in SimulationX.

Old:
grafik

New:
grafik

**Comment by beutlich** [comment]
@maltelenz We should only use one of the standardized font names, being "serif" , "sans-serif" , and "monospace". Can you check again, please.

**Comment by maltelenz** [comment]
@beutlich Good point. Unfortunately those alternatives have an uglier asterisk, but I agree it is the right thing to do. New version:

```
package OperatorIcons2
  block '-'
    annotation(Icon(coordinateSystem(preserveAspectRatio = false, extent = {{-100, -100}, {100, 100}}, initialScale = 0.1, grid = {10, 10}), graphics = {Rectangle(visible = true, lineColor = {200, 200, 200}, fillColor = {248, 248, 248}, fillPattern = FillPattern.HorizontalCylinder, extent = {{-100, -100}, {100, 100}}, radius = 25), Rectangle(visible = true, lineColor = {128, 128, 128}, extent = {{-100, -100}, {100, 100}}, radius = 25), Text(visible = true, origin = {-0, 23.265}, textColor = {128, 128, 128}, extent = {{-100, -79.072}, {100, 98.84}}, textString = "-", fontSize = 800, fontName = "monospace")}));
  end '-';

  block '*'
    annotation(Icon(coordinateSystem(preserveAspectRatio = false, extent = {{-100, -100}, {100, 100}}, initialScale = 0.1, grid = {10, 10}), graphics = {Rectangle(visible = true, lineColor = {200, 200, 200}, fillColor = {248, 248, 248}, fillPattern = FillPattern.HorizontalCylinder, extent = {{-100, -100}, {100, 100}}, radius = 25), Rectangle(visible = true, lineColor = {128, 128, 128}, extent = {{-100, -100}, {100, 100}}, radius = 25), Text(visible = true, origin = {-0.962, 15.534}, textColor = {128, 128, 128}, extent = {{-99.038, -216.588}, {101.018, 99.631}}, textString = "*", fontSize = 800, fontName = "monospace")}));
  end '*';
end OperatorIcons2;
```
And rendering in SystemModeler:
image

**Comment by tobolar** [comment]
To be consistent throughout the MSL, - it would be nice to estabilish the rule for icons containing one (and two?) characters as a main symbol. See also #3581 
This IMO shall concern also special characters, not just the lettering.

**Comment by HansOlsson** [comment]
> @beutlich Good point. Unfortunately those alternatives have an uglier asterisk, but I agree it is the right thing to do. New version:
> 
> ```
> package OperatorIcons2
>   block '-'
>     annotation(Icon(coordinateSystem(preserveAspectRatio = false, extent = {{-100, -100}, {100, 100}}, initialScale = 0.1, grid = {10, 10}), graphics = {Rectangle(visible = true, lineColor = {200, 200, 200}, fillColor = {248, 248, 248}, fillPattern = FillPattern.HorizontalCylinder, extent = {{-100, -100}, {100, 100}}, radius = 25), Rectangle(visible = true, lineColor = {128, 128, 128}, extent = {{-100, -100}, {100, 100}}, radius = 25), Text(visible = true, origin = {-0, 23.265}, textColor = {128, 128, 128}, extent = {{-100, -79.072}, {100, 98.84}}, textString = "-", fontSize = 800, fontName = "monospace")}));

Hmm...
fontsize=800 seems odd
(For some reason, that only Swedes understand, the number triggered some old memories.)

I would say that something around 20-30 is more reasonable in Dymola.
However, there is something weird with vertical alignment in Dymola - @DagBruck 

Note that other similar icons, such as Modelica.Blocks.Math.MultiProduct and Modelica.Icons.Function also have somewhat smallish texts without setting fontSize.

**Comment by tobolar** [comment]
I would suggest to accept this PR with some larger text size / font size and to continue in #3581 - in order to omit discussion in two threads

**Comment by maltelenz** [comment]
> fontsize=800 seems odd

It is a size that made it reasonably sized in SystemModeler.

> I would say that something around 20-30 is more reasonable in Dymola.

That is a really large difference to our 800. I would assume that is a bug in Dymola, or do you have indications otherwise?


> Note that other similar icons, such as Modelica.Blocks.Math.MultiProduct and Modelica.Icons.Function also have somewhat smallish texts without setting fontSize.

`MultiProduct` looks really tiny as well, so not a good example to follow:

image

**Comment by HansOlsson** [comment]
> > I would say that something around 20-30 is more reasonable in Dymola.
> 
> That is a really large difference to our 800. I would assume that is a bug in Dymola, or do you have indications otherwise?

I don't know - it could be that fontSize isn't well-specified. 
I found that there is only one use of non-zero fontSize in MSL and that's in a diagram: Modelica.Mechanics.MultiBody.Examples.Loops.PlanarFourbar
@DagBruck ?

> > Note that other similar icons, such as Modelica.Blocks.Math.MultiProduct and Modelica.Icons.Function also have somewhat smallish texts without setting fontSize.
> 
> `MultiProduct` looks really tiny as well, so not a good example to follow:
> 
> image

It doesn't look _that_ tiny in Dymola, and my point was to first have it consistent and then later improve it.

MathOp

**Comment by HansOlsson** [comment]
> I would suggest to accept this PR with some larger text size / font size and to continue in #3581 - in order to omit discussion in two threads

I understand that it's bit smallish, but to me it would make more sense to accept this PR as is, and then continue in #3581 as we (as noted) already have other icons that look similar using extent, and the meaning of fontSize seems completely different in different tools.

It could be that both extent and fontSize are unclear for texts, and/or some tools have defects - but as long as we copy an existing variant I don't see a problem with this PR.

**Review by maltelenz — CHANGES_REQUESTED** [review]
> we (as noted) already have other icons that look similar using extent

That is no reason to spread the problem to more icons.

The purpose of this PR seems to be to work around a bug in one tool where the current icon looks ugly. I don't think it is fair to change to a different implementation that makes it ugly and unreadably small in other tools.

**Comment by HansOlsson** [comment]
> @maltelenz We should only use one of the standardized font names, being "serif" , "sans-serif" , and "monospace". Can you check again, please.

I think the "serif" has the nicest "*" (at least in Dymola). But we have the issue that vertical alignment differs, which complicates things.

**Comment by maltelenz** [comment]
Indeed there is a problem with alignment, but better than the original change. In System Modeler:

image

**Comment by maltelenz** [comment]
I would like to see what the proposed alignment looks like in multiple other tools, as well as the alignment of this alternative that places it correctly in WSM:

```
operator record ComplexWSMAlign
  encapsulated operator '-'
    annotation(Icon(coordinateSystem(preserveAspectRatio = false, extent = {{-100, -100}, {100, 100}}, initialScale = 0.1, grid = {10, 10}), graphics = {Rectangle(visible = true, lineColor = {200, 200, 200}, fillColor = {248, 248, 248}, fillPattern = FillPattern.HorizontalCylinder, extent = {{-100, -100}, {100, 100}}, radius = 25), Rectangle(visible = true, lineColor = {128, 128, 128}, extent = {{-100, -100}, {100, 100}}, radius = 25), Text(visible = true, origin = {0, 10}, textColor = {128, 128, 128}, extent = {{-200, -200}, {200, 250}}, textString = "-", fontName = "serif")}));
  end '-';

  encapsulated operator '*'
    annotation(Icon(coordinateSystem(preserveAspectRatio = false, extent = {{-100, -100}, {100, 100}}, initialScale = 0.1, grid = {10, 10}), graphics = {Rectangle(visible = true, lineColor = {200, 200, 200}, fillColor = {248, 248, 248}, fillPattern = FillPattern.HorizontalCylinder, extent = {{-100, -100}, {100, 100}}, radius = 25), Rectangle(visible = true, lineColor = {128, 128, 128}, extent = {{-100, -100}, {100, 100}}, radius = 25), Text(visible = true, origin = {0, 10}, textColor = {128, 128, 128}, extent = {{-200, -200}, {200, 100}}, textString = "*", fontName = "serif")}));
  end '*';
end ComplexWSMAlign;
```

This way we can choose the alignment that looks the least bad in most tools.

Here is what it looks like in System Modeler
image

**Comment by HansOlsson** [comment]
> I would like to see what the proposed alignment looks like in multiple other tools, as well as the alignment of this alternative that places it correctly in WSM:

Hmm.. I don't see a visual difference between ComplexWSMAlign and the tip of this branch in Dymola.
If the extra attributes are needed I can add hem.

Here's how it looks in Dymola (original, first commit, latest and ComplexWSMAlign).
Untitled

**Comment by henrikt-ma** [comment]
> Hmm.. I don't see a visual difference between ComplexWSMAlign and the tip of this branch in Dymola.
> If the extra attributes are needed I can add hem.

The asterisk is visibly higher up in `ComplexWSMAlign` compared to `Complex`.

**Comment by HansOlsson** [comment]
> > Hmm.. I don't see a visual difference between ComplexWSMAlign and the tip of this branch in Dymola.
> > If the extra attributes are needed I can add hem.
> 
> The asterisk is visibly higher up in `ComplexWSMAlign` compared to `Complex`.

Ok, and to me it seems a bit too high up in Dymola. Take the middle between the options?

**Comment by maltelenz** [comment]
I'd still like to see more tools than two, since this is clearly something where interpretation differs, and no pattern of interpretation can be established with two data points.

**Comment by HansOlsson** [comment]
> I'd still like to see more tools than two, since this is clearly something where interpretation differs, and no pattern of interpretation can be established with two data points.

@sjoelund @beutlich can you re-generate the images?

**Comment by HansOlsson** [comment]
> > I'd still like to see more tools than two, since this is clearly something where interpretation differs, and no pattern of interpretation can be established with two data points.
> 
> @sjoelund @beutlich can you re-generate the images?

Or perhaps @perost and @gkurzbach ?

**Comment by perost** [comment]
> > > I'd still like to see more tools than two, since this is clearly something where interpretation differs, and no pattern of interpretation can be established with two data points.
> > 
> > 
> > @sjoelund @beutlich can you re-generate the images?
> 
> Or perhaps @perost and @gkurzbach ?

Perhaps @adeas31? Graphical annotations are a bit outside my area.

**Comment by adeas31** [comment]
Master version:
image

PR version:
image

**Comment by maltelenz** [comment]
> Master version:
> 
> PR version:

How about `ComplexWSMAlign` from here: https://github.com/modelica/ModelicaStandardLibrary/pull/3638#issuecomment-737232649 ?

**Comment by adeas31** [comment]
image

**Review by maltelenz — APPROVED** [review]
Now that we have screenshots from 3 tools, it looks like System Modeler is the odd one out with regards to vertical alignment. Given that, I can accept the current PR as is.

The larger question of what the general guideline should be for icons like this remains to be discussed and decided in #3581, but this is a clear improvement compared to the earlier icon.

**Comment by beutlich** [comment]
> 
> 
> This is how it looks in SimulationX.
> 
> Old:
> grafik
> 
> Previously:
> grafik

Proposed:
grafik

**Review by beutlich — APPROVED** [review]

**Comment by beutlich** [comment]
@HansOlsson Please be aware that I rebased and force-pushed to trigger all CI checks. Feel free to merge though.

**Comment by christiankral** [comment]
This is what it in Dymola for Linux looks like:

image

**Comment by adeas31** [comment]
That is not nice. @perost or @sjoelund can you guys check how OpenModelica is doing on Linux?

**Comment by perost** [comment]
> That is not nice. @perost or @sjoelund can you guys check how OpenModelica is doing on Linux?

This is how the icons look for me: 
ComplexIcons

**Comment by DagBruck** [comment]
May I ask what font you use in SystemModeler and OpenModelica to render icons with e.g. "*" as the symbol? As you have probably seen, the location of the symbol depends also on the font, and how it is related to its metrics.

Alright, you can of course draw the text in a bitmap, crop any surrounding whitespace, and then draw what remains in the center. But that makes it hard to evenly space or align two text strings.

**Comment by DagBruck** [comment]
> > May I ask what font you use in SystemModeler and OpenModelica to render icons with e.g. "*" as the symbol? As you have probably seen, the location of the symbol depends also on the font, and how it is related to its metrics.
> 
> As far as I can tell: The system default (`QFontInfo Helper::systemFontInfo = QFontInfo(QFont());`)

Well, that's why I ask. :-) Qt gives different results depending on what system you are running on so you cannot really know.

**Comment by maltelenz** [comment]
> May I ask what font you use in SystemModeler and OpenModelica to render icons with e.g. "*" as the symbol? As you have probably seen, the location of the symbol depends also on the font, and how it is related to its metrics.

System Modeler uses "Arial" as the default font. If that doesn't exist on the system, Qt supposedly figures out the closest alternative.

**Pull request merged**
