### PR TITLE
Use InlineAfterIndexReduction consistently in Move.{position, position_der}

### LINKED ISSUE #2616: Inconsistent position function annotations LateInline vs. InlineAfterIndexReduction
Modelica.Mechanics.Rotational.Components.AngleToTorqueAdaptor uses either
Modelica.Mechanics.Rotational.Sources.Move.position (if use_phi and use_w and use_a) or Modelica.Mechanics.Rotational.Components.AngleToTorqueAdaptor.Move_w.position (if use_phi and use_w and not use_a). However function Move.position sets the `LateInline` annotation (3432a2218e1a4ff83dc1bd67f799aac6f6644eb4), whereas Move_w.position sets the `InlineAfterIndexReduction` annotation, leading to inconsistent behaviour with imported FMUs.

I propose to set the `InlineAfterIndexReduction` consistently, as also is done with new functions in Modelica.Blocks.Interfaces.PartialFMUadaptors.Functions.

### PR DESCRIPTION
**Pull request by beutlich**
Close #2616.

### CODE REVIEW

**Comment by HansOlsson** [comment]
The change itself looks as expected and seems good. But there are two related issues that will take a bit of time to investigate (related to systems of equations, and some rare cases for index reduction).

**Comment by HansOlsson** [comment]
> 
> 
> Seems ok, it might require some additional code changes in Dymola to fully use this in the best way - but the code is clearer.

This should be handled in Dymola 2021 (i.e. Move in PlanarLoops). 
Note that this change reverts the change in #1523

**Comment by beutlich** [comment]
Hm, my only motivation for #2616 was to have LateInline and InlineAfterIndexReduction consistently in the MSL. I did not want to revert #1523 by design. We could also use LateInline instead.

**Comment by HansOlsson** [comment]
> 
> 
> Hm, my only motivation for #2616 was to have LateInline and InlineAfterIndexReduction consistently in the MSL. I did not want to revert #1523 by design. We could also use LateInline instead.

Using LateInline consistently instead would require _even_ more changes.

The underlying issue that the Orientation-matrix has some special optimizations used in the resolve-functions and that they break some structural assumptions in special cases. Having different annotations is a hack to circumvent that, and doesn't clarify the reason for the difference.

**Comment by beutlich** [comment]
So, I guess we can leave it as is and do not need to revert this PR. Can you please confirm?

**Comment by HansOlsson** [comment]
> 
> 
> So, I guess we can leave it as is and do not need to revert this PR. Can you please confirm?

Yes.

**Pull request merged**
