### PR TITLE
Quasi-static Transformer

### PR DESCRIPTION
**Pull request by AHaumer**
I recently recognized that we're missing Electrical.QuasiStatic.SinglePhase.Transformer, i.e. in parallel to Electrcal.Analog.Baisic.Transformer. This is a transformer defined by primary, secondary and mutual inductance. 
I implemented this transformer model, and a test example (Electrical.QausiStatic.SinglePhase.Examples.MultipleResonance), too.
How can I suggest signals for comparison? I'd suggest currentSensor.abs_i and currentSensor.arg_i.

### CODE REVIEW

**Review by dietmarw — APPROVED** [review]
I removed one vendor annotation. Otherwise fine.

**Comment by AHaumer** [comment]
Why is continuous-integration/travis-ci/pr failing - could anyone explain?

**Comment by HansOlsson** [comment]
> Why is continuous-integration/travis-ci/pr failing - could anyone explain?

Internal CI-problem:

toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by sjoelund** [comment]
> Why is continuous-integration/travis-ci/pr failing - could anyone explain?

#3709 should fix that by no longer using travis or docker

**Comment by beutlich** [comment]
> 
> 
> Why is continuous-integration/travis-ci/pr failing - could anyone explain?

See https://github.com/modelica/ModelicaStandardLibrary/discussions/3699. I created two PRs removing the docker dependency from Travis CI. I am going to merge it later tonight.

**Comment by beutlich** [comment]
CI is fixed and all green. Note, that I needed to rebase to branch.

**Review by beutlich — COMMENTED** [review]
> How can I suggest signals for comparison? I'd suggest currentSensor.abs_i and currentSensor.arg_i.

Please do not forget to add the comparisonSignals.txt.

**Review by christiankral — APPROVED** [review]
Looks OK

**Comment by paultjevdh** [comment]
I came across this post and got interested. However, the MultipleResonance example will not translate for me (neither in openmodelica nor dymola).
When I revert the change of 13 march this year, it works fine in both (but supposedly no longer in Modelon Impact)
Something seems wrong in the call `Modelica.Units.SI.ComplexImpedance(100 +j*0)` .

**Comment by HansOlsson** [comment]
> I came across this post and got interested. However, the MultipleResonance example will not translate for me (neither in openmodelica nor dymola). When I revert the change of 13 march this year, it works fine in both (but supposedly no longer in Modelon Impact) Something seems wrong in the call `Modelica.Units.SI.ComplexImpedance(100 +j*0)` .

Yes, it is trying to convert to complex twice: `Modelica.Units.SI.ComplexImpedance(100)` by itself converts the number 100 to a Complex (Impedance), and `100+j*0` converts the number 100 to a Complex value.

My first guess is that there's an excessive optimization of `100+j*0` simplifying it to `100`, and thus causing it to work like `Modelica.Units.SI.ComplexImpedance(100)`. I don't know why it wasn't corrected immediately when I reported it.

**Comment by beutlich** [comment]
> I don't know why it wasn't corrected immediately when I reported it.

Actually, I did in #4374 (still w/o review since 28th of March).

**Pull request merged**
