### PR TITLE
Update matio library to 1.5.21

### PR DESCRIPTION
**Pull request by beutlich**
This updates ModelicaMatIO to the latest version 1.5.21 of the underlying matio library.

I can provide the new binaries for testing in a separate commit using a dedicated branch.

### CODE REVIEW

**Review by HansOlsson — APPROVED** [review]
Looks good, seems like primarily white-space changes.

**Comment by beutlich** [comment]
> 
> 
> Looks good, seems like primarily white-space changes.

Unfortunately they hide the relevant changes.

**Review by sjoelund — APPROVED** [review]
It seems OK. Not as many diffs to look through when using `git diff -w --ignore-space-at-eol --word-diff-regex=[^[:space:]] beutlich/update-matio-1.5.21~1..beutlich/update-matio-1.5.21`

**Comment by beutlich** [comment]
Superseded by #3982.

**Pull request merged**
