### PR TITLE
Fix unit errors in ReferenceAir.MoistAir

### PR DESCRIPTION
**Pull request by henrikt-ma**

### CODE REVIEW

**Comment by qlambert-pro** [comment]
This would help address the issues reported in https://github.com/modelica/ModelicaStandardLibrary/issues/4099

**Review by hubertus65 — APPROVED** [review]

**Review by HansOlsson — CHANGES_REQUESTED** [review]
Similar comment:
The examples in MSL should also be seen as examples of how people should write models.
The previous example worked for that - the new one does not.

Telling users that they cannot write such a simple test (as currently), but must introduce a number of new declaration that provides no benefit doesn't seem nice and will instead turn off users.

It also tells users that unit-checking is a chore.

If we wanted to give users something better we could do that, but then we should have public parameters, and sweep between two states with different pressures (p1A=1e5 at time=0 and p1B=2e5 at time=1) instead of a pressure slope, since that is more intuitive.

And the states should have pressure, temperature, and mass-fractions for consistency reasons.

Done correctly that would automatically be unit-correct, and indicate how to sweep a medium in a parameterized way.

**Comment by henrikt-ma** [comment]
> Done correctly that would automatically be unit-correct, and indicate how to sweep a medium in a parameterized way.

Are you suggesting to modify the example this way as part of this PR?  (I could do that.  No problem.)

**Comment by HansOlsson** [comment]
> > Done correctly that would automatically be unit-correct, and indicate how to sweep a medium in a parameterized way.
> 
> Are you suggesting to modify the example this way as part of this PR? (I could do that. No problem.)

Replied in #4115 having multiple PR for the different examples isn't helpful.

**Review by HansOlsson — APPROVED** [review]
Ok, according to MAP-Lib.
The requirement to have two reviewers doesn't seem to be working well when we don't have enough domain-experts.

**Pull request merged**
