### PR TITLE
Add modified Akima interpolation (univariate) as known from MATLAB ≥ R2017b

### LINKED ISSUE #1039: Tables: CombiTimeTable with Akima spline interpolation and borderline slopes
**Reported by beutlich on 20 Mar 2013 15:27 UTC**
Consider the following table model with Akima spline interpolation

```modelica
model ProblematicAkima
  parameter Real eps=0.1;
  Modelica.Blocks.Sources.CombiTimeTable t_old(
    table=[0+eps,5;1,3;2,1;3,1;4,1;5,3],
    smoothness=Modelica.Blocks.Types.Smoothness.ContinuousDerivative) annotation(Placement(transformation(extent={{-100,60},{-80,80}})));
end ProblematicAkima;
```

As long as `eps` is small but greater than zero we get similar curves for the interpolated values. For `eps` = 0 there is a behavioral changeover of the interpolated values that suddenly result in values less than one for `time` in (2,3).

Should an alternative variant of the Akima spline interpolation be used that interpolates (for `eps` = 0) linearly between `time` in [1,2] with the drawback of a discontinuous derivative at `time` = 2?

ProblematicAkima

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1039

### PR DESCRIPTION
**Pull request by beutlich**
The _modified_ Akima interpolation (aka. _Makima_) avoids overshoots/undershoots and edge cases of identical slopes that are present in the original Akima method. It is documented in [Cleve's corner](https://blogs.mathworks.com/cleve/2019/04/29/makima-piecewise-cubic-interpolation/) by Cosmin Ionita from The MathWorks and also available since MATLAB R2017b.

This properly resolves #1039, which previously was closed as wontfix.

### CODE REVIEW

**Comment by beutlich** [comment]
> Are there other references to this?

I am afraid, there is no other publication than the makima documentation by The MathWorks (https://www.mathworks.com/help/matlab/ref/makima.html#mw_e8ee1c8c-2cc3-46c4-90c4-c3208804ff4e) and this blog post.

**Comment by HansOlsson** [comment]
> I am afraid, there is no other publication than the makima documentation by The MathWorks (https://www.mathworks.com/help/matlab/ref/makima.html#mw_e8ee1c8c-2cc3-46c4-90c4-c3208804ff4e) and this blog post.

To me that is concerning from a legal perspective.

**Comment by beutlich** [comment]
> 
> 
> > I am afraid, there is no other publication than the makima documentation by The MathWorks (https://www.mathworks.com/help/matlab/ref/makima.html#mw_e8ee1c8c-2cc3-46c4-90c4-c3208804ff4e) and this blog post.
> 
> To me that is concerning from a legal perspective.

Understable. Would it be OK for you if I directly ask Cosmin Ionita from The MathWorks about rights and permission to use makima in OSS projects?

**Comment by MartinOtter** [comment]
> 
> 
> > > I am afraid, there is no other publication than the makima documentation by The MathWorks (https://www.mathworks.com/help/matlab/ref/makima.html#mw_e8ee1c8c-2cc3-46c4-90c4-c3208804ff4e) and this blog post.
> > 
> > 
> > To me that is concerning from a legal perspective.
> 
> Understandable. Would it be OK for you if I directly ask Cosmin Ionita from The MathWorks about rights and permission to use makima in OSS projects?

This does not make sense. The blog post is a publicly available web page. From a copyright point of view neither text nor a picture is used from this blog. Only information that is publicly shared in this post is utilized. It is completely fine to use this information. It is polite to reference this blog post (https://blogs.mathworks.com/cleve/2019/04/29/makima-piecewise-cubic-interpolation/). However, the MathWorks documentation should not be referenced.

**Comment by HansOlsson** [comment]
> This does not make sense. The blog post is a publicly available web page. From a copyright point of view neither text nor a picture is used from this blog.

The copyrighted blog post is problematic since it (as far as I understand) both contain a textual description and code. We should at least make it really clear that we implemented the code based on the description in the text.

**Comment by beutlich** [comment]
The C file has the reference to the blog post only. https://blogs.mathworks.com/cleve/2019/04/29/makima-piecewise-cubic-interpolation/#3b78d49a-0e90-4c1d-9f16-49a23a175132 are the modified formulas I used as input for the C implementation.

**Comment by beutlich** [comment]
> Please, use the following link in the description:
> 
> https://blogs.mathworks.com/cleve/2019/04/29/makima-piecewise-cubic-interpolation/

That link is used in the C file. What else do you mean by description?

**Comment by MartinOtter** [comment]
> 
> 
> > Please, use the following link in the description:
> > https://blogs.mathworks.com/cleve/2019/04/29/makima-piecewise-cubic-interpolation/
> 
> That link is used in the C file. What else do you mean by description?
Sorry. This is what I meant. All this looks fine now.

**Comment by beutlich** [comment]
> We should at least make it really clear that we implemented the code based on the description in the text.

@HansOlsson Is the link in the C file good enough or do you insist on an extra description in the documentation of the table blocks. (Would be a good idea anyway to have all references listed, but we do not have Modelica.Blocks.UsersGuide.References yet.)

**Comment by HansOlsson** [comment]
> We should at least make it really clear that we implemented the code based on the description in the text.
> 
> @HansOlsson Is the link in the C file good enough after the discussion or do you insist on an extra description in the documentation of the table blocks. (Would be a good idea anyway to have all references listed, but we do not have Modelica.Blocks.UsersGuide.References yet.)

I would prefer if it in some way stated that it was based on the _description_ on that page - not the _code_ on the same page.

**Comment by beutlich** [comment]
Instead of

```c
 /* Reference:
     Cosmin Ionita. Makima piecewise cubic interpolation, April 2019.
     (https://blogs.mathworks.com/cleve/2019/04/29/makima-piecewise-cubic-interpolation/)
  */
```

I could write

```c
 /* Reference:
     Cosmin Ionita. Makima piecewise cubic interpolation, April 2019.
     (https://blogs.mathworks.com/cleve/2019/04/29/makima-piecewise-cubic-interpolation/)
     Note: The MATLAB code listings have not been utilized during implementation.
  */
```

But, too me, this looks rather odd as this note simply does not belong here when just giving the reference.

There also is an official short-link, we could use: https://blogs.mathworks.com/cleve/?p=4707

**Comment by HansOlsson** [comment]
> But, too me, this looks rather odd as this note simply does not belong here when just giving the reference.

I meant something like: "Reference - method description in: https://blogs.mathworks.com/cleve/2019/04/29/makima-piecewise-cubic-interpolation/"

I don't view it as _that_ odd. People often give page-numbers/chapters when referencing a book.

**Pull request merged**
