### PR TITLE
Fix wrong usage of quantities in Modelica.Electrical.Analog.Interfaces.IdealSemiconductor

### PR DESCRIPTION
**Pull request by AHaumer**
fixes bug #4386

### CODE REVIEW

**Comment by beutlich** [comment]
> What's going wrong here?

Your two commits have diferent commit authors.
1) @AHaumer signed the CLA on 2020-01-14T09:15:43.761Z (via CLA Assistant)
2) @haa39214 did not sign the CLA

If you do not want to update teh commits it still can be fixed when squashing later.

**Comment by AHaumer** [comment]
I've used the same github user, just another notebook. No idea why the username is different and how I can sign the CLA with the other username because the two usernames are connected.

**Review by HansOlsson — APPROVED** [review]
Seems ok, but more stylistic improvement than bug-fix.

**Review by christiankral — APPROVED** [review]
This proposal is OK

**Pull request merged**
