### PR TITLE
Fix initialization of lines for maintenance

### PR DESCRIPTION
**Pull request by AHaumer**
This is the same fix as #3828 for master but without the unification of TLines for maintenance/4.0.x.

### CODE REVIEW

**Comment by dietmarw** [comment]
@AHaumer Sorry this is wrong. To not waste time I will fix both PR such that they will be correct. So please sit back and let me do this for now.

**Comment by AHaumer** [comment]
> 
> 
> @AHaumer Sorry this is wrong. To not waste time I will fix both PR such that they will be correct. So please sit back and let me do this for now.

Sorry, I would appreciate if you explain to me how I should have done.

**Comment by dietmarw** [comment]
You did not base your commit on the latest master is the simple answer. You used some other branch with lots of merge commits. 
1. checkout master and make sure to do a git pull in order to are in sync with upstearm master
2. create a branch
3. apply the commit(s)
4. push the branch and create the PR

**Comment by dietmarw** [comment]
Mind, for this you do not need to do it now since I've already have taken care of it.

**Pull request closed without merging**
