### PR TITLE
Changed dofpT issue #3695

### LINKED ISSUE #3695: Trajectory of 'k' in R134a_setState_pTX doesn't look suitable for comparison
Can someone please verify that `k` is a meaningful comparison signal in `R134a_setState_pTX`:
- https://github.com/modelica/MAP-LIB_ReferenceResults/blob/v4.0.0/ModelicaTest/Media/TestOnly/R134a_setState_pTX/comparisonSignals.txt

It doesn't look like the typical comparison signal:
k

### PR DESCRIPTION
**Pull request by wischhusen**
Changed code for function dofpT for testing to resolve #3695.

### CODE REVIEW

**Review by thorade — APPROVED** [review]
As stated by Stefan, density guess values are now calculated from temperature instead of pressure, leading to more stable iterations.

**Review by henrikt-ma — COMMENTED** [review]
Since I'm not a model domain expert, I can't say much until I see the updated reference result.

I can still mention, though, that the model seems to simulate fine, and all result trajectories look extremely nice – quite different in quality from the current reference results.

Regarding the general problem of not being able to say much until there is an updated reference result:
- The natural solution would be to have the updated reference in the very same PR.
- All tool vendors would be able to do CI testing of the MSL _master_.  This would mean early feedback to MAP-Lib, as well as giving tool vendors much more freedom to plan when to test and report issues regarding an upcoming MSL release. 
- This doesn't have to be prohibitively expensive storage wise: A suitably compressed result that still occupies more than 10–100 KB probably contains signals that are not suitable comparison variables anyway.  (At Wolfram we have very good experience from working with correctness checking against compressed results that we keep in the same repository as the Modelica library sources.)
- With the figure annotations expected in Modelica 3.5, having reference trajectories for selected variables stored with the model would take us very close to a situation where tools could actually be rendering figures in documentation instead of just showing screen shots:  Never more screen shots that could be out of date (only in case out-of-date reference result still allows correctness checks to pass), users can make a plot together with a simulated result to judge for themselves whether the match is close enough, no more figures produced by one tool looking out of place in another tool.

**Comment by beutlich** [comment]
> Since I'm not a model domain expert, I can't say much until I see the updated reference result.

Do you can confirm that the issue is fixed in WSM?

> The natural solution would be to have the updated reference in the very same PR

Nope. We do not have continuous reference results, but only generate them with new tags of MSL. If there is a new tag (= release) it is no big deal to regenerate them.

**Comment by henrikt-ma** [comment]
> > Since I'm not a model domain expert, I can't say much until I see the updated reference result.
> 
> Do you can confirm that the issue is fixed in WSM?

No.  Since I'm not a domain expert the only things I would be able to confirm would be either the removal of the problematic signal from the reference result (no need to involve System Modeler to verify this), or check the System Modeler simulation against an updated reference result.

> > The natural solution would be to have the updated reference in the very same PR
> 
> Nope. We do not have continuous reference results, but only generate them with new tags of MSL. If there is a new tag (= release or pre-release) it is no big deal to regenerate them.

Than that would mean that a new pre-release tag is needed in this case, so that tool vendors get access to the updated reference result.

**Comment by beutlich** [comment]
> 
> 
> > > Since I'm not a model domain expert, I can't say much until I see the updated reference result.
> > 
> > 
> > Do you can confirm that the issue is fixed in WSM?
> 
> No. Since I'm not a domain expert the only things I would be able to confirm would be either the removal of the problematic signal from the reference result (no need to involve System Modeler to verify this), or check the System Modeler simulation against an updated reference result.

OK, got it.

> > > The natural solution would be to have the updated reference in the very same PR
> > 
> > 
> > Nope. We do not have continuous reference results, but only generate them with new tags of MSL. If there is a new tag (= release or pre-release) it is no big deal to regenerate them.
> 
> Than that would mean that a new pre-release tag is needed in this case, so that tool vendors get access to the updated reference result.

Which would imply that there is some master plan about upcoming maintenance and main releases.

**Comment by henrikt-ma** [comment]
> Which would imply that there is some master plan about upcoming maintenance and main releases.

Right. I should probably have said that a new post-release tag is needed.

**Comment by beutlich** [comment]
> 
> 
> > Which would imply that there is some master plan about upcoming maintenance and main releases.
> 
> Right. I should probably have said that a new post-release tag is needed.

Which simply is a pre-release of the next maintenance release.

**Comment by henrikt-ma** [comment]
> > > Which would imply that there is some master plan about upcoming maintenance and main releases.
> > 
> > 
> > Right. I should probably have said that a new post-release tag is needed.
> 
> Which simply is a pre-release of the next maintenance release.

In that case, this PR should target a maintenance branch rather than _master_.  For something targeting _master_, I suppose it could be an extremely early pre-release of a new version whose version hasn't even been decided yet.

I really can't see how to do this in a sensible way without model updates going hand in hand with updated reference results.

**Comment by beutlich** [comment]
> 
> 
> > > > Which would imply that there is some master plan about upcoming maintenance and main releases.
> > > 
> > > 
> > > Right. I should probably have said that a new post-release tag is needed.
> > 
> > 
> > Which simply is a pre-release of the next maintenance release.
> 
> In that case, this PR should target a maintenance branch rather than _master_. For something targeting _master_, I suppose it could be an extremely early pre-release of a new version whose version hasn't even been decided yet.

Nope, all fixes go to master first. If it is labeled as bug it will be back-ported to all supported maintenance branches. That is the workflow we used to follow.

> I really can't see how to do this in a sensible way without model updates going hand in hand with updated reference results.

This would only work if reference results are stored within the same repository as the library and are automatically updated. IIRC the Buildings library is following that workflow. For what we have now, given the resources we need to face, we can only provide updated reference results with new tags.

**Comment by henrikt-ma** [comment]
> > I really can't see how to do this in a sensible way without model updates going hand in hand with updated reference results.
> 
> This would only work if reference results are stored within the same repository as the library and are automatically updated. IIRC the Buildings library is following that workflow. For what we have now, given the resources we need to face, we can only provide updated reference results with new tags.

(Way to go, Buildings, that makes it two of us!)

Of course, scarce resources must be taken into consideration, and I can only imagine this working if the workload was distributed upon all contributors by making it a required part of any pull request with impact on simulation results.  A key resource here – in addition to the library contributions themselves – would be continuous integration testing, which I think should be a high priority for quality assurance, don't you agree, @casella?  Ideally, this should even prevent PRs from being merged if they break correctness compared to the reference results.

I understand that there are other challenges here as well, like how to deal with tool-specific issues causing CI test failures, and how to make it sufficiently easy for library developers to update the reference results.  These are challenges I believe are necessary to address to reach the next level of quality assurance.

**Comment by MartinOtter** [comment]
Sorry. I have not enough knowledge about this topic to judge. Therefore, removed me as reviewer.

**Review by hubertus65 — APPROVED** [review]

**Pull request merged**
