### PR TITLE
Fix MSVC warning on strdup

### PR DESCRIPTION
**Pull request by beutlich**
Follow-up of #4222. I missed that one location. (Only detected when playing with #4265.) Sorry for the extra review.

### CODE REVIEW

**Review by HansOlsson — APPROVED** [review]

**Review by dietmarw-se — APPROVED** [review]
Lgtm

**Review by dietmarw — APPROVED** [review]
Lgtm

**Comment by Esther-Devakirubai** [comment]
@casella Should this be backported to maint 4.1.0?

**Comment by beutlich** [comment]
That was on merged on 2024-01-18, i.e., before branching of maint/4.1.0. Hence it already is there.

**Pull request merged**
