### PR TITLE
Add division tag around image tags

### PR DESCRIPTION
**Pull request by beutlich**
Replace paragraph tags around image tags by division tags.

### CODE REVIEW

**Comment by dietmarw** [comment]
I wonder. Is this something that ought to get added to the documentation guide lines?

**Comment by beutlich** [comment]
Not sure. Paragraph tag is a text container, whereas divison tag is without any semantics.

**Comment by dietmarw** [comment]
For now this really just looks like a tool issue which we are trying to hack. If not, then it really should go into the guidelines so that future editions don't have to do the whole search replace once more.

**Comment by beutlich** [comment]
It's not a tool issue. It is a formal correction only, I believe. No need to merge it for MSL v4.0.0 now.

**Comment by dietmarw** [comment]
If I recall correctly then `` should not really be inside `<p>` to start with but is tolerated. So if we want clean HTML I would just remove the surrounding `<p>`s.

**Comment by tobolar** [comment]
I agree with @dietmarw. In Modelica.UsersGuide.Conventions.Documentation.Format.Figures, there is only stated:
> 1. Figures have to be placed outside of paragraphs to be HTML compliant.

To omit missing spacing between text and images, I really set some images within `<div>` environment in Modelica.Mechanics.Rotational and Modelica.Mechanics.Translational. But this just arbitrary and without any concept/rules.

**Comment by beutlich** [comment]
You mean, it is not enough to have

> Figures have to be placed outside of paragraphs to be HTML compliant.

**Comment by HansOlsson** [comment]
> You mean, it is not enough to have
> 
> > Figures have to be placed outside of paragraphs to be HTML compliant.
> 
> ?

It could be clearer that it should be in this tag, but it isn't really necessary to update it.

**Pull request merged**
