### PR TITLE
Fix ModelicaTest.Magnetic.FluxTubes.BasicComponents reported by #3415

### PR DESCRIPTION
**Pull request by christiankral**
Set parameter `c_usefulFlux = 0.7`

See #3415.

### CODE REVIEW

**Comment by beutlich** [comment]
I wonder if #3307 added a real regression when the parameter binding `c_usefulFlux = 0.7` was replaced by a start value `c_usefulFlux(start=0.7)`?

**Comment by christiankral** [comment]
It possibly is not a regression but a not fully specified initial condition of `ModelicaTest`

**Comment by christiankral** [comment]
So it is rather a bug then...

**Comment by beutlich** [comment]
I'd claim we need a conversion if a parameter binding is removed (similar as if a parameter value is changed).

**Comment by christiankral** [comment]
I then re-open #3300, because that is where we introduced the problem by change the default value to a start value.

**Comment by christiankral** [comment]
@beutlich What would the conversion then look like?

```
convertModifiers({"Modelica.Magnetic.FluxTubes.Basic.LeakageWithCoefficient",
                  "Modelica.Magnetic.QuasiStatic.FluxTubes.Basic.LeakageWithCoefficient"},
                 {"c_usefulFlux"}, {"c_usefulFlux=0.7"}, true)
```

**Comment by HansOlsson** [comment]
> 
> 
> @beutlich What would the conversion then look like?
> 
> ```
> convertModifiers({"Modelica.Magnetic.FluxTubes.Basic.LeakageWithCoefficient",
>                   "Modelica.Magnetic.QuasiStatic.FluxTubes.Basic.LeakageWithCoefficient"},
>                  {"c_usefulFlux"}, {"c_usefulFlux=0.7"}, true)
> ```

As I understand it the modifier should be added even if there currently was no modifier, right?
In that case it would be (or without the last "true" - there is no reason to try to simplify this):

```
convertModifiers({"Modelica.Magnetic.FluxTubes.Basic.LeakageWithCoefficient",
                  "Modelica.Magnetic.QuasiStatic.FluxTubes.Basic.LeakageWithCoefficient"},
                  fill("",0), {"c_usefulFlux=0.7"}, true)
```
However, if there is already a modifier for `c_usefulFlux` the result is currently not specified.

**Comment by christiankral** [comment]
@HansOlsson Thanks a lot.

**Comment by HansOlsson** [comment]
> However, if there is already a modifier for c_usefulFlux the result is currently not specified.

Ooops. Wrong, it wasn't specified in 3.4 but it was added in https://github.com/modelica/ModelicaSpecification/pull/2409/
And as I understand it that works out also in this case.

**Comment by christiankral** [comment]
> > However, if there is already a modifier for c_usefulFlux the result is currently not specified.
> 
> Ooops. Wrong, it wasn't specified in 3.4 but it was added in [modelica/ModelicaSpecification#2409](https://github.com/modelica/ModelicaSpecification/pull/2409)
> And as I understand it that works out also in this case.

I tested the conversion 1a5d6c86c88fef9f28bbb3a455940a9d786875c4 with Dymola 2020 and it works OK.

**Pull request merged**
