### PR TITLE
Fix text in icons of sensors

### PR DESCRIPTION
**Pull request by christiankral**
This is a first attempt to get #2628 resolved. I did not yet touch `Modelica.Mechanics.MultiBody` and `Modelica.Fluid` as the library officers may do a much better job than I can make. I propose to go ahead with this PR and try to close it and then let the library officers of MultiBody and Fluid create additional PRs.

However, I tried to get all the sensors to look the same as much as possible. My PR is a massive change of the visual appearance. So suppose to checkout the branch https://github.com/christiankral/ModelicaStandardLibrary/tree/text_sensor and go through each of the packages indicated under Labels.

### CODE REVIEW

**Comment by christiankral** [comment]
@beutlich For a reason I do not understand there occurred some conflicts. Could you please have a look at these conflicts as I do not actually understand what their cause is...

**Comment by christiankral** [comment]
I will add some notes in the User's Guide of the MSL on the proper text icon design.

**Comment by beutlich** [comment]
> 
> 
> @beutlich For a reason I do not understand there occurred some conflicts. Could you please have a look at these conflicts as I do not actually understand what their cause is...

Should be good again now.

**Comment by christiankral** [comment]
> In Modelica.Magnetic.QuasiStatic.FluxTubes.Sensors.Transient.FundamentalWavePermabilitySensor, if both outputs have the same unit I'd prefer to have the unit in the circle as it was before.

image

The left output is `mur` with SI unit 1, and the right output is `mu` with SI unit H/m. I thought that unity quantity does not need an indication of `1`

**Comment by christiankral** [comment]
> You use `VA`, but also `N.m`. For consistency, should it be `V.A` (or `Nm`)?

I think it is good to have a consistent way of indicating units. I will therefore change `VA` to `V.A`

**Comment by maltelenz** [comment]
The images at the bottom of the documentation of `modelica://Modelica.UsersGuide.Conventions.Icons` do not show up. Maybe they have not been added yet?

The following have no spacing around the text, which makes them look cramped:
```
Modelica.Mechanics.Translational.Sensors.RelSpeedSensor
Modelica.Mechanics.Translational.Sensors.RelAccSensor
```
Apart from that, this looks good to me.

**Comment by christiankral** [comment]
In Dymola some SI units are not even rendered due to the small text size. I will thus change the design proposal and increase the text size for SI units of more than three characters.

**Comment by christiankral** [comment]
Give me a couple more minutes -- we can always roll back if required.

**Comment by maltelenz** [comment]
> In Dymola some SI units are not even rendered due to the small text size. I will thus change the design proposal and increase the text size for SI units of more than three characters.

Can you give an example? I'm curious how SystemModeler renders them.

**Comment by christiankral** [comment]
I did two measures:
1. I changed the text box format for longer texts of the RotationalSensor to improve readibility
2. I moved the pointer of the TranslationalSensor to the left to have more space available:

image

**Comment by christiankral** [comment]
> > In Dymola some SI units are not even rendered due to the small text size. I will thus change the design proposal and increase the text size for SI units of more than three characters.
> 
> Can you give an example? I'm curious how SystemModeler renders them.

Have a look at c786c9f

**Comment by christiankral** [comment]
Dymola renders the latest proposal of b8dfa02 as:

image

**Comment by maltelenz** [comment]
SystemModeler doesn't elide either of f22333f and b8dfa02. I think we might only elide tags (%name, %par, ...), and assume the library developer knows what they are doing for fixed length strings.

Although I prefer the smaller size, I'm fine with the new one as well.

**Comment by beutlich** [comment]
@christiankral Is this OK to get merged?

**Comment by christiankral** [comment]
@beutlich Yes, it can get merged

**Pull request merged**
