### PR TITLE
Corrected a bug in PowerConverters/DCAC/Control/SVPWM.mo

### PR DESCRIPTION
**Pull request by AHaumer**
I had to correct a bug in PowerConverters/DCAC/Control/SVPWM.mo.
Is it possible to backport the bugfix to maint/4.0.x and maint/3.2.3?

### CODE REVIEW

**Comment by beutlich** [comment]
> Is it possible to backport the bugfix to maint/4.0.x and maint/3.2.3?

Yes, we can do it. Butw ill wait for library officer's review first.

**Comment by JoeRiel** [comment]
The comment before the large if needs to be fixed: `t0/4 + ta/2 + tb/2 + t0/2 + tb/2 + t2/2 + t0/4`; the t2 should, I think, be replaced with tb.

**Comment by beutlich** [comment]
SVPWM was added by b1f2d29827d49a2284e3e671ec93170c5c57032f for MSL v3.2.3.

**Review by MartinOtter — APPROVED** [review]

**Review by christiankral — APPROVED** [review]
Looks OK

**Comment by christiankral** [comment]
@AHaumer I think it makes sense to add a literature reference to the calculation procedure

**Pull request merged**
