### PR TITLE
Add connectorSizing to StateGraph.PartialStep

### PR DESCRIPTION
**Pull request by beutlich**
Update StateGraph with the connectorSizing feature (of StateGraph2) to improve the modeling comfort in a Modelica editor.

A conversion is required since the default values for nIn and nOut needed to be adapted.

### CODE REVIEW

**Comment by beutlich** [comment]
> However, if we already have 'nIn=2' we should keep that - but the specification doesn't state how to handle that ambiguity.

Dymola raises a conversion warning and prefers the existing modifier.

**Comment by beutlich** [comment]
@HansOlsson OK for you after dealing with https://github.com/modelica/ModelicaSpecification/pull/2409?

@mwetter What iy your opinion? Thanks for your feedback/review.

**Comment by HansOlsson** [comment]
> @HansOlsson OK for you after dealing with modelica/ModelicaSpecification#2409?

Yes.

**Comment by beutlich** [comment]
@MartinOtter OK for you, too?

**Pull request merged**
