### PR TITLE
Removed obsolete images from Resources/Fluid

### PR DESCRIPTION
**Pull request by wischhusen**
Ref: #3339  Please merge

### CODE REVIEW

**Comment by dietmarw** [comment]
Sorry but this is a total mess. What is it you actually **wanted** to achieve here? 

If you have a look what this PR touches (https://github.com/modelica/ModelicaStandardLibrary/pull/3429/files) then you will understand that this does not work.

**Comment by wischhusen** [comment]
I see. Well only the last three commits are relevant.

**Comment by dietmarw** [comment]
OK let me see what I can do.

**Comment by wischhusen** [comment]
Thanks

**Comment by dietmarw** [comment]
@wischhusen I need some more info since you based your changes on a way outdated master. For the future, before doing any changes make sure that your master branch is up to date with what is in the main repository. 

So can you please comment on what you have done. As in did you only remove files or did you also update some references in some Modelica files?

**Comment by wischhusen** [comment]
I would be highly interested in a fool-proof step-by-step procedure ;-). I carried out Git Sync on my fork but that was obviously not enough. 

The changes have almost nothing to do with the Modelica code. I just removed png and eps files from the Resources folder as explained in #3339. And I removed a link to FD.png in the documentation of Dissipation package (top-level docu). This is the only change in the Modelica library that is relevant.

**Comment by dietmarw** [comment]
There are quite a lot of images that were missed it seems. So I'm going to do a different approach of removing first ALL images and then see what the OM document generator complains is missing.

**Comment by dietmarw** [comment]
So I've redone the removal. I can automatically check for images used in the documentation since the OM documentation generator complains about missing files. But for image files used as icons I could only check manually. So it would be good if @wischhusen could have a look especially a the icons to see if something is missing now or not.

**Comment by dietmarw** [comment]
Good catch. I removed that one now too.

**Pull request merged**
