### PR TITLE
Math asserts

### PR DESCRIPTION
**Pull request by HansOlsson**
Add assertions in example-functions so that we will detect if they fail.
Related to #4338 - but I don't see it as needed for release.

### CODE REVIEW

**Comment by HansOlsson** [comment]
It seems #4338 is seen as blocking for 4.1.0 release; thus this is needed.

**Review by casella — APPROVED** [review]
LGTM

**Comment by casella** [comment]
We can merge this on master anyway, I guess.

**Comment by HansOlsson** [comment]
> We can merge this on master anyway, I guess.

Yes. It just seems that CI-checks didn't complete.

**Comment by Esther-Devakirubai** [comment]
@casella Should this be backported to maint/4.1.x?

**Comment by casella** [comment]
Please do, this is necessary for proper regression testing. Thanks!

**Comment by Esther-Devakirubai** [comment]
Backported to maint/4.1.x by #4470

**Pull request merged**
