### PR TITLE
Fix mass flow rate calculation

### LINKED ISSUE #2770: Wrong mass flow rate calculation in Modelica.Fluid.Fittings.GenericResistances.VolumeFlowRate
The mass flow rate of volumeFlowRate is always zero if the pressure drop is a linear function of volume flow rate. 

The volume flow of is calculated by solving the quadric equation dp=a*V_flow^2+b*V_flow. This fails if a is zero. The actual problem is in Modelica.Fluid.Dissipation.PressureLoss.General.dp_volumeFlowRate_MFLOW:

1) a is silently replaced by max(a,Modelica.Constants.eps) (the same for b, but this is not an issue here)
2) The volume flow rate is calculated by (-b/(2*a) + ((b/(2*a))^2 + dp/a)^0.5   (I simplified a bit)
The point is, for small a the right term sqrt(X^2 + eps) --> X, and this leads to V_flow=0 if b>0. 

Proposed solution:
1) The replacement  a,b=max(Modelica.Constants.eps, abs(IN_con.a,b)) should be removed. Instead, for (a*a)<=0 the linear solution dp/b should be returned. This should be relevant only if a is given as a parameter. 
2) One should calculate only the solution with the greater absolute value with the formula above. In the case b>0 (which is the common case) this is the negative solution  
    x1= (-b/(2*a) - ((b/(2*a))^2 + dp/a)^0.5
The second root should be calculated by Vieta's formula
    x2 = c/a/x1
In the common case b>0 the second solution x2 is the physically meaningful.
I removed the regularized power function SmoothPower here only for simplicity of presentation. It should be kept in the actual code.

### PR DESCRIPTION
**Pull request by wischhusen**
Proposal for a fix of issue #2770.

Close #2770.

### CODE REVIEW

**Comment by beutlich** [comment]
@joergu Can you please confirm that this fixes the mass flow issue. Thanks.

**Comment by wischhusen** [comment]
@joergu Yes it does for either way of calculation.

**Comment by wischhusen** [comment]
[Issue2770Tester.zip](https://github.com/modelica/ModelicaStandardLibrary/files/2604538/Issue2770Tester.zip)

**Comment by wischhusen** [comment]
In that case please add a stop time to 2 seconds. Thank you.

**Comment by beutlich** [comment]
Will do.

**Comment by wischhusen** [comment]
The cancellation issue was not completely clear to me. 
@joergu Could you elaborate?

**Comment by joergu** [comment]
I would like to postpone to tomorrow. I have only limited access today.

**Comment by beutlich** [comment]
> I would like to postpone to tomorrow. I have only limited access today.

@joergu Any update on this?

**Comment by joergu** [comment]
Hi,
sorry for delay. I modified the Tester and include another proposal for solving the quadratic equation. You can test it with a=1e-5 and b=1e5. 
Compiling the model with 64bit (with mingw) this raises an error for me  during initialization, compiling with 32bit works fine. However, you can see the lack of numeric precision of the MSL implementation by plotting m_flow and m_flow2.  
Sorry, my browser seems to have major problems here. I send it by PM to Stefan.

**Comment by wischhusen** [comment]
Regularization fixed. Now without regularization function for a>0 and b>0. Linear contribution in function makes regularization with SmoothPower obsolete.

**Comment by beutlich** [comment]
When trying to resolve the merge conflict I noticed that the commit history of this PR is not clean, but rather broken. @wischhusen I cherry-picked your three relevant commits and pushed to a separate branch. Can you please confirm that https://github.com/modelica/ModelicaStandardLibrary/compare/b7123a80be5897e05e1e27d38d1aaf043b98fdf5...beutlich:issue2770 are the intended changes and nothing was forgotten? Please note that these changes are actucally different from the diff displayed at https://github.com/modelica/ModelicaStandardLibrary/pull/2782/files.

**Comment by beutlich** [comment]
@wischhusen Never mind the new merge conflict. I will wait for your comment and resolve the conflict afterwards.

**Comment by wischhusen** [comment]
Seems to be okay.

**Comment by beutlich** [comment]
> 
> 
> Seems to be okay.

Thanks for the confirmation.

@wischhusen Can you please add/share the modified tester that @joergu provided by mail? I'd like to add it to ModelicaTest.

**Comment by beutlich** [comment]
> I would suggest to add the commit of the test cases provided by @joergu to this pull request

Yes, this was my intention, too.

> Would be even good to have a minimal unit test that reproduces the error and the fix.

**Comment by beutlich** [comment]
> @wischhusen Can you please add/share the modified tester that @joergu provided by mail? I'd like to add it to ModelicaTest.

Reminder @wischhusen.

**Comment by wischhusen** [comment]
I hope it is the right version.
[Issue2770Tester2.zip](https://github.com/modelica/ModelicaStandardLibrary/files/3392073/Issue2770Tester2.zip)

**Comment by beutlich** [comment]
@wischhusen Are you going to update this PR?

**Comment by wischhusen** [comment]
I am still struggling with git. I pushed the changes to my fork:
wischhusen/Modelica-1

**Comment by beutlich** [comment]
> 
> 
> I am still struggling with git. I pushed the changes to my fork:
> wischhusen/Modelica-1

Do not see it. Did you already push?

**Comment by wischhusen** [comment]
https://github.com/wischhusen/Modelica-1/commits/master

I can see it here.

**Comment by beutlich** [comment]
> 
> 
> https://github.com/wischhusen/Modelica-1/commits/master
> 
> I can see it here.

Right. I thought Modelica-1 means a branch name, not a fork name and therefore I was looking at the wrong places.

Looking at at your recent commit https://github.com/wischhusen/Modelica-1/commit/cef50d338d94965aa208f1c6097128cc0b6df9ac, I do not find any change that is not already part of this PR. So what are you missing?

**Comment by beutlich** [comment]
@wischhusen  You pushed to your master, but it is completely behind:

> This branch is 3 commits ahead, 1792 commits behind modelica:master. 

See our [wiki](https://github.com/modelica/ModelicaStandardLibrary/wiki/References,-how-tos-and-tutorials-to-git) for how to sync again. Let me know when I can help.

**Comment by beutlich** [comment]
@wischhusen Since the discussion ceased again, can you please tell me what is missing in this PR?

@joergu OK for you to merge?

**Comment by wischhusen** [comment]
@beutlich You are right, everything is in place. For me the current version is fine.

**Pull request merged**
