### PR TITLE
Remove questionable comparison signals from ModelicaTest.Fluid.Dissipation.Verifications.HeatTransfer.HeatExchanger.kc_roundTube

### PR DESCRIPTION
**Pull request by beutlich**
#2969 is still apparent in the reference results of MSL v4.0.0-beta.2 created by Dymola 2020x. This pull request only removes the questionable comparison signals Nu[2] and Nu[3].

Generally, there is a floating-point overflow at simulation start time for Nu[3] in Modelica.Fluid.Dissipation.HeatTransfer.HeatExchanger.kc_roundTube_KC which is not covered. Therefore, either the test model  ModelicaTest.Fluid.Dissipation.Verifications.HeatTransfer.HeatExchanger.kc_roundTube or the called function Modelica.Fluid.Dissipation.HeatTransfer.HeatExchanger.kc_roundTube_KC need to be fixed.

### CODE REVIEW

**Comment by beutlich** [comment]
> What is the goal with this pull request?

The goal is to to remove the dubious signals as a first remedy (independent from the underlying library issue), such that the reference results (of MSL v3.2.3+build.4 and MSL v4.0.0) will no longer contain them.

**Comment by maltelenz** [comment]
In my opinion, the fact that there is an overflow makes all the results from the model questionable. I think we should wait/push for a comment from the library officer.

**Comment by beutlich** [comment]
How long shall we wait then? #2969 already is open for more than 9 months.

**Comment by maltelenz** [comment]
I realize that. One would hope the fact that the issue is raised in the context of an imminent release triggers some action.

If we cannot get the library officer to look at it, maybe the model needs to be removed completely, since it would have to be considered abandoned and broken.

**Comment by beutlich** [comment]
@maltelenz Yet OK for you to merge? We still have #2969 open once this PR gets merged.

**Comment by maltelenz** [comment]
> @maltelenz Yet OK for you to merge? We still have #2969 open once this PR gets merged.

I would prefer removing the model altogether. There is no point in generating any reference results if the model is obviously broken.

**Comment by beutlich** [comment]
OK, will create alternative PR instead.

**Pull request closed without merging**
