### PR TITLE
Add recommendation for styling of 'tab' and 'group' annotations

### PR DESCRIPTION
**Pull request by tobolar**

### CODE REVIEW

**Review by henrikt-ma — COMMENTED** [review]
The proposed recommendations look good to me.

**Review by beutlich — COMMENTED** [review]
Could you also add 2 or 3 good examples per tab and group. Thanks.

**Comment by tobolar** [comment]
Thinking about, maybe there could be one more 'tab' rule saying something like: 
- Use tabs if there are more then X parameters in the "general" dialog.

A rationale behind: 
1. It make no sense to collect all class parameters into tabs, and have no one in the "general" dialog.
2. Parameters shall be grouped in the "general" dialog first.

Question: what is X?

**Comment by HansOlsson** [comment]
> Thinking about, maybe there could be one more 'tab' rule saying something like:
> 
> * Use tabs if there are more then X parameters in the "general" dialog.
> 
> A rationale behind:
> 
> 1. It make no sense to collect all class parameters into tabs, and have no one in the "general" dialog.
> 2. Parameters shall be grouped in the "general" dialog first.
> 
> Question: what is X?

I don't think we need a strict number for that, but just a general rule of thumb like: "if the parameters are so many that it is difficult to get an overview" or "if the parameters cannot all fit on the screen".

Obviously there are cases where parameters are moved to Tabs even if that is not the case, in particular "Advanced"-tab.

**Comment by tobolar** [comment]
> I don't think we need a strict number for that, but just a general rule of thumb like: "if the parameters are so many that it is difficult to get an overview" or "if the parameters cannot all fit on the screen".

I agree with you.
My focus was esp. on the "general" tab. I dont like having this tab (nearly) empty.

So I will add "Try to group components or variables in the default "general" tab prior to defining a new tab."

**Comment by tobolar** [comment]
> I don't think we need a strict number for that, but just a general rule of thumb like: "if the parameters are so many that it is difficult to get an overview" or "if the parameters cannot all fit on the screen".

I agree with you.
My focus was esp. on the "general" tab. I dont like having this tab (nearly) empty when there are other tabs (which is not the case for MSL).

What about "Try to group components or variables in the default "general" tab first. But feel free to open a new tab it they are so many."

**Comment by tobolar** [comment]
> Could you also add 2 or 3 good examples per tab and group. Thanks.

@beutlich I would add one simple example. IMO having more examples would be too complex.

**Comment by beutlich** [comment]
> > Could you also add 2 or 3 good examples per tab and group. Thanks.
> 
> @beutlich I would add one simple example. IMO having more examples would be too complex.

Ah, I rather was thinking just about the names, not teh complete declaration.

**Comment by tobolar** [comment]
> Ah, I rather was thinking just about the names, not teh complete declaration.

Enhanced now.

**Review by hubertus65 — APPROVED** [review]

**Pull request merged**
