### PR TITLE
Use ellipses instead of arcs by lines in Mechanics.MultiBody.Forces

### PR DESCRIPTION
**Pull request by tobolar**
This is a free continuation of #3634. In the figure below are shown the four elements being touched at most.

iconsMBSforces0

### CODE REVIEW

**Review by beutlich — COMMENTED** [review]
Here's how it looks in SimulationX. Maybe you want to remove the white backgreound of BasicForce and BasicTorque as well.

grafik

**Review by christiankral — APPROVED** [review]
Looks good to me, when checking it in Dymola; an yes, removing the white background boxes is a good idea.

OpenModelica shows, however, the boundary lines of the ellipse segments:
image

**Review by maltelenz — APPROVED** [review]
Test model:
```
model ForcesEllipses
  Modelica.Mechanics.MultiBody.Forces.Force force1 annotation(Placement(visible = true, transformation(origin = {-110, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.ForceAndTorque forceAndTorque1 annotation(Placement(visible = true, transformation(origin = {-70, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.Internal.BasicTorque basicTorque1 annotation(Placement(visible = true, transformation(origin = {-30, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.Internal.BasicWorldTorque basicWorldTorque1 annotation(Placement(visible = true, transformation(origin = {-70, 10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.Torque torque1 annotation(Placement(visible = true, transformation(origin = {-110, 10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.WorldForceAndTorque forceAndTorque annotation(Placement(visible = true, transformation(origin = {-30, 10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.MultiBody.Forces.WorldTorque torque annotation(Placement(visible = true, transformation(origin = {10, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  annotation(Diagram(coordinateSystem(extent = {{-130, -10}, {30, 75}}, preserveAspectRatio = true, initialScale = 0.1, grid = {5, 5})), Icon(coordinateSystem(extent = {{-100, -100}, {100, 100}}, preserveAspectRatio = true, initialScale = 0.1, grid = {10, 10})));
end ForcesEllipses;
```

In System Modeler before:
image
After:
image

Clear improvement, thank you!

**Comment by tobolar** [comment]
> Maybe you want to remove the white backgreound of BasicForce and BasicTorque as well.

@beutlich Done in fb4de457a956efbf18f448a2a18be65b11fddb94.

> OpenModelica shows, however, the boundary lines of the ellipse segments.

@christiankral The feature is obviously missing or wrong implemented in OM for the ellipse's closure is set to `closure=EllipseClosure.None`. Please add an issue to OM if applicable: https://github.com/OpenModelica/OpenModelica/issues/new/choose

**Comment by christiankral** [comment]
Created [OM Trac ticket](https://trac.openmodelica.org/OpenModelica/ticket/6357#ticket)

**Pull request merged**
