### PR TITLE
Convert "HeatingResistor" to "Resistor" in Electrical.Analog

### PR DESCRIPTION
**Pull request by christiankral**
see #2899

### CODE REVIEW

**Comment by beutlich** [comment]
Do you want me to exclude the "invalid" commit on V.A?

**Comment by christiankral** [comment]
The conversion script proposed in https://github.com/modelica/ModelicaStandardLibrary/issues/2899#issuecomment-504384161 does not work in Dymola. I therefore changed it in https://github.com/modelica/ModelicaStandardLibrary/pull/2983/commits/c31d6a8c466de06a00ea0ea8d349eaa2caf33469 -- which triggers Dymola to convert `Issue2899` as intended. 

However, I do not understand why the performed change in https://github.com/modelica/ModelicaStandardLibrary/pull/2983/commits/c31d6a8c466de06a00ea0ea8d349eaa2caf33469 works, as this makes only sense to me if 

```modelica
convertElement("Modelica.Electrical.Analog.Basic.HeatingResistor",
               {"R_ref"},
               {"R"});
```

is performed **before**

```modelica
convertClass("Modelica.Electrical.Analog.Basic.HeatingResistor",
              "Modelica.Electrical.Analog.Basic.Resistor");
```

even though the two conversions are implemented in the conversion script in the opposite order.

@beutlich Can you please double check if the conversion script is correct?

**Comment by beutlich** [comment]
@christiankral Can only check in Dymola, too, which is the only kown tool to support conversion currently.

We could also rename R to R_ref in Resistor.

**Comment by beutlich** [comment]
Conversion of ModelicaTestConversion4.Electrical.Analog.Issue2899 works as expected.

**Comment by christiankral** [comment]
> Do you want me to exclude the "invalid" commit on V.A?

@beutlich My fault. I guess I shall "undo" the change, as the change is handled in #2982, correct

**Comment by beutlich** [comment]
Yes, you can do so.

**Comment by christiankral** [comment]
> Please update Modelica.Electrical.Analog.Examples.HeatingResistor to no longer use the HeatingResistor.

Thanks, first I thought about it then then I forgot about it... I will change the example.

**Comment by HansOlsson** [comment]
> The conversion script proposed in #2899 (comment) does not work in Dymola. I therefore changed it 
...
> is performed before

The script-commands don't convert models one by one, but they sort of create a conversion table that is then applied in one go  - and that's why the order doesn't matter.

**Pull request merged**
