### PR TITLE
Fix rotational adaptor icons

### PR DESCRIPTION
**Pull request by tobolar**
refs #2562

### CODE REVIEW

**Comment by tobolar** [comment]
Actually, my updates concern PR #2562 which already have been merged. There is no connection to #2569 except that the same components are affected. But the topic is different.

**Comment by StephanZiegler** [comment]
I added the rounded rectangular to the icon for consistency. Looks fine for me.

**Comment by tobolar** [comment]
The original idea was to only revert changes on the two adaptors. But having rectangle's border of double width is fine for consistency reasons.

@AHaumer and @StephanZiegler Please review again.

**Comment by tobolar** [comment]
I don't understand. On one side you have changed rectangle's border width in de2a8984d8a9a1da98e76ed7d870366c9ef5337f to be consistent with general adaptors but on the other side you want to change position of description strings in c302514b1a16a85adb327054108507ffec8574dd which in turn is absolutely inconsistent.

I have to stress again that the original idea of this PR was to only revert changes on the two adaptors. Not to experiment on new icons for them.

**Comment by StephanZiegler** [comment]
So maybe i got the meaning of this ticket wrong in the first place. 
Under "Fix" I understand repair/improve or in in this case "make it matching". I'm sorry if this is considered nitpicking, but my opinion is, if we put effort into if, we should do it properly.

Regarding your statement:

> ...but on the other side you want to change position of description strings in c302514 which in turn is absolutely inconsistent. 

In My tool (Dymola 2018FD01) this looks like this:
before:
adaptor_before

and after:
adaptor_after

So for me the the input/output names are aligned after the changes. In the first version the names are just spread over the icon, which is in my opinon not consistent with the other adaptors.
Does it look different on your tool?
Why do you consider it inconsistent? Is there any modeling or styling rule applying that i am not aware of?
Please clarify.

General question: if the changes should just be reverted, is a review required in the first place?

**Comment by dietmarw** [comment]
@StephanZiegler For icon design, the new MSL that we are working on has now a guideline. Check `Modelica.UsersGuide.Conventions.Icons` from master.

**Comment by tobolar** [comment]
@StephanZiegler Sorry, I was confused since supposed your commit is to this PR - but it is a separate one, isn't it? (I wonder this is even possible due to double review process.)

Your changes on description strings are fine, of course.

Nontheless I would perform your changes on my fork again and commit it on my own. Then you can review again.

**Comment by StephanZiegler** [comment]
@tobolar yes, sorry i pushed my changes wrongly. 
I wanted to wait for the result of this discussion before pushing and maybe causing even more confusion. 

Yes commit to your fork and i will review again.

**Comment by tobolar** [comment]
@StephanZiegler  GitHub is still a mystic thing for me.

**Comment by StephanZiegler** [comment]
Look fine on my end now.

**Comment by AHaumer** [comment]
I have no strong preference on the icons but I'd prefer to be able to distinguish the icon of the "old" adaptors and the "new" generic adaptors (in Mechanics.Rotational). And I would prefer to have a consistent look (maybe with domain-specific colours) in Electrical.Analog, Mechanics.Rotational, Mechanics.Translational and Thermal.HeatTransfer.

**Comment by tobolar** [comment]
@AHaumer IMHO this is the case now.

**Pull request merged**
