### PR TITLE
Fixed -Wundef warning by first checking if macro is defined

### PR DESCRIPTION
**Pull request by beutlich**
As reported by @seanm in https://github.com/tbeu/matio/pull/178.

### CODE REVIEW

**Review by sjoelund — APPROVED** [review]
This is OK. A bit unnecessary, but OK to be able to use -Wall.

**Review by HansOlsson — APPROVED** [review]
Ok, even if unnecessary as undefined potential macros are replaced by 0 here.

**Comment by beutlich** [comment]
@seanm OK for you to sign the CLA?

**Comment by seanm** [comment]
@beutlich sorry for the delayed response, I was on vacation until today. Oof that's a lot of work for such a triviality... I've never even heard of Modelica, I thought I was patching matio, but I guess that file is actually from your project.  Maybe it's easier if someone recreates the patch without my name associated...?

**Pull request merged**
