### PR TITLE
Make damper cage always present in SMEE_DOL example

### PR DESCRIPTION
**Pull request by christiankral**
See #2936

### CODE REVIEW

**Comment by beutlich** [comment]
@HansOlsson I requested your review here since I am not sure if the PR is enough to fix the issue.

**Comment by beutlich** [comment]
> The change does not suffice.

Thanks. That is what I suspected.

**Comment by christiankral** [comment]
What could the solution then be? Remove the variable `irRMS` referring to the conditional component?

**Comment by christiankral** [comment]
OK, I did not yet see https://github.com/modelica/ModelicaStandardLibrary/issues/2936#issuecomment-494300565
I will investigate this proposal

**Comment by christiankral** [comment]
https://github.com/modelica/ModelicaStandardLibrary/issues/2936#issuecomment-494300565 seems not be the solution, see https://github.com/modelica/ModelicaStandardLibrary/issues/2936#issuecomment-496002400

**Comment by AHaumer** [comment]
resolved by #2956

**Pull request closed without merging**
