### PR TITLE
Rotational and translational inverse speed dependent torque/force

### PR DESCRIPTION
**Pull request by AHaumer**
as well as test examples.
When teaching drives, we distinguish 4 different types of load:
1. crane / elevator: constant load 
2. calender / roller: linear speed dependency
3. pump / fan: quadratic speed dependency
4. machining: inverse speed dependency
1.-3. are available, 4. is missing.

### CODE REVIEW

**Review by beutlich — COMMENTED** [review]
For the new examples we would also require the approriate comparisonSignals.txt specifications.

**Comment by AHaumer** [comment]
Sorry I forgot them. Added them just now.

**Comment by beutlich** [comment]
@AHaumer The master branch will become 4.1.0 or 5.0.0 one day, not 4.0.1. See also [VersionManagement](https://doc.modelica.org/Modelica%204.0.0/Resources/helpDymola/Modelica_UsersGuide_ReleaseNotes.html#Modelica.UsersGuide.ReleaseNotes.VersionManagement).

**Review by dietmarw — APPROVED** [review]
Nice addition. Looks fine.

**Review by tobolar — APPROVED** [review]
Good job!
IMO the two examples shall rather be moved into ModelicaTest.Rotational (and Translational, resp.) But it's probably a matter of discussion.

**Pull request merged**
