### PR TITLE
Adds animated level on the icon layer of the OpenTank

### PR DESCRIPTION
**Pull request by dietmarw**
Basically implementing the same feature as already present in `Modelica.Fluid.Vessels.OpenTank`

### CODE REVIEW

**Comment by dietmarw** [comment]
@AHaumer and @christiankral Any chance to review this?

**Comment by dietmarw** [comment]
> Why is `preserveAspectRatio=false` in the proposal, whereas `Modelica.Fluid.Vessels.OpenTank` uses `preserveAspectRatio=true`?

The PR removes that annotation and does not set it to false. Default is true.

**Review by christiankral — APPROVED** [review]
OK then.

**Comment by TManikantan** [comment]
@AHaumer would you please review fix for this ticket? Please also let us know if additional info or summary would help you expedite the review.

**Comment by TManikantan** [comment]
@AHaumer would you please review the fix ?

**Review by hubertus65 — APPROVED** [review]

**Pull request merged**
