### PR TITLE
Split Mechanics.MultiBody into single files

### PR DESCRIPTION
**Pull request by tobolar**
refs #2975

### CODE REVIEW

**Comment by tobolar** [comment]
I checked:
- all classes saved in single files
- pedantic check of MultiBody in Dymola 2020x
- all examples simulates (no regression check)
- all test models in ModelicaTest.MultiBody simulates (no regression check)

**Comment by tobolar** [comment]
> I'll just put this on hold for now

I'm in favor of it. 
I would then prefer to wait with proceeding of other MultiBody-related issues till this PR is merged, to prevent possible conflicts.

**Comment by beutlich** [comment]
> 
> 
> I'll just put this on hold for now since I'm not sure we should introduce this change now after alpha has been tagged. I would like to get @beutlich 's opinion on this. After all it is a feature which helps the development but is not really important for the released version. So can be added right after 4.0.0 release is done.

Hm, @christiankral opened #3389 recently to get Electrical.Analog split for MSL 4.0.0. Thus, if we put it on hold for MultiBody we should also avoid it for Electrical.Analog.

**Comment by dietmarw** [comment]
Yes I personally would put this also on hold there so it does not interfere with the testing. But I leave that up to you @beutlich.

**Pull request merged**
