### PR TITLE
Fix Media.Air.MoistAir.{density_derX, s_pTX, s_pTX_der}

### LINKED ISSUE #2868: Modelica.Media.Air.MoistAir.density_derX is not right
I think that the current algorithms of Modelica.Media.Air.MoistAir.density_derX,
```
dddX[Water] := pressure(state)*(steam.R - dryair.R)/((steam.R - dryair.R)
  *state.X[Water]*temperature(state) + dryair.R*temperature(state))^2;
dddX[Air] := pressure(state)*(dryair.R - steam.R)/((dryair.R - steam.R)*
  state.X[Air]*temperature(state) + steam.R*temperature(state))^2;
```
are not right.  

**Unit check**

Mass fraction X [kg/kg] is unitless.
The unit of density_derX should be same as density.
But the unit of abouve equations are,
`pressure*R/(R*temperature)^2 = pressure/(R*temperature^2) = density/temperature.
`
     where, `density = pressure/(R*temperature)`   is equation of state for ideal gases.

 **my derivation**
```
density = p/(R*T)
=>
d(density)/dX = - p/(R^2*T) * dR/dX = {-p*(dR/dX)} / (R^2*T)  --- (a)
```
(1) dddX[Water]

```
R = steam.R*X[Water] + dryair.R*(1-X[Water]) 
   = (steam.R - dryair.R)*X[Water] + dryair.R 

dR/dX[Water] = steam.R - dryair.R

numerator of (a) = -p*(dR/dX) = - pressure(state)*(steam.R - dryair.R)
denominator of (a) = R^2*T 
   = ((steam.R - dryair.R)*X[Water] + dryair.R)^2*temperature(state)

dddX[Water] = - pressure(state)*(steam.R - dryair.R)/
    ( ((steam.R - dryair.R)*X[Water] + dryair.R)^2 * temperature(state))
```

(2) dddX[Air]
```
R = steam.R*(1-X[Air]) + dryair.R*X[Air]
  = steam.R + (dryair.R - steam.R)*X[Air]

dR/dX[Air] = dryair.R - steam.R

numerator of (*) = -p*(dR/dX) = - pressure(state)*(dryair.R - steam.R)
denominator of (*) = R^2*T
   = (steam.R + (dryair.R - steam.R)*X[Air])^2 * temperature(state)

dddX[Air] = - pressure(state)*(dryair.R - steam.R)/
              ( (steam.R + (dryair.R - steam.R)*X[Air])^2 * temperature(state) )
```

### LINKED ISSUE #2872: Mistake of the sign of a term in Modelica.Media.Air.MoistAir.s_pTX
Algorithm of s_pTX

```
  algorithm
    s := Modelica.Media.IdealGases.Common.Functions.s0_Tlow(dryair, T)*(1 - X[
      Water]) + Modelica.Media.IdealGases.Common.Functions.s0_Tlow(steam, T)*
      X[Water] - Modelica.Constants.R*(Utilities.smoothMax(
          X[Water]/MMX[Water]*Modelica.Math.log(max(Y[Water], Modelica.Constants.eps)
        *p/reference_p),
          0.0,
          1e-9) - Utilities.smoothMax(
          (1 - X[Water])/MMX[Air]*Modelica.Math.log(max(Y[Air], Modelica.Constants.eps)
        *p/reference_p),
          0.0,
          1e-9));
```

I think that the 8th line of above,
```
       1e-9) - Utilities.smoothMax(
```
should be replaced to
```
       1e-9) + Utilities.smoothMax(
```

I modified the format of above algorithm. This is the sign of the 14th line of bellow.
-R is already multiplied in the 6th line.
```
algorithm
  s := Modelica.Media.IdealGases.Common.Functions.s0_Tlow(dryair, T)
         *(1 - X[Water])
     + Modelica.Media.IdealGases.Common.Functions.s0_Tlow(steam, T)
         *X[Water]
     - Modelica.Constants.R*
       (
          Utilities.smoothMax(
            X[Water]/MMX[Water]
              *Modelica.Math.log(max(Y[Water], Modelica.Constants.eps)*p/reference_p),
            0.0,
            1e-9
            ) 
        + Utilities.smoothMax(
            (1 - X[Water])/MMX[Air]
               *Modelica.Math.log(max(Y[Air], Modelica.Constants.eps)*p/reference_p),
            0.0,
            1e-9
            )
       );
```

### LINKED ISSUE #2874: Modelia.Media.Air.MoistAir.s_pTX_der is not right
[s_pTX_der.pdf](https://github.com/modelica/ModelicaStandardLibrary/files/3035944/s_pTX_der.pdf)

I think MoistAir.s_pTX_der is not right.
Please see above PDF.

### PR DESCRIPTION
**Pull request by wischhusen**
Corrected issues #2874 #2872 #2868 as elaborated by the reporter.

Fix #2868 (density_derX), fix #2872 (s_pTX) and fix #2874 (s_pTX_der).

### CODE REVIEW

**Comment by sjoelund** [comment]
This also changes the license back to ModelicaLicense2, and has conflicts...

**Comment by beutlich** [comment]
This PR is not clean. I will resolve the merge conflicts later.

**Comment by thorade** [comment]
Regarding content, maybe #2870 could also be addressed with this?

**Comment by beutlich** [comment]
> 
> 
> Regarding content, maybe #2870 could also be addressed with this?

Hm, I opened #2919 to fix #2870.

**Comment by beutlich** [comment]
@hubertus65 @casella Please review.
@wischhusen I hope I caught all the relevant changes.
@finback-at @thorade FYI

**Comment by beutlich** [comment]
> In fact, we may write such a test model for a generic medium, and then extend it to test all the media we have in the Modelica.Media library.

@hubertus65 @thorade @hubertus65 Since increasing the test coverage and overall library quality is one of our development goals it might be beneficial if you could provide such tests. @thorade's test model from https://github.com/modelica/ModelicaStandardLibrary/issues/2870#issuecomment-490965895 might be used as starting idea. Thank you!

**Comment by beutlich** [comment]
@finback-at Any chance for your review on the three addressed issues? Thanks!

**Comment by beutlich** [comment]
@thorade OK for you now?

**Comment by thorade** [comment]
Sure, I only looked at it before you fixed whitespace.

**Pull request merged**
