### PR TITLE
Implement translational driving resistance

### PR DESCRIPTION
**Pull request by AHaumer**
reopened PR (previously PR #2942) for isssue #2940.
I messed up my fork - sorry.
I closed PR 2942, deleted my fork, forked newly, branched and this new PR.

### CODE REVIEW

**Comment by tobolar** [comment]
I have several isses concerning the model (e.g. icon, parameter names, documentation) but it is more feasible to me to do all in a sequence of commits to this PR instead of listing them all in a comment.

**Comment by AHaumer** [comment]
Some comments to @tobolar 's changes:
- Make use of import-clause import SI = Modelica.SIunits; 
I dislike this style: Hard to read for newbies, hard to handle if you copy code snippets out of the model.
What's the disadvantage of using fully qualified Modelica.SIunits.xxx?
- Renaming vRel to vAir:
vAir sound like "velocity of air" - that's misleading, could get mixed up with wind speed.
vRel is much clearer = relative velocity of vehicle with respect to surrounding air.
- "velocity" or "speed" - ok for me.

**Comment by tobolar** [comment]
@AHaumer 

- Concerning import-clause import SI = Modelica.SIunits; - this is used overall in Modelica.Mechanics, so I simply used that style. I agree with your arguments but would prefer to be consistent at the moment.
- Renaming vRel to vAir: I used variable name and description (Resultant air velocity) as used in [Road and Off-Road Vehicle System Dynamics Handbook](https://www.crcpress.com/Road-and-Off-Road-Vehicle-System-Dynamics-Handbook/Mastinu-Ploechl/p/book/9781138075290). I guess it also corresponds to measurements in a wind tunnel with vehicle at standstill.
  In the original description of the parameter ("Relative velocity") it was unclear to which reference this relates. But using "relative velocity of vehicle with respect to surrounding air" sounds well. I will revert the change.
- "velocity" or "speed" - both is used within the library but I prefer "velocity".

Thanks!

**Comment by tobolar** [comment]
@AHaumer 
1. I have yet another issue concerning vRel. Actually, it shall be given by a _negative_ vehicle velocity and the velocity of ambient wind. This would result in the negative fDrag which we could consider being right since really working against positive velocity of `frame`. Consequently, both forces fRoll and fGrav shall be negative as well. This shall be in accordance with the sign conventions described in `Modelica.Mechanics.Translational.UsersGuide.SignConventions`.
2. I would suggest to use parameters `m` and `g` instead of `Fn`, with `g` having default value of 9.81. This corrsponds to the model's documentation and could be easier for the user.
3. Regarding suggestions in #2931 (which still is a matter of discussion but this rule is indeed mostly followed in `Modelica.Mechanics.Translational`), there shall be `_` to separate indices from variables. Therefore, there shall be `c_r`, `c_w`, `c_rConstant` (or `c_r_constant`), `v_reg`, etc.
4. How to spell `usecrInput`? It looks awesome. `useCrInput` or `use_crInput` could be better.

**Comment by AHaumer** [comment]
@tobolar 

1. The velocity of wind is counted positive in the positive direction of vehicel movement. v - vWind is the relative velocity of the vehicle with respect to the air. Case v > vWind results in a positive fDrag. Reverting both vehicle velocity and wind velocity, we get negative fDrag. All resistances fDrag, fRoll and fGrav are counted positive if they're acting against the vehicle's movement. Applying these to the connector i.e. flange.f = fDrag + fRoll + fGrav is just the right action. If you would like to revert the sign of all three forces, you'll have to write flange.f = -fDrag - fRoll - fGrav. I prefer the solution as it is implemented.

2. No! I discussed this with @christiankral In a vehicle model, you'll have to propagate the mass twice (to the mass and the drivingResistance). This will cause a lot of mistakes - forget to propagate the mass to both components. If we use Fn, the user has to think "How large is Fn?" and he won't forget to use the right mass twice. BTW, using m and g, we should use Modelica.Constants.g_n as default for g instead of 9.81

3. If you prefer this style - fine for me (although c_w looks ugly whereas cw is recognized by nearly everyone).

4. This was requested by @beutlich I admit it looks ugly. What are the conventions? If we assemble a name from different parts we normally use CamelCase instead of underscore (which denotes subscripts). There we would have to write useCrInput (which looks ugly, too).

5. The icon is fine for me.

**Comment by otronarp** [comment]
> 2. No! I discussed this with @christiankral In a vehicle model, you'll have to propagate the mass twice (to the mass and the drivingResistance). This will cause a lot of mistakes - forget to propagate the mass to both components. If we use Fn, the user has to think "How large is Fn?" and he won't forget to use the right mass twice. BTW, using m and g, we should use Modelica.Constants.g_n as default for g instead of 9.81

I really don't see how hiding the mass inside Fn makes it more clear that you need to propagate the mass twice, to me it sounds more like it would have the opposite effect and making it less obvious.

**Comment by HansOlsson** [comment]
> I really don't see how hiding the mass inside Fn makes it more clear that you need to propagate the mass twice, to me it sounds more like it would have the opposite effect and making it less obvious.

I would also think so. 

But just so we are clear: the Vehicle1D model already propagates the mass twice (once to another mass and once to Fn), it's just that if the user would build something similar they would need to do the same.

However, when thinking I got a similar conclusion as @tobolar 
> I would suggest to use parameters m and g instead of Fn, with g having default value of 9.81. 

And if the user wants to change the 'g' of the driving resistance that becomes messier if they have to change 'Fn'. One alternative is that the driving resistance model has three parameters:
m, g, and Fn=m*g, where 'm' and 'g' are only used in that formula in that model.

**Comment by AHaumer** [comment]
In a discussion with @christiankral thequestion came up:
Why not implement a simple model of a whole vehicle (including mass and wheel(s)), utilizing already implemented sources for the driving resistances (with some small backwards compatible enhancements)? You'll see rather clearly not only the driving resistances but the force needed for acceleration or braking, too.
I'll create an alternative PR during the weekend.

**Comment by AHaumer** [comment]
I#d prefer PR #2963 (simple vehicle model) instead of this PR (driving resistance).

**Comment by AHaumer** [comment]
closed in favour of #2963

**Pull request closed without merging**
