### PR TITLE
Rebuild binaries for Windows (MSVC, TDM-GCC) and Linux (GCC)

### LINKED ISSUE #4178: Recompilation of binaries necessary
In the master branch e.g. commit ce36c07 examples which include a CombiTimeTable are not compiling, because the function
ModelicaStandardTables_CombiTimeTable_init3
can not be found in the binaries. The function was added to ModelicaStandardTables.c after the last built of the binaries. 
So a recompilation of the binaries for all platforms is necessary.

### PR DESCRIPTION
**Pull request by beutlich**
I rebuilt the binaries using

* MSVC VS 2005
* GCC (TDM64-1) 5.1.0
* Linux GCC 4.8.5

to fix #4178.

### CODE REVIEW

**Comment by beutlich** [comment]
Should probably wait for #3700.

**Review by casella — COMMENTED** [review]
@beutlich, the versions of the compilers that you used to build the binaries are really old. Is that done on purpose? Do we have established guidelines to produce those binaries?

Thanks!

**Comment by beutlich** [comment]
> Is that done on purpose?

Of course. (I even purchased VS 2005 (on MA budget) for that reason ;-)). The reason is, that all newer compilers are still object compatible to these old static libraries, i.e., they can link them w/o caring on C runtime issues. And as it worked out the last years: Never change an old compiler.

**Comment by HansOlsson** [comment]
> > Is that done on purpose?
> 
> Of course. (I even purchased VS 2005 (on MA budget) for that reason ;-)). The reason is, that all newer compilers are still object compatible to these old static libraries, i.e., they can link them w/o caring on C runtime issues. And as it worked out the last years: Never change an old compiler.

Yes, for C with at least two potential problems regarding the C runtime if linking with a newer compiler:
- Don't directly use `stdio`, `stdout`, and `stderr` between different compiler versions (VS 2015 was the breaking change). You can use `printf`, `scanf`, `getchar` etc; it's just the names `stdio`, `stdout`, and `stderr` that shouldn't be used.
- Don't use macros to access the locale data-structure generated by a different compiler version. VS 2012 was the breaking change as far as I recall.

**Comment by beutlich** [comment]
> Should probably wait for #3700.

This one is merged.

Still waiting for #4274 before rebuilding again.

**Comment by beutlich** [comment]
> Still waiting for #4274 before rebuilding again.

Rebuilt with all desired PRs merged.

**Comment by beutlich** [comment]
While this is not yet reviewed/merged we can wait for #4278.

**Comment by HansOlsson** [comment]
> While this is not yet reviewed/merged we can wait for #4278.

I will wait with reviewing until that is ready (and will then check that the libraries link etc).

**Comment by maltelenz** [comment]
I also want to bring up the alternative to just not have binaries in the repository. I strongly prefer that.

In general, I find it is a bad idea to have build products checked in into source repositories, because of reasons probably clear (often out of date, bloating the repository size, ...).

I expect all tool vendors build their own binaries anyway.

For CI, we need to build binaries for each run anyway, or the CI results will not mean much, since they will not match what is in the repository (when the external source changes).

The new CMake project proposal should help with CI efforts: #4265

If we want to provide binaries for users that don't want to use a tool-shipped version (even though you would expect it to be somewhat broken), maybe binaries could be built as part of the release process and included in the release zip file?

**Comment by HansOlsson** [comment]
> I also want to bring up the alternative to just not have binaries in the repository. I strongly prefer that.
> 
> In general, I find it is a bad idea to have build products checked in into source repositories, because of reasons probably clear (often out of date, bloating the repository size, ...).

I generally agree (with some exceptions that don't apply here).

However, the problem is that we also want to test 4.1.0 before it is released, and without the binaries some testers will have a problem with that (as we have seen very clearly) - so I'm not sure if changing the process now is a good idea.

I can see two possibilities:
- Get CMake etc to work perfectly
- Have one (or more) down-stream branch/repo with the binaries (and possibly other things needed for testers).

**Comment by maltelenz** [comment]
Maybe @GallLeo can comment on what they need for their regression test runs, and what they think of the procedure proposed by @beutlich [here](https://github.com/modelica/ModelicaStandardLibrary/pull/4265#issuecomment-1894511463).

**Comment by beutlich** [comment]
CI is the way to go: Have push and PR triggered action to build the binaries and keep the artifacts.

**Review by HansOlsson — APPROVED** [review]
Looking good.
I noticed two unrelated issues - will open PR for that.

**Comment by GallLeo** [comment]
For our regression test server, we manually built from source. 
Last week, according to #4265.

I.e. we either have to automize the compiler call on our side or use the built artifacts from Github CI.
I think, only having binaries available for release builds (zip) is not enough.

**Review by GallLeo — APPROVED** [review]
As we sucessfully ran nightly tests with the same source base, I assume these binaries are fine, as well.

**Comment by maltelenz** [comment]
> For our regression test server, we manually built from source. 
> Last week, according to #4265.
> 
> I.e. we either have to automize the compiler call on our side or use the built artifacts from Github CI.

I think this should be the way forward, for the reasons already brought up earlier in this thread.

However, if accepting new binaries in the repo for now will help with moving the 4.1.0 forward more smoothly, I don't mind. 

Maybe we can remove the binaries on master to make clear that we don't want binaries in the repo going forward? I'd be happy to provide such a pull request.

**Comment by beutlich** [comment]
> I'd be happy to provide such a pull request.

Yes, please go ahead.

**Comment by beutlich** [comment]
> Last week, according to #4265.

@GallLeo I'd appreciate to get your/LTX review on that #4265 PR. Thanks.

**Comment by beutlich** [comment]
Waiting for #4345 to be merged.

**Comment by beutlich** [comment]
Rebased and rebuilt once again.

**Comment by beutlich** [comment]
@HansOlsson Note, that we do not need to wait for #4302 (since ModelicaInternal.c is compiled for libModelicaExternalC).

**Comment by beutlich** [comment]
As stated in #4347, there is no need to have the binaries in the repo - as long as they are part of the released asset. (Unfortunately this was not the case for the lastest pre-relases https://github.com/modelica/ModelicaStandardLibrary/releases/download/v4.1.0-alpha.1/ModelicaStandardLibrary_v4.1.0-alpha.1.zip or https://github.com/modelica/ModelicaStandardLibrary/releases/download/v4.1.0-beta.1/ModelicaStandardLibrary_v4.1.0-beta.1.zip.)

**Comment by HansOlsson** [comment]
> As stated in #4347, there is no need to have the binaries in the repo - as long as they are part of the released asset. (Unfortunately this was not the case for the lastest pre-relases https://github.com/modelica/ModelicaStandardLibrary/releases/download/v4.1.0-alpha.1/ModelicaStandardLibrary_v4.1.0-alpha.1.zip or https://github.com/modelica/ModelicaStandardLibrary/releases/download/v4.1.0-beta.1/ModelicaStandardLibrary_v4.1.0-beta.1.zip.)

Ok, but the logic would be that we remove the libraries at some point in the future - as long as they exist they should be up-to-date.

**Comment by Harisankar-Allimangalath** [comment]
@casella @GallLeo @HansOlsson we have to merge this to the master also right , or is it already updated in the master ? 

just for understanding , Thankyou

**Comment by beutlich** [comment]
No, this is not meant for bringing to master, see #4347.

**Comment by casella** [comment]
@Harisankar-Allimangalath we'll need to sort out the binary issue for 4.2.0, but that will be after the 4.1.0 release.

**Pull request merged**
