### PR TITLE
Update icon color of red dot

### LINKED ISSUE #3567: Modelica icon color
The Modelica library icon layer has a red dot, but the red color was changed in the recent update of the official Modelica icons. The color of the icon is now RGB(200, 16, 46).

### PR DESCRIPTION
**Pull request by beutlich**
Resolves #3567 as suggested by @DagBruck .

### CODE REVIEW

**Review by DagBruck — APPROVED** [review]

**Review by HansOlsson — APPROVED** [review]
Looks good.

I understand the discussion about darkness of the grey is related to the size - as soon as you are down to pixels then fuzziness and anti-aliasing(?) will blend it with other pixels making it effectively lighter so you have to make it darker to compensate.
The red dot is big enough that it doesn't matter.

In general designing small scale graphics is challenging: I was going to write that a more radical change is for repeated items to replace them with fewer "larger" ones, e.g., the number of ball bounces. I then realized that the logo sort of already does that: in the large logo we have a long arc going through the 'o' - that is gone in the icon.

**Comment by Harisankar-Allimangalath** [comment]
@casella do you have any suggestions towards this changes , if not I shall merge it . 

Thankyou

**Comment by Harisankar-Allimangalath** [comment]
@beutlich do you have any suggestion on this ?

**Comment by beutlich** [comment]
> @beutlich do you have any suggestion on this ?

@casella (being assigned) is the one to take over.

**Comment by Harisankar-Allimangalath** [comment]
I am backporting this to maintenance branch ,

**Pull request merged**
