### PR TITLE
Added comparison signals for DynamicPipeEnergyConservationCheck  / DynamicPipeEnergyConservationCheck2

### PR DESCRIPTION
**Pull request by casella**
Added missing comparison signals for DynamicPipeEnergyConservationCheck and DynamicPipeEnergyConservationCheck2. Since the goal of the model is to check energy balance by comparing boundary enthalpies, I only added those values to the comparison signals.

Contributes resolving #4349.

### CODE REVIEW

**Review by arunkumar-narasimhan — APPROVED** [review]

**Review by maltelenz — APPROVED** [review]
Can at least confirm that the models do contain all listed variables.

**Review by HansOlsson — APPROVED** [review]

**Comment by Esther-Devakirubai** [comment]
@casella Can this be backported to Maint/4.1.0?

**Comment by casella** [comment]
> @casella Can this be backported to Maint/4.1.0?

Please do and report in #4349. Thanks!

**Comment by Esther-Devakirubai** [comment]
Backporting this to maintenance branch by #4450

**Pull request merged**
