### PR TITLE
Improve wording of electrical and magnetic connector descriptions

### PR DESCRIPTION
**Pull request by christiankral**
The changes are based on the discussion of #2560. Due to the added and improved doc strings of the connectors, the examples of the MSL (and other user libraries) are much better to understand. The tooltips associated with the connectors now show a much more complete and accurate description of the connectors.

### CODE REVIEW

**Comment by dietmarw** [comment]
@christiankral Please be careful in future and do **not** create branches at modelica/ModelicaStandardLibrary but your fork.

**Comment by christiankral** [comment]
@dietmarw OK, the Modelica branch is a result of syncing the upstream repository -- sorry. When pushing the branch the git interface proposed to apply `git push --set-upstream origin wording-interfaces-3.2.3` which is apparently not what I should have done. How can I then only push it to my (synced) fork? Do you know what the command git is?

**Comment by christiankral** [comment]
I hope the wording is fine now: also added "quasi-static" to the User's Guide spelling section.

**Comment by dietmarw** [comment]
The only other alternative is that you create a new PR based on your branch and we close this one. But I would prefer you pushing just that last commit.

**Comment by christiankral** [comment]
@dietmarw You're right; my fault. It is now pushed upstream to modelica/ModelicaStandardLibrary.

**Comment by AHaumer** [comment]
Just to clarify some questions:
I'm not convinced that polyphase is the better term than multiphase. I guess both terms are used in English literature.
Regarding plug and pin: pin is a single phase electric connector, plug is a multi-/poly-phase connector containing m pins. 
Regarding the wording: I have no strong preference whether to use an article (the) or not. 
When we're talking about a potential (remember, a potential variable can ONLY be a potential quantity, not a potential difference!) I would use "at the connector". For a flow variable I would use "into the connector" (from outside).

**Comment by dietmarw** [comment]
We already had a discussion on polyphase vs multiphase in #1865 were you @AHaumer also agreed. So we should stick to polyphase.

**Comment by tobolar** [comment]
> Moreover, there is "electrical pin" but "electric plug".

I wanted to stress _electrical_ against _electric_ in that review, but found no possibility to highlight it by text format - obviously no such possibility in review window.
> Regarding the wording: I have no strong preference whether to use an article (the) or not.

I rather mean general usage of articles in description strings within whole MSL. I guess they are generally not used.

**Comment by christiankral** [comment]
OK, changed "electric" to "electrical" in the connector descriptions. 

Please note, that the terms are not yet entirely changed throughout all libraries. I just wanted to improve the wording of the connectors, so far. I will continue on the unification later.

**Pull request merged**
