### PR TITLE
Rename HeatingNPN_OrGate to HeatingNPN_NORGate

### LINKED ISSUE #2521: Wrong name of example Modelica.Electrical.Analog.Examples.HeatingNPN_OrGate
The name of the example HeatingNPN-OrGate is wrong since the circuit in that example is a NOR circuit.
Unfortunatelly changing the name would break backwards compatibility. Therefore we need to wait for the next major release to change the name.

### PR DESCRIPTION
**Pull request by beutlich**
Close #2521.

### CODE REVIEW

**Comment by christiankral** [comment]
I am actually wondering why we need both the models `Modelica.Electrical.Analog.Semiconductors.HeatingNPN` and `Modelica.Electrical.Analog.Semiconductors.NPN`, as they both have a heat port. @christophclauss I suppose the underlying physical model is the same. 

Having components with `Heating` in their name are usually a leftover from the time when components were designed without heat port. Afterwards, the `Heating` components were add to the MSL. Later, step by step, the heat ports were added in a backwards compatible way. Therefore, we may consider removing all these `Heating` components from the MSL.

**Comment by dietmarw** [comment]
I agree. All those Heating* models that have been now included in the * themselves should be removed (and usages converted).

**Comment by beutlich** [comment]
> Therefore, we may consider removing all these Heating components from the MSL.

Can you please create a separate issue for that. This one is just on the example renaming.

**Comment by christiankral** [comment]
#2899 is intended to remove the name `Heating` from obsolete models and examples

**Comment by beutlich** [comment]
> It looks like the conversion script entry is missing

Since it is not required for example models.

**Pull request merged**
