### PR TITLE
Remove ModelicaUtilities.h from MSL distribution

### LINKED ISSUE #3867: Is ModelicaUtilities.h tool-specific?
ModelicaUtilities.h is mentioned in the language specification, [Sect. 12.9.6](https://specification.modelica.org/maint/3.5/functions.html#utility-functions), and available in [Modelica/Resources /C-Sources](https://github.com/modelica/ModelicaStandardLibrary/tree/master/Modelica/Resources/C-Sources).

Is it expected to be customized by each tool vendor, or should it be left as on the MA repo?

What is the recommended way to #include it in a .c source code file within a certain library's Resources directory?

### PR DESCRIPTION
**Pull request by beutlich**
ModelicaUtilities.h is ought to be distributed by Modelica tools and no longer by the MSL.

Closes #3867.

### CODE REVIEW

**Review by sjoelund — APPROVED** [review]

**Comment by sjoelund** [comment]
Just need to fix the CI jobs

**Comment by beutlich** [comment]
> 
> 
> Just need to fix the CI jobs

Can you please tell me how to configure the include directory in https://github.com/modelica/ModelicaStandardLibrary/blob/364a7f372da8f566e15a76f6b014ba342b75c8cb/.github/workflows/checkCI.yml#L19-L20

Thanks.

**Comment by sjoelund** [comment]
> > Just need to fix the CI jobs
> 
> Can you please tell me how to configure the include directory in
> 
> https://github.com/modelica/ModelicaStandardLibrary/blob/364a7f372da8f566e15a76f6b014ba342b75c8cb/.github/workflows/checkCI.yml#L19-L20
> 
> Thanks.

`./configure ... CPPFLAGS="..."` (a bit busy in the conference)

**Review by henrikt-ma — COMMENTED** [review]
Looks like this is mostly affecting CI, which I don't know much about.  I'm just a bit surprised that the file is kept at all – isn't the intention that also CI should have access to a Modelica tool environment when building the libs?

**Comment by beutlich** [comment]
Current CI is tool-invariant. It only is some unit tests without the requirement to have a Modelica tool available.

**Comment by sjoelund** [comment]
> Looks like this is mostly affecting CI, which I don't know much about. I'm just a bit surprised that the file is kept at all – isn't the intention that also CI should have access to a Modelica tool environment when building the libs?

It could be done that way, but I think it's easier to just keep a small header in the CI.

**Comment by beutlich** [comment]
> 
> 
> Looks like this is mostly affecting CI, which I don't know much about. I'm just a bit surprised that the file is kept at all – 

Only in the repository (for CI reasons), but no longer in the MSL distribution.

> isn't the intention that also CI should have access to a Modelica tool environment when building the libs?

Current CI is tool-invariant. It only is some unit tests without the requirement to have a Modelica tool available.

**Comment by beutlich** [comment]
@sjoelund Maybe you can fix teh Jenkinsfile since I do not know how you like the fix, in `allAutotools`, `autotools` or each caller?

**Comment by beutlich** [comment]
Reminder for me to fix the conficts of #3686 afterwards.

**Review by henrikt-ma — APPROVED** [review]
> > isn't the intention that also CI should have access to a Modelica tool environment when building the libs?
> 
> Current CI is tool-invariant. It only is some unit tests without the requirement to have a Modelica tool available.

OK, it seems like one could consider the CI its own Modelica tool environment in this case, so having a non-distributed copy of the file for this purpose makes sense.

**Comment by beutlich** [comment]
Will change the VS project again to take the ModelicaUtilities.h from an environment variable `MODELICA_UTILITIES_INC`.

**Comment by beutlich** [comment]
@sjoelund I introduced environment variable `MODELICA_UTILITIES_INCLUDE` in the build scripts. Can you please review again, especially configure.ac. Thanks.

**Review by sjoelund — CHANGES_REQUESTED** [review]
I don't see the value of using your own environment variable when there is an established standard for CPPFLAGS (for make, cmake and configure scripts). I could see the point for vcproj though. It could perhaps be used as a fallback if configure or cmake do not find the header (less easy to detect for makefiles)

**Comment by beutlich** [comment]
OK, only for VS then. Will do

**Comment by beutlich** [comment]
The issue I see with BuildProjects/gcc/Makefile is that you now need to set ``make CPPFLAGS="-DNDEBUG -DHAVE_UNISTD_H -DHAVE_STDARG_H -DHAVE_HIDDEN -DHAVE_MEMCPY -Ipath/to/ModelicaUtilitiesHeader"` on the command line as there is no append on the CPPFLAGS.

**Comment by beutlich** [comment]
> 
> 
> Reminder for me to fix the conficts of #3686 afterwards.

Done.

**Pull request merged**
