### PR TITLE
Utilize PressureSlope unit in Media consistently

### PR DESCRIPTION
**Pull request by beutlich**
This is a follow-up of the recently merged PRs #4115 (adding unit "Pa/s") and #4103 (introducing a new type PressureRate with unit "Pa/s").

### CODE REVIEW

**Review by maltelenz — APPROVED** [review]
Looks good to me.

**Comment by HansOlsson** [comment]
Based on #4236 shouldn't it be PressureSlope instead of PressureRate?

That would make it Pressure and Temperature more consistent.
Based on #4236 FlowRate is for connector variables, whereas Slope is for derivatives, (and plain Rate is used for completely different things).

**Comment by beutlich** [comment]
> Based on #4236 shouldn't it be `PressureSlope `instead of `PressureRate`?
> 
> That would make `Pressure` and `Temperature` more consistent. Based on #4236 `FlowRate `is for connector variables, whereas `Slope` is for derivatives, (and plain `Rate` is used for completely different things).

Will do (in this PR).

**Review by casella — APPROVED** [review]
LGTM

**Pull request merged**
