### PR TITLE
Resolve #4336

### LINKED ISSUE #4336: MSL 4.1.0 Regressions - Magnetic.FluxTubes
The following models fail in result comparison.
Tested revision: f9bddf86 (2024-02-16)

Changed models, need reference update after library officer check:
- [x] Modelica.Magnetic.FluxTubes.Examples.MovingCoilActuator.ForceCurrentBehaviour
      - Reason: `pmActuator.coil.L_stat` is ill-defined at time = 0. @AHaumer will provide a PR to remove it from the comparison signals. Resolved by #4418
      - Updated reference files? Yes pls. @GallLeo 
- [x] ModelicaTest.Magnetic.FluxTubes.Sensors
      - Reason: no more regression reported
      - Updated reference files? No.
- [x] ModelicaTest.Magnetic.FluxTubes.Shapes.FixedShape
      - Reason: no more regression reported
      - Updated reference files? No.

- [x] Release notes check: Are all classes mentioned which could lead to result changes in user models?	  	  

I have to dig into the first one, but the other two: @GallLeo are you sure? There's no diff at all:
grafik

---
_Useful Links_

_Current comparison report:
https://www.ltx.de/download/MA/Compare_MSL_v4.1.0/comparison_report_overview.html
-> Reference result test -> Comparison_

_Comparison signal definitions:
https://github.com/modelica/ModelicaStandardLibrary/tree/master/Modelica/Resources/Reference/Modelica
https://github.com/modelica/ModelicaStandardLibrary/tree/master/ModelicaTest/Resources/Reference/ModelicaTest_

_Reference results:
https://github.com/modelica/MAP-LIB_ReferenceResults_

### PR DESCRIPTION
**Pull request by AHaumer**
- remove ill-defined pmActuator.coil.L_stat from comparisonSignals.txt for Modelica.Magnetic.FluxTubes.Examples.MovingCoilActuator.ForceCurrentBehaviour
- define output interval for all 3 examples Modelica.Magnetic.FluxTubes.Examples.MovingCoilActuator

### CODE REVIEW

**Review by casella — APPROVED** [review]
LGTM

**Review by HansOlsson — COMMENTED** [review]
I agree with removing the signals and the new Interval for ArmatureStroke (in order to see the accelerations in the armature that happens in very short bursts).

But I don't see why we have so short Interval for the other two models - to me it seems 0.01 s would work as well. To me if someone sets a very small Interval I expect that there is something relevant on that time-scale, and I don't know which signal.

BTW: The documentation is broken for those two models (and likely have been for quite some time) - it refers to flange_b for components that only have flange.

**Review by maltelenz — APPROVED** [review]

**Comment by Esther-Devakirubai** [comment]
@casella Can this be backported to maint/4.1.0? No milestone mentioned.

**Comment by casella** [comment]
Please do, this resolves #4336, please also close that once the backport is merged in.

**Comment by Esther-Devakirubai** [comment]
Backported to maintenance branch by #4447

**Pull request merged**
