### PR TITLE
Add StopTime to experiment annotation of Modelica.Electrical.QuasiStatic.SinglePhase.Examples.MultipleResonance

### PR DESCRIPTION
**Pull request by Harisankar-Allimangalath**
backport #PR4311

### CODE REVIEW

**Review by beutlich — CHANGES_REQUESTED** [review]
Please fix the commit message to not reference the wrong issue.

**Comment by Harisankar-Allimangalath** [comment]
@beutlich , is it fine if I edit the commit message added by @AHaumer

**Comment by beutlich** [comment]
> @beutlich , is it fine if I edit the commit message added by @AHaumer

You can easily fix it when doing a squash merge via GitHub.

**Review by beutlich — APPROVED** [review]

**Review by arunkumar-narasimhan — APPROVED** [review]

**Review by AHaumer — APPROVED** [review]
ök

**Pull request merged**
