### PR TITLE
Correct Constraints.Prismatic

### PR DESCRIPTION
**Pull request by HansOlsson**
Avoid singularity close to the solution by not having diagonal(R_T)=ones(3),
which is basically x^2 and thus its derivative is singular at the solution.

Instead use off-diagonal(R_T)=zeros(3) whose derivative is non-singular at the solution.
(With some trick so that we only get {1,1,1} on the diagonal and not {-1,-1,1}.)

Found when investigating #3712 

Dymola will notice that non-linear systems are close to singular for the wrong setting. (Enable Debug>Non-Linear>Details)

### CODE REVIEW

**Comment by HansOlsson** [comment]
CI isn't working, see https://github.com/modelica/ModelicaStandardLibrary/issues/3697#issuecomment-760267088

**Comment by beutlich** [comment]
Does this fix #3710?

**Comment by HansOlsson** [comment]
> Does this fix #3710?

Yes, completely and re-using existing code. 
I didn't realize that someone had already made a ticket for it.

**Comment by henrikt-ma** [comment]
I am so pleased to see numeric conditioning issues like this being fixed!  I have only tested this on the `PrismaticConstraint` example, but in this case the fix works excellent.

**Review by henrikt-ma — APPROVED** [review]
The new constraint does indeed look better from a numerical perspective, gives vastly improved numerical conditioning at least in the case of the `PrismaticConstraint` example, and doesn't cause any other problems with System Modeler as far as I can see.

**Comment by tobolar** [comment]
@HansOlsson
> I didn't realize that someone had already made a ticket for it.

You've only missed it by hours. The issue is quite new! :-)

**Review by tobolar — APPROVED** [review]
Nice!

**Review by beutlich — COMMENTED** [review]
@HansOlsson Could you please update to include the assert that the diagonal elements are all positive one (as requested by https://github.com/modelica/ModelicaStandardLibrary/issues/3710#issuecomment-761886823).

**Comment by HansOlsson** [comment]
> @HansOlsson Could you please update to include the assert that the diagonal elements are all positive one (as requested by [#3710 (comment)](https://github.com/modelica/ModelicaStandardLibrary/issues/3710#issuecomment-761886823)).

It's not needed, as the atan2 in equalityConstraint will ensure that (negative diagonal elements will give a residual of pi); cp. #1817 and the earlier issue (before they had a number) that added atan2 in equalityConstraint.

**Review by beutlich — APPROVED** [review]
> 
> 
> > @HansOlsson Could you please update to include the assert that the diagonal elements are all positive one (as requested by [#3710 (comment)](https://github.com/modelica/ModelicaStandardLibrary/issues/3710#issuecomment-761886823)).
> 
> It's not needed, as the atan2 in equalityConstraint will ensure that (negative diagonal elements will give a residual of pi); cp. #1817 and the earlier issue (before they had a number) that added atan2 in equalityConstraint.

Right. Thanks. @TobiasZawada

**Comment by TobiasZawada** [comment]
Okay, in my short review I ended up there: https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Mechanics/MultiBody/Frames/TransformationMatrices/orientationConstraint.mo

I think that was my fault, wasn't it?

Is there another specialization of `orientationConstraint` used for the relative orientation?

(I don't doubt the solution, I just want to understand it.)

**Comment by HansOlsson** [comment]
> Okay, in my short review I ended up there: https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Mechanics/MultiBody/Frames/TransformationMatrices/orientationConstraint.mo

It's `equalityConstraint `in 

https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Mechanics/MultiBody/Frames/TransformationMatrices/Orientation.mo

A bit confusing as it's not a separate file, since it's a function in a record.

**Comment by HansOlsson** [comment]
> Okay, in my short review I ended up there: https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Mechanics/MultiBody/Frames/TransformationMatrices/orientationConstraint.mo
> 
> I think that was my fault, wasn't it?
> 
> Is there another specialization of `orientationConstraint` used for the orientations?
> 
> (I don't doubt the solution anymore, I just want to understand it.)
> 
> EDIT: I see now that #1817 is about quaternions. What does ensure that quaternions are used for the Orientations at the connectors?

It's worse - there are three variants of equalityConstraint.

The ones that is primarily used was corrected 2007-01-23 (T and w) and used in connectors, the quaternion one in #1817, and that one isn't corrected yet (only T) - I don't know if that is used at all.
Copy duplication.

**Comment by tobolar** [comment]
@HansOlsson Could you also add Documentation.revision annotation summarizing the improvement?
Cf. https://github.com/modelica/ModelicaStandardLibrary/pull/3724#pullrequestreview-570734200

**Comment by HansOlsson** [comment]
> @HansOlsson Could you also add Documentation.revision annotation summarizing the improvement?
> Cf. [#3724 (review)](https://github.com/modelica/ModelicaStandardLibrary/pull/3724#pullrequestreview-570734200)

Ok!

**Pull request merged**
