### PR TITLE
AdditionalSqrt

### PR DESCRIPTION
**Pull request by Esther-Devakirubai**
Backport #4396

### CODE REVIEW

**Review by casella — CHANGES_REQUESTED** [review]
@Esther-Devakirubai #4396 affects four files, while this backport only affects two. I guess there are some additional commits missing

**Comment by Esther-Devakirubai** [comment]
> @Esther-Devakirubai #4396 affects four files, while this backport only affects two. I guess there are some additional commits missing

Will check.

**Comment by Esther-Devakirubai** [comment]
> > @Esther-Devakirubai #4396 affects four files, while this backport only affects two. I guess there are some additional commits missing
> 
> Will check.

@casella I see only 2 files being affected by this.

https://github.com/modelica/ModelicaStandardLibrary/commit/1be54b5edfd3370f0365cab256cbed62c40bc2bc

Please correct me if I am wrong.

**Comment by maltelenz** [comment]
@Esther-Devakirubai there are more commits in #4396 : https://github.com/modelica/ModelicaStandardLibrary/pull/4396/commits

but this PR only contains the contents of one of them.

**Comment by casella** [comment]
> @Esther-Devakirubai there are more commits in #4396 : https://github.com/modelica/ModelicaStandardLibrary/pull/4396/commits
> 
> but this PR only contains the contents of one of them.

Yes, the #4396 PR contains multple commits, but for some reason the cherry-picking only considered the first one

**Review by maltelenz — CHANGES_REQUESTED** [review]
Does still not have the same changes as #4396 which it claims to backport.

**Review by maltelenz — APPROVED** [review]
Changes now match what it claims to backport.

I have no opinion on whether this should be backported, but @casella already [said it was OK to backport](https://github.com/modelica/ModelicaStandardLibrary/pull/4396#issuecomment-2260085544), so approving.

**Review by casella — COMMENTED** [review]
I don't get why `.sqrt` and not just `sqrt`. sqrt(v) is defined as the square root if v is Real or Integer, which is the case here. @HansOlsson, why the leading dot?

**Comment by HansOlsson** [comment]
> I don't get why `.sqrt` and not just `sqrt`. sqrt(v) is defined as the square root if v is Real or Integer, which is the case here. @HansOlsson, why the leading dot?

There is a comment explaining that on the line: "Real, not complex sqrt".

Due to lookup `sqrt` in `Modelica.ComplexMath` will find the complex `Modelica.ComplexMath.sqrt`-function, which isn't desired here. The complex exp and log functions work around it by using Modelica.Math.exp and Modelica.Math.log

**Comment by Esther-Devakirubai** [comment]
@casella Can this be approved and Merged?

**Comment by casella** [comment]
> There is a comment explaining that on the line: "Real, not complex sqrt".
> 
> Due to lookup `sqrt` in `Modelica.ComplexMath` will find the complex `Modelica.ComplexMath.sqrt`-function, which isn't desired here. The complex exp and log functions work around it by using Modelica.Math.exp and Modelica.Math.log

I previously assumed that built-in functions had precedence in the look-up process, so they could not be shadowed. I obviously missed [Section 5.6.1.1](https://specification.modelica.org/maint/3.6/scoping-name-lookup-and-flattening.html#the-class-tree) saying: "The builtin classes are put into the unnamed root of the class tree".

**Comment by casella** [comment]
> @casella Can this be approved and Merged?

Yes, please go ahead. Thanks!

**Comment by maltelenz** [comment]
> > @casella Can this be approved and Merged?
> 
> Yes, please go ahead. Thanks!

You requested changes earlier, so you have to actually approve :)

**Review by casella — APPROVED** [review]
LGTM

**Comment by casella** [comment]
> @casella You requested changes earlier, so you have to actually approve :)

😅

**Pull request merged**
