### PR TITLE
Update CMake config

### PR DESCRIPTION
**Pull request by beutlich**
In addition to #4265

* Do not expose ZLIB_INCLUDE_DIR to all targets
* Fix build with VS 17.10

### CODE REVIEW

**Review by HansOlsson — APPROVED** [review]
Looks good (after going down the rabbit hole of trying to check whether there will be a vs 2025 or not).

**Comment by beutlich** [comment]
> Looks good (after going down the rabbit hole of trying to check whether there will be a vs 2025 or not).

Oh, did you find out?

**Comment by casella** [comment]
And, will there be a ChatGPT 5? 😄

**Comment by HansOlsson** [comment]
> And, will there be a ChatGPT 5? 😄

More relevant than you might think: I noticed that LLMs hallucinated that the release date of VS 2025 had been announced.

**Review by maltelenz — APPROVED** [review]
Looks good to me.

**Pull request merged**
