### PR TITLE
Run spelling check via GitHub Actions

### PR DESCRIPTION
**Pull request by beutlich**

### CODE REVIEW

**Review by sjoelund — APPROVED** [review]

**Comment by sjoelund** [comment]
Make sure to update the package.order file after renaming class

**Comment by beutlich** [comment]
> Make sure to update the package.order file after renaming class

Right. I forgot about it. Luckily it is in ModelicaTest and we do not have to worry about conversion.

**Review by dietmarw — COMMENTED** [review]
I guess it is OK, though probably quite fragile since the introduction of any false positive will now also require to update the CI setup. At the same time I don't think codespell is very good in catching spelling errors. It never did on my own libs unfortunately.

**Comment by HansOlsson** [comment]
> I guess it is OK, though probably quite fragile since the introduction of any false positive will now also require to update the CI setup. At the same time I don't think codespell is very good in catching spelling errors. It never did on my own libs unfortunately.

I'm also concerned about this - both that many changes will require updating a CI-command line, and also that there are so many similar cases that are missed.

In particular "ist" for multi-body is likely IST the Information Societies Technology, but why does it ignore all names and the abbreviation RealSim?

For Blocks.Digitial "utput" it is likely the `<strong>o</strong>utput` that is causing this, but why don't we have nput, ingle, ultiple based on the same pattern?

I agree that running a spell-checker is generally a good idea, but I'm not convinced it should be this automated.

**Comment by beutlich** [comment]
@dietmarw @HansOlsson I see your points and changed the workflow trigger event from push/PR to manual trigger and weekly trigger.

**Review by dietmarw — APPROVED** [review]

**Pull request merged**
