### PR TITLE
Document non-backward compatible changes of #3690

### PR DESCRIPTION
**Pull request by beutlich**
This was forgotten before merging #3690.

### CODE REVIEW

**Review by tobolar — APPROVED** [review]

**Comment by tobolar** [comment]
@beutlich You could also add such a documentation for #3702 (doing so here seems easier for reviewing).

**Comment by beutlich** [comment]
> 
> 
> @beutlich You could also add such a documentation for #3702 (doing so here seems easier for reviewing).

Do not understand what are the non-backward compatible changes of #3702. My focus are these non-backward compatible changes which are hard to track when just scanning the closed issues.

**Comment by tobolar** [comment]
Sorry, my mistake. The idea was to document the new elements. But this is obviously not necessary at the moment.

**Review by HansOlsson — APPROVED** [review]
Ok!

**Pull request merged**
