### PR TITLE
Update CoupledClutches.mos

### PR DESCRIPTION
**Pull request by DagBruck**
Updated to Dymola command set from this millennium.

### CODE REVIEW

**Review by dietmarw — APPROVED** [review]
LGTM

**Comment by beutlich** [comment]
Would be better to merge to master and cherry-pick after merge.

**Review by AHaumer — APPROVED** [review]
ok
as @beutlich said, merge to master, then to maint\4.1.0

**Review by tobolar — APPROVED** [review]
Fine to me.

**Comment by DagBruck** [comment]
It would help to have some document that describes "best practices". Git permits many different ways to use the system, branching, etc. I'm happy to march along, if somebody just points in the right direction.

**Comment by DagBruck** [comment]
Thats for the pointer @dietmarw but I must admit I was confused by what it says:

> **Maintenance branch**
> 
> Name: "maint/4.0.x"
> 
> This branch contains the released Modelica Standard Library version (e.g., v4.0.0) where all bug-fixes since this release date are included (also consecutive BUGFIX versions 4.0.1, 4.0.2, etc., up to when a new MINOR or MAJOR release becomes available; i.e., there will not be any further BUGFIX versions (i.e., 4.0.x) of a previous release).

The way I read it, the maintenance branch is created after the new release has been created, and then you can apply bug fixes to 4.0.x versions. Is that correct?

What makes me confused is that we have `maint/4.1.0` define now, but 4.1 has not been released.

**Comment by dietmarw** [comment]
Well naming the branch `4.1.0` is simply **wrong**. It should be `4.1.x`

**Comment by DagBruck** [comment]
@HansOlsson suggested  I create a new pull request for the master branch: #4350.

**Pull request closed without merging**
