### PR TITLE
Add LinearDependency2 and deprecate LinearDependency

### LINKED ISSUE #1724: Modelica.Blocks.Math.LinearDependency has strange formulation
**Reported by Joe Riel on 1 Jun 2015 14:58 UTC**
The relatively new block LinearDependency seems strange. It's defining equation is `y = y0*(1 + k1*u1 + k2*u2);`. y0 is a parameter; its description says it is an initial value, which makes no sense.  It is a scale factor (with a useless default of 0).  However, if its value is nonzero, then one cannot produce an output with a non-zero offset.  I'm thinking the block would be slightly more useful if the defining equation were `y = y0 + k1*u1 + k2*u2`.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1724

### PR DESCRIPTION
**Pull request by beutlich**
This is my second attempt to fix #1724.

### CODE REVIEW

**Comment by JoeRiel** [comment]
I'm not real familiar with convertModifiers, but would the following work?
```convertModifiers("Modelica.Blocks.LinearDependency",
                 {"y0=0", "k1=0", "k2=0"}, {"y0=%y0%","k1=%y0%*%k1%","k2=%y0%*%k2%"});```
If so, that would allow directly replacing the model, hence no need to create a new name.

**Comment by beutlich** [comment]
> I'm not real familiar with convertModifiers, but would the following work?

Need to check it.

**Comment by beutlich** [comment]
> I'm not real familiar with convertModifiers, but would the following work?

Unfortunately, the following conversion fails in Dymola 2020, since `y0` cannot be evaluated.

```
convertModifiers("Modelica.Blocks.Math.LinearDependency",
                 {"k1"}, {"k1=%y0%*%k1%"});
convertModifiers("Modelica.Blocks.Math.LinearDependency",
                 {"k2"}, {"k2=%y0%*%k2%"});
```

The following conversion works in Dymola 2020, but unfortunately is not save w.r.t. the lookup of `y0`, since we do not have a self/this environment in Modelica (see https://github.com/modelica/ModelicaSpecification/issues/213).

```
convertModifiers("Modelica.Blocks.Math.LinearDependency",
                 {"k1"}, {"k1=y0*%k1%"});
convertModifiers("Modelica.Blocks.Math.LinearDependency",
                 {"k2"}, {"k2=y0*%k2%"});
```

Thus, currently complex modifiers cannot be converted in Dymola 2020.

**Comment by beutlich** [comment]
Superseded by #3095.

**Pull request closed without merging**
