### PR TITLE
Consistent spelling of electrical and magnetic terms

### LINKED ISSUE #733: Rename `SynchronousInductionMachines` to `SynchronousMachines`
**Reported by dietmarw on 30 Apr 2012 13:25 UTC**
There seems to be a major flaw with the naming convention. To my knowledge an electrical machine can be either of induction type **or** of synchronous type but not both at the same time. Therefore calling a machine "Synchronous Induction Machine" doesn't make sense and the naming convention should be changed as soon as a conversion script allows this.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/733

### LINKED ISSUE #2973: Rename MultiPhase to Polyphase
This is a follow-up on https://github.com/modelica/ModelicaStandardLibrary/issues/1865#issuecomment-330878902 and also related to #733 and also #2971.

We should correct the multi-phase terms (and their spelling variants) to `Polyphase`. Mind no camel case since it was agreed that the correct to be used term is "polyphase" and not "poly-phase" or "poly phase".

### PR DESCRIPTION
**Pull request by beutlich**
This is getting massive.

* polyphase
* single-phase
* three-phase
* quasi-static
* induction machine
* synchronous machine
* electromagnetic

close #733, close #2973

### CODE REVIEW

**Comment by christiankral** [comment]
@AHaumer I think we shall go ahead with this PR anytime soon. Otherwise we may run into (even more) conflicts when incorporating other PRs.

**Comment by beutlich** [comment]
Took me one hour to resolve he merge conflicts.

This PR is not yet ready sinc conversion scripts are missing and not yet all models are renamed.

**Comment by christiankral** [comment]
Sorry for opening the PR...

**Comment by christiankral** [comment]
Thanks a lot for putting so much effort in resolving the merge conflicts. I think we shall try to merge this PR with the highest priority due to the huge impact is has.

**Comment by beutlich** [comment]
@christiankral Maybe you could create a PR first removing Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SymmetricMultiPhaseCageWinding_obsolete (and Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SaliencyCageWinding_obsolete) such that they do not get renamed when I do bulk search and replace.

**Comment by christiankral** [comment]
> @christiankral Maybe you could create a PR first removing Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SymmetricMultiPhaseCageWinding_obsolete (and Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SaliencyCageWinding_obsolete) such that they do not get renamed when I do bulk search and replace.

Covered by #3031

**Comment by AHaumer** [comment]
@beutlich 
Many thanks for tackling this issue - you're right, this is a really large change, I appreciate this.
As far as I see this looks good, I saw only a few issues:
* aimcData -> imcData
* defaultComponentName="aimc" -> "imc"

I'm pretty sure even if we go through the whole thing we will miss some small issues. 
But never mind, if don't do that as soon as possible it'll get never done and it blocks other issues.
We can tackle small remianing issues later.

As soon as we have a conversion script, I vote for merging.

**Comment by beutlich** [comment]
> 
> 
> > @christiankral Maybe you could create a PR first removing Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SymmetricMultiPhaseCageWinding_obsolete (and Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SaliencyCageWinding_obsolete) such that they do not get renamed when I do bulk search and replace.
> 
> Covered by #3031

Thanks. Changes are incorporated by rebasing.

>  I saw only a few issues:

Yes, not all renaming is done currently.

**Comment by beutlich** [comment]
Here's the proposed conversion for the renaming (no examples, no component name):

```
convertClass("Modelica.Electrical.Machines.BasicMachines.AsynchronousInductionMachines.AIM_SquirrelCage",
              "Modelica.Electrical.Machines.BasicMachines.InductionMachines.IM_SquirrelCage")
convertClass("Modelica.Electrical.Machines.BasicMachines.AsynchronousInductionMachines.AIM_SlipRing",
              "Modelica.Electrical.Machines.BasicMachines.InductionMachines.IM_SlipRing")
convertClass("Modelica.Electrical.Machines.BasicMachines.SynchronousInductionMachines",
              "Modelica.Electrical.Machines.BasicMachines.SynchronousMachines")
convertClass("Modelica.Electrical.Machines.Thermal.AsynchronousInductionMachines.ThermalAmbientAIMC",
              "Modelica.Electrical.Machines.Thermal.InductionMachines.ThermalAmbientIMC")
convertClass("Modelica.Electrical.Machines.Thermal.AsynchronousInductionMachines.ThermalAmbientAIMS",
              "Modelica.Electrical.Machines.Thermal.InductionMachines.ThermalAmbientIMS")
convertClass("Modelica.Electrical.Machines.Thermal.SynchronousInductionMachines",
              "Modelica.Electrical.Machines.Thermal.SynchronousMachines")
convertClass("Modelica.Electrical.Machines.Interfaces.InductionMachines.ThermalPortAIMC",
              "Modelica.Electrical.Machines.Interfaces.InductionMachines.ThermalPortIMC")
convertClass("Modelica.Electrical.Machines.Interfaces.InductionMachines.PowerBalanceAIMC",
              "Modelica.Electrical.Machines.Interfaces.InductionMachines.PowerBalanceIMC")
convertClass("Modelica.Electrical.Machines.Interfaces.InductionMachines.ThermalPortAIMS",
              "Modelica.Electrical.Machines.Interfaces.InductionMachines.ThermalPortIMS")
convertClass("Modelica.Electrical.Machines.Interfaces.InductionMachines.PowerBalanceAIMS",
              "Modelica.Electrical.Machines.Interfaces.InductionMachines.PowerBalanceIMS")
convertClass("Modelica.Electrical.Machines.Utilities.ParameterRecords.AIM_SquirrelCageData",
              "Modelica.Electrical.Machines.Utilities.ParameterRecords.IM_SquirrelCageData")
convertClass("Modelica.Electrical.Machines.Utilities.ParameterRecords.AIM_SlipRingData",
              "Modelica.Electrical.Machines.Utilities.ParameterRecords.IM_SlipRingData")
convertClass("Modelica.Electrical.PowerConverters.DCAC.MultiPhase2Level",
              "Modelica.Electrical.PowerConverters.DCAC.Polyphase2Level")
convertClass("Modelica.Electrical.QuasiStationary.MultiPhase",
              "Modelica.Electrical.QuasiStatic.Polyphase")
convertClass("Modelica.Electrical.MultiPhase",
              "Modelica.Electrical.Polyphase")
convertClass("Modelica.Magnetic.FundamentalWave.UsersGuide.MultiPhase",
              "Modelica.Magnetic.FundamentalWave.UsersGuide.Polyphase")
convertClass("Modelica.Magnetic.FundamentalWave.Components.MultiPhaseElectroMagneticConverter",
              "Modelica.Magnetic.FundamentalWave.Components.PolyphaseElectroMagneticConverter")
convertClass("Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SymmetricMultiPhaseWinding",
              "Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SymmetricPolyphaseWinding")
convertClass("Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SymmetricMultiPhaseCageWinding",
              "Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SymmetricPolyphaseCageWinding")
convertClass("Modelica.Magnetic.FundamentalWave.BasicMachines.AsynchronousInductionMachines.AIM_SquirrelCage",
              "Modelica.Magnetic.FundamentalWave.BasicMachines.InductionMachines.IM_SquirrelCage")
convertClass("Modelica.Magnetic.FundamentalWave.BasicMachines.AsynchronousInductionMachines.AIM_SlipRing",
              "Modelica.Magnetic.FundamentalWave.BasicMachines.InductionMachines.IM_SlipRing")
convertClass("Modelica.Magnetic.FundamentalWave.BasicMachines.SynchronousInductionMachines",
              "Modelica.Magnetic.FundamentalWave.BasicMachines.SynchronousMachines")
convertClass("Modelica.Magnetic.QuasiStatic.FundamentalWave.Components.MultiPhaseElectroMagneticConverter",
              "Modelica.Magnetic.QuasiStatic.FundamentalWave.Components.PolyphaseElectroMagneticConverter")
convertClass("Modelica.Magnetic.QuasiStatic.FundamentalWave.BasicMachines.Components.SymmetricMultiPhaseWinding",
              "Modelica.Magnetic.QuasiStatic.FundamentalWave.BasicMachines.Components.SymmetricPolyphaseWinding")
convertClass("Modelica.Magnetic.QuasiStatic.FundamentalWave.BasicMachines.Components.SymmetricMultiPhaseCageWinding",
              "Modelica.Magnetic.QuasiStatic.FundamentalWave.BasicMachines.Components.SymmetricPolyphaseCageWinding")
```

To be honest, I am too lazy to figure out proper test conversion classes. If anyone want's to do so, please let me know.

**Comment by beutlich** [comment]
@AHaumer @christiankral I added some dummy conversion test models to test the proposed renaming of classes. From my point of view this PR is now ready for your review.

**Pull request merged**
