### PR TITLE
Bug in pressure influence in moist air function s_pTX and s_pTX_der

### PR DESCRIPTION
**Pull request by wischhusen**
See https://github.com/modelica/ModelicaStandardLibrary/pull/3069#issuecomment-529359817 for the issue analysis.

### CODE REVIEW

**Comment by dietmarw** [comment]
This PR is messed up. Please try again without deleting half of the MSL ;-)

**Comment by beutlich** [comment]
I tried my best. Please double check.

**Comment by beutlich** [comment]
@wischhusen  Can you please confirm the force-pushed changes!
@hubertus65 @thorade Can you please review!

**Comment by thorade** [comment]
Just by looking at the code I do not immediately see what has changed or not, also partly due to formatting, but I assume it is correct. Do we have a minimal example to reproduce the problem that will be fixed by this?

**Comment by wischhusen** [comment]
@thorade This should be the tester.

[testerMoistAir.zip](https://github.com/modelica/ModelicaStandardLibrary/files/3641215/testerMoistAir.zip)

**Comment by beutlich** [comment]
@hubertus65 @thorade Can you please add your review.

**Comment by beutlich** [comment]
Edit: Updated my previous comment (which was based on wrong simulation time).

**Pull request merged**
