### PR TITLE
Fix dimension of conditionally declared components

### LINKED ISSUE #2574: Potentially illegal conditional components in Fluid.Vessels
`Modelica.Fluid.Vessels.BaseClasses.PartialLumpedVessel` contains the following conditional components (type names shortened for readability):
```Modelica
RealInput[nPorts] portsData_diameter_internal = portsData.diameter if use_portsData and nPorts > 0;
RealInput[nPorts] portsData_height_internal = portsData.height if use_portsData and nPorts > 0;
RealInput[nPorts] portsData_zeta_in_internal = portsData.zeta_in if use_portsData and nPorts > 0;
RealInput[nPorts] portsData_zeta_out_internal = portsData.zeta_out if use_portsData and nPorts > 0;
```
`portsData` is in turn declared as:
```Modelica
parameter VesselPortsData[if use_portsData then nPorts else 0] portsData;
```
The issue with this is that when `use_portsData = false` then `portsData` will be an array with 0 elements while the conditional variables above will have `nPorts` elements, leading to a type mismatch between the variables and their binding equations when `nPorts > 0`. This occurs in e.g. `Modelica.Fluid.Examples.TraceSubstrances.RoomCO2WithControls` where `use_portsData` is set to `false` and `nPorts` to 4 on the `volume` component.

This was previously somewhat of a gray area since it wasn't really specified how valid conditional components should be, but in Modelica 3.4 this was clarified as (section 4.4.5):
>If the Boolean expression is false the component (including its modifier) is removed from the flattened DAE , and connections to/from the component are removed. [Adding the component and then removing it ensures that the component is valid.]

I interpret this to mean that conditional components must be as valid as any other component, including having type compatible binding equations.

### PR DESCRIPTION
**Pull request by beutlich**
close #2574

### CODE REVIEW

**Comment by beutlich** [comment]
I rather prefer to have the dimensions explicit.

**Comment by HansOlsson** [comment]
How about having a common protected parameter for this size - something like `nPortsOr0 `(preferably more sensible name).

**Comment by beutlich** [comment]
> How about having a common protected parameter for this size

Yes, that is sensible, but probably more invasive (than just the four lines as now).

I hope that @casella will have a look at it and update this PR accordingly.

**Comment by HansOlsson** [comment]
If you really insist I can accept giving the array dimensions.

**Comment by beutlich** [comment]
Considering @perost's edit from https://github.com/modelica/ModelicaStandardLibrary/issues/2574#issuecomment-393849202, this is wrong.

**Comment by beutlich** [comment]
> I hope there is at least one test case for this addition.

Modelica.Fluid.Examples.TraceSubstances.RoomCO2WithControls has use_portsData = false and nPorts =4.

**Pull request closed without merging**
