### PR TITLE
Fix initialization of Lines as discussed in #3826

### PR DESCRIPTION
**Pull request by AHaumer**
The models `Analog.Lines.{OLine, ULine, TLine1, TLine2, TLine3}` lack the possibility for proper initialization, since the components that have to be accessed for initialization are protected. I've made them public.
`Analog.Lines.M_OLine` is bugfixed in #3827.
@dietmarw can you back-port this to maint/4.0.x?
I suppose after merging this PR and #3827 we should rebase #3819 or create a new PR.

### CODE REVIEW

**Review by dietmarw — APPROVED** [review]

**Comment by AHaumer** [comment]
@dietmarw could we include in this PR a unification of {TLine1, TLine2, TLine3} which only differ in parameterization?

**Comment by dietmarw** [comment]
> @dietmarw can you back-port this to maint/4.0.x?

Yes will do. 

> I suppose after merging this PR and #3827 we should rebase #3819 or create a new PR.

I'll rebase it once this is merged.

**Comment by dietmarw** [comment]
> @dietmarw could we include in this PR a unification of {TLine1, TLine2, TLine3} which only differ in parameterization, or should this be done in a sparate PR?

I guess this is superseded by the PR you've already created.

**Comment by dietmarw** [comment]
@ahaumer, the extension  added in c0ed357 means it can no longer be seen as bugfix. Hence it will not get back-ported. Which is probably fine but just thought to make you aware of this.

**Comment by AHaumer** [comment]
> 
> 
> @AHaumer, the extension added in [c0ed357](https://github.com/modelica/ModelicaStandardLibrary/commit/c0ed3575ee4cd8f091229a39a4f2c6cad802de83) means it can no longer be seen as bugfix. Hence it will not get back-ported. Which is probably fine but just thought to make you aware of this.

Would it be ok if I create a PR that handles initialization for maint/4.0,x?

**Comment by dietmarw** [comment]
Simply create a new PR with just the latest change and I take care of this PR so it will only contain the bugfix.

**Comment by dietmarw** [comment]
So this PR is now the original bugix PR again. Which can be merged once approved. Please do not add any additional features here.

**Comment by AHaumer** [comment]
Ok so you separate the initalization fix from unifying the TLines. 
Since unifying the TLines won't strikeover the bigfix of this PR?

**Review by christiankral — COMMENTED** [review]
As the variables `er` and `es` became public, they need a docstring on my opinion.

**Review by christiankral — COMMENTED** [review]
@AHaumer Please double check the docstrings and confirm / change them accordingly.

I will approve this PR once @AHaumer commented on the proposed docstrings.

**Review by christiankral — APPROVED** [review]
I suppose the wording is good now.

**Pull request merged**
