### PR TITLE
Almost automatically updated to have correct gradient.

### LINKED ISSUE #3951: Missing gradient colors in some Icons
Some classes have Icon annotations where there is a `fillPattern` which should give a gradient, but they have `lineColor` explicitly equal to `fillColor` which results in a solid fill instead.

As an example we have `Modelica.Fluid.Vessels.OpenTank` where the upper part of the tank is represented as:
```
  Rectangle(
    extent={{-100,100},{100,-100}},
    lineColor={255,255,255},
    fillColor={255,255,255},
    fillPattern=FillPattern.VerticalCylinder)
```

We believe this could be the result of developing the models before there was standardized support for gradient fills.

**I wonder, is the intended behavior that it should be a gradient from black to `fillColor`?** If that would be correct then for e.g. `OpenTank` the `lineColor` should be removed, and preferably `pattern=LinePattern.None` added since the tank is open.

Other affected classes with one or more graphical elements where this happens in MSL 4.0:
  Modelica.Electrical.Machines.Icons.TransientTransformer
  Modelica.Electrical.Machines.BasicMachines.Transformers
  Modelica.Electrical.Machines.Icons.QuasiStaticTransformer
  Modelica.Electrical.Machines.BasicMachines.Components.PartialAirGapDC
  Modelica.Electrical.QuasiStatic.Machines.BasicMachines.Transformers
  Modelica.Fluid.Examples.AST_BatchPlant.BaseClasses.TankWith3InletOutletArraysWithEvaporatorCondensor
  Modelica.Fluid.Examples.AST_BatchPlant.BaseClasses.TankWithTopPorts
  Modelica.Magnetic.FluxTubes.Examples.Hysteresis.Components.Transformer1PhaseWithHysteresis
  Modelica.Magnetic.FluxTubes.Examples.Hysteresis.Components.Transformer3PhaseYyWithHysteresis

### PR DESCRIPTION
**Pull request by HansOlsson**
Primarily done using a new flag of updateModelicaAnnotations in Dymola.
But Modelica/Electrical/Machines/Icons/(Quasi|)StaticTransformer.mo was also manually converted to be more line-based texts (makes future changes more logical), and some part of Modelica.Electrical are missing here - need to investigate.
Closes #3951

### CODE REVIEW

**Comment by HansOlsson** [comment]
For TwoPort and FourPort I believe the gradients were a plain mistake, and removed them.

**Comment by HansOlsson** [comment]
> I'm not really sure what this is all about, am I supposed to know?

Perhaps, the change in Modelica.Fluid.Vessels should change the diagrams seen in Modelica.Fluid.Examples.AST_BatchPlant.BaseClasses.TankWith3InletOutletArraysWithEvaporatorCondensor
Modelica.Fluid.Examples.AST_BatchPlant.BaseClasses.TankWithTopPorts
for Dymola; and possibly make it look better in other tools.

**Comment by HansOlsson** [comment]
If you use Dymola and you don't see any change in

@casella 
- Modelica.Fluid.Examples.AST_BatchPlant.BaseClasses.TankWith3InletOutletArraysWithEvaporatorCondensor (icon has tank with gradient)
- Modelica.Fluid.Examples.AST_BatchPlant.BaseClasses.TankWithTopPorts (icon has tank with gradient)

@christiankral @AHaumer 
- Modelica.Electrical.Machines.BasicMachines.Components.PartialAirGapDC (icon has bar with gradient)
- Modelica.Electrical.Machines.BasicMachines.Transformers (icon has bars with gradients)
- Modelica.Electrical.Analog.Interfaces.FourPin (diagram has arrows - they should be solid, no gradients)

etc you can accept it.

For other tools it may be the same, or the older version may lack the gradients (for the ones that should have them).

**Review by christiankral — APPROVED** [review]
I checked the electrical and magnetic icons and they all look good.

**Review by MartinOtter — APPROVED** [review]

**Pull request merged**
