### PR TITLE
Add SystemModeler generated pages to doc.modelica.org

### PR DESCRIPTION
**Pull request by maltelenz**
This pull request is to add MSL library documentation generated by Wolfram SystemModeler to https://doc.modelica.org/

The structure of the generated files follows a similar pattern as the ones for OpenModelica, but has a subdirectory structure for each top level library.

### CODE REVIEW

**Comment by dietmarw** [comment]
I'm not sure I did or if it is simply the way Dymola and OM are using the standard location. @maltelenz would that be an option for WSW aswell?

**Comment by maltelenz** [comment]
To point to the existing images, we would have to write a special generator just for doc.modelica.org. We would prefer not doing that, since it would be a one-off project with all that means in terms of invested time, testing and potential for bugs in code that will very rarely be used.

**Comment by dietmarw** [comment]
I understand. Would be fine by me. OK for you too, @beutlich ?

**Comment by HansOlsson** [comment]
> I'm not sure I did or if it is simply the way Dymola and OM are using the standard location. 

For Dymola the default is that we don't copy images and resources when generating the html in the normal way, but instead reference the exisitng files.

However, we have been forced to change Dymola for doc.modelica.org to allow that special folder (Resources/helpDymola).

**Comment by beutlich** [comment]
I checked again taking the resource `Lossy-Gear-Bug_Solution.pdf` (from Modelica.UsersGuide.ReleaseNotes.Version_3_2) as example: Search for `attachment` on each of the listed pages
* [Dymola](https://doc.modelica.org/Modelica%203.2.3/Resources/helpDymola/Modelica_UsersGuide_ReleaseNotes.html#Modelica.UsersGuide.ReleaseNotes.Version_3_2) does not link to the attachment. Why was the resource link lost?
* [MapleSim](https://doc.modelica.org/Modelica%203.2.3/Resources/helpMapleSim/UsersGuide/ReleaseNotes/index.html#Version_3_2) links to https://doc.modelica.org/Modelica%203.2.3/Resources/Documentation/Mechanics/Lossy-Gear-Bug_Solution.pdf (which is what I would expect).
* Similarly, [OpenModelica](https://doc.modelica.org/Modelica%203.2.3/Resources/helpOM/Modelica.UsersGuide.ReleaseNotes.Version_3_2.html) also links to https://doc.modelica.org/Modelica%203.2.3/Resources/Documentation/Mechanics/Lossy-Gear-Bug_Solution.pdf.
* WSM (if merged) would link to https://doc.modelica.org/Modelica%203.2.3/Resources/helpWSM/Modelica/resources/Modelica.UsersGuide.ReleaseNotes.Version_3_2_info_001.pdf. Thus, the resource is duplicated and even renamed.

I'd prefer if resources (especially binary files like PDFs) are shared across tools (or even versions), but I see that it might be an ambitious goal. If we do not want to force tools to do so, we simply can move on and accept this and any later pull requests. The only down-side is that it bloats the git repository.

**Comment by dietmarw** [comment]
Actually although not optimal the bloat would only happen in the checked out working copy since the git repo will not contain duplicates (even if renamed): 

```
~/.wo…lica 3.2.3/Resources[gh-pages-add-wsm]$ git hash-object Documentation/Mechanics/Lossy-Gear-Bug_Solution.pdf
09c231c229cc16bc4e078a748058b3a241cf99f4
~/.wo…lica 3.2.3/Resources[gh-pages-add-wsm]$ git hash-object helpWSM/Modelica/resources/Modelica.UsersGuide.ReleaseNotes.Version_3_2_info_001.pdf
09c231c229cc16bc4e078a748058b3a241cf99f4
```

So I would not worry too much about bloat.

**Comment by dietmarw** [comment]
The size of the git repo has just changed by 4 MB by adding the WSM documentation:
```
~/.wo…gh-modelica/Modelica[gh-pages]$ du -sh .git
625M	.git
~/.wo…gh-modelica/Modelica[gh-pages]$ git co gh-pages-add-wsm 
Switched to branch 'gh-pages-add-wsm'
Your branch is up-to-date with 'maltelenz/gh-pages-add-wsm'.
~/.wo…gh-modelica/Modelica[gh-pages-add-wsm]$ du -sh .git
629M	.git
```

**Comment by HansOlsson** [comment]
> I checked again taking the resource Lossy-Gear-Bug_Solution.pdf (from Modelica.UsersGuide.ReleaseNotes.Version_3_2) as example: Search for attachment on each of the listed pages
> 
> Dymola does not link to the attachment. Why was the resource link lost?

It seems like an old issue that has been resolved in Dymola 2020x related to using relative links for such cases. I can regenerate the help-files later.

**Comment by maltelenz** [comment]
> the bloat would only happen in the checked out working copy since the git repo will not contain duplicates (even if renamed)

In that case I see no reason to require tool vendors to point to a centralized location of the resources.

**Comment by beutlich** [comment]
> The size of the git repo has just changed by 3 MB by adding the WSM documentation

This only applies to the .git folder, right? Otherwise, helpWSM is 106 MB on disk.

**Comment by beutlich** [comment]
> I can regenerate the help-files later.

@HansOlsson Make sure to also use MSL v3.2.3+build.3. Simply open a new PR for the gh-pages branch of this repo. (It is recommend to have a separate clone of that gh-pages branch).

**Comment by maltelenz** [comment]
Who is supposed to push the merge button on this, now that all reviewers approved? Should I?

**Comment by beutlich** [comment]
> 
> 
> Who is supposed to push the merge button on this, now that all reviewers approved? Should I?

grafik

**Comment by dietmarw** [comment]
Alright, alright ....

**Comment by maltelenz** [comment]
> Alright, alright ....

I didn't mean to push, I genuinely wanted to know if it was my responsibility if I opened the pull request ;-)

**Comment by HansOlsson** [comment]
> I can regenerate the help-files later.
> 
> @HansOlsson Make sure to also use MSL v3.2.3+build.3. Simply open a new PR for the gh-pages branch of this repo. (It is recommend to have a separate clone of that gh-pages branch).

@beutlich Can you provide a link for that just that procedure without anything special?
I can find several completely different variants, but to me it seems almost everyone is doing some weird - including rebasing etc.

**Comment by beutlich** [comment]
> It seems like an old issue that has been resolved in Dymola 2020x related to using relative links for such cases. I can regenerate the help-files later.

Confirmed that #3277 resolves it.

**Pull request merged**
