### PR TITLE
Simplify selection of constraint equations to be used

### PR DESCRIPTION
**Pull request by tobolar**
Less error-prone and better understandable approach.

### CODE REVIEW

**Review by beutlich — COMMENTED** [review]
LGTM. Can you please address the other three constraints, too?

**Comment by tobolar** [comment]
@beutlich Haven't realized this for the other constraints previously. Done now. Thanks.

**Comment by beutlich** [comment]
Thanks. I really wonder why there is no common base class for all four constaints as they share so much code.

**Review by HansOlsson — APPROVED** [review]
Looks **much** clearer.

**Comment by tobolar** [comment]
@beutlich Could you update your review?

**Review by beutlich — APPROVED** [review]

**Pull request merged**
