### PR TITLE
Add division tag around image tags

### PR DESCRIPTION
**Pull request by beutlich**
See also #3549.

### CODE REVIEW

**Comment by beutlich** [comment]
Something like this?

> Figures shall be placed outside of paragraphs.
> Figures shall not be placed directly within the body context.

**Comment by tobolar** [comment]
@christiankral Are you able to contribute to this discussion? You are in the end the Library officer of UsersGuide.

To be clear: I like the idea of `<div>`environment. But not sure how this works within another environments, e.g. figures within lists.

**Comment by beutlich** [comment]
@tobolar OK for you to merge this PR anyway and update the guide lines later in a separate issue?

**Comment by tobolar** [comment]
I don't know the procedure in detail but wouldn't it lead to lot of warnings being simply ignored? The check itself is fine to me, so ok to merge.

**Pull request merged**
