### PR TITLE
Fix unit error in TestOnly.MoistAir, R134a_setState_pTX and WaterIF97_dewEnthalpy

### PR DESCRIPTION
**Pull request by henrikt-ma**
Note that there is currently no `Units.SI.PressureRate`.  In case https://github.com/modelica/ModelicaStandardLibrary/pull/4103 gets merged first, we should make use of the `Units.SI.PressureRate` introduced there.

### CODE REVIEW

**Comment by qlambert-pro** [comment]
This would help addressing the issues reported in #4099

**Review by hubertus65 — APPROVED** [review]

**Comment by HansOlsson** [comment]
I'm not sure if this is needed - and would discuss it together with #4097

**Review by HansOlsson — CHANGES_REQUESTED** [review]
And here as well.

**Comment by henrikt-ma** [comment]
> And here as well.

I think you need to elaborate.

**Comment by HansOlsson** [comment]
> > And here as well.
> 
> I think you need to elaborate.

See comments in #4103 and #4117

**Review by HansOlsson — APPROVED** [review]
Ok, according to MAP-Lib.

**Pull request merged**
