### PR TITLE
Fix unit error in BatteryDischargeCharge

### PR DESCRIPTION
**Pull request by qlambert-pro**
The magic number 1200, should be carying a unit in order for unit checking to pass. I wasn't inspired, when it came to naming the constant, so feel free to suggest a better name.

### CODE REVIEW

**Comment by HansOlsson** [comment]
Looking at the code it's as if it is the short-circuit current of the battery, which explains the dangerously high number.

**Review by hubertus65 — APPROVED** [review]

**Comment by AHaumer** [comment]
See #4412:
`  parameter Modelica.Units.SI.Current Isc = 1200 "Short-circuit current of cell at OCVmax";`
Instead of having a lot of single PR's, why don't look through these examples systematically and provide the same for CCCV_Cell, CCCV_CellRC, CCCV_Stack, CCCV_StackRC.

**Comment by HansOlsson** [comment]
> See #4412: ` parameter Modelica.Units.SI.Current Isc = 1200 "Short-circuit current of cell at OCVmax";` Instead of having a lot of single PR's, why don't look through these examples systematically and provide the same for CCCV_Cell, CCCV_CellRC, CCCV_Stack, CCCV_StackRC.

You mean #4112 - and I agree that having one common PR for them makes more sense.

**Review by HansOlsson — CHANGES_REQUESTED** [review]
Coordinate/merge with #4112

**Comment by christiankral** [comment]
> This issue is fixed in [8450a8e](https://github.com/modelica/ModelicaStandardLibrary/commit/8450a8eb11d7925dc89475b2f63db2db563ba402) by #4112

Therefore, this ticket can be closed.

**Pull request closed without merging**
