### PR TITLE
Update CI to check HTML documentation for tag validity

### PR DESCRIPTION
**Pull request by beutlich**
Related to #3060 and https://github.com/modelica/ModelicaStandardLibrary/pull/3274#issuecomment-567102255.

The python script has some troubles with self-closing void tags `<br/>` or `</br>` which I simply replaced by `<br>` in https://github.com/modelica/ModelicaStandardLibrary/pull/3274/commits/87d7fa9dfe907360056cd49b7f755c9e8bdd79bf for #3274.

One other false-positive are multi-line non-void tags. Luckily there is only one occurrence in all of MSL, which I edited in https://github.com/modelica/ModelicaStandardLibrary/pull/3274/commits/1b7ed59564d6d5122cf423d03eabc61b38e10b8b for #3274.

https://github.com/modelica/ModelicaStandardLibrary/blob/289ba3c99d7773065dfaee9cc5a8d2860616b8b0/Modelica/Media/IdealGases/Common/package.mo#L1058-L1059

### CODE REVIEW

**Comment by beutlich** [comment]
CI will run successfully once #3274 is merged.

**Comment by mtiller** [comment]
Wouldn't it be better to just use an existing library for this?  I'm not that familiar with the Python ecosystem, but a [simple search](https://www.google.com/search?q=python+tidy+html&oq=python+tidy+html&aqs=chrome..69i57j69i64.2058j0j1&sourceid=chrome&ie=UTF-8) turned up many options.  Seems like they will catch all the issues (which aren't really specified here) and more.

**Comment by beutlich** [comment]
Yes, HTML Tidy is where I started, basically by running https://github.com/RWTH-EBC/HTML-Tidy-Modelica.

The problem with HTML Tidy is that it only detects invalid HTML tags as errros, e.g., 

```
[-- C:\Projekte\MSL\Modelica\Electrical\Batteries\ParameterRecords\TransientData\CellData.mo ]
line 31 column 93 - Error: <cde> is not recognized!


[-- C:\Projekte\MSL\Modelica\Electrical\Batteries\UsersGuide\Concept.mo ]
line 49 column 114 - Error: <nr> is not recognized!
```

Whenever you configure HTML Tidy to show warnings or information, it gets far too noisy. See the two log files with [warnings only](https://gist.github.com/beutlich/2643abf949768e01a6571622be95299e) and [both warnings and info](https://gist.github.com/beutlich/e4f360650035611f7b11056bea5b98c4) for example.

The proposed CI really is a fast, but poor-mans implementation of simple HTML tag validity checking according to our guidelines:
 * lower case tags
 * use `strong` and `em` tags (over `b` and `i` tags)
 * tags should be closed (though HTML might be more tolerant)

**Comment by beutlich** [comment]
Hm, I believe we need to fix these warnings and really should run HTML Tidy with warnings disgnostics.

**Comment by beutlich** [comment]
Doesn't look too bad if we mute the three HTML Tidy warnings `MISSING_ATTRIBUTE,REMOVED_HTML5,MISMATCHED_ATTRIBUTE_WARN` (requires HTML Tidy version 5.6). I'll care for the remaining HTML issues and update the CI job to also utilize HTMl Tidy.

**Comment by beutlich** [comment]
@mtiller The HTML Tidy check is now also included. Thanks for your feedback which really pushed me (again) in the right direction.

**Pull request merged**
