### PR TITLE
Bump used Modelica language version to 3.6 for MapleSim moparser (CI)

### PR DESCRIPTION
**Pull request by beutlich**
According to #4175 this should not be merged right now.

### CODE REVIEW

**Comment by maltelenz** [comment]
There was a decision in the monthly MAP-Lib meeting on the 14th of November, to switch to 3.6 fully, and consider for each PR that tries to use 3.6 features, whether we are ready to accept it for 14.1 or not.

Unfortunately it doesn't seem this was written down anywhere. It was discussed in the context of #4208.

So this should be possible to merge.

**Comment by tobolar** [comment]
@beutlich : I guess @maltelenz is better suited to review this PR.  I was not present at the last MAP-Lib meeting.

**Review by maltelenz — APPROVED** [review]

**Comment by eshmoylova** [comment]
@hubertus65 recorded the following in the chat on Teams for MAP-LIB Monthly: 
image
If we say in the documentation that we support 3.6 then we need to support that claim elsewhere.

**Review by eshmoylova — APPROVED** [review]

**Comment by henrikt-ma** [comment]
@casella, I suppose you as the project leader is the right person to push the merge button on this.

**Comment by arunkumar-narasimhan** [comment]
@casella, this PR is all ready to merge, but seems to be failing at checks. Could you please look into it?

**Comment by beutlich** [comment]
> but seems to be failing at checks.

Not any more.

Note, that merging this PR opens the door for PRs like #4231 which I'd not to have right now. Therefore I'd not like to have it merged now.

**Comment by henrikt-ma** [comment]
> Note, that merging this PR opens the door for PRs like #4231 which I'd not to have right now. Therefore I'd not like to have it merged now.

This sounds like a misunderstanding to me.  The door for #4231 is already open version-wise as of #4208.  What is needed in order to move forward with #4231 shouldn't have anything to do with the MapleSim moparser, but what we need is an agreement with tool vendors that they welcome the adoption of the specific language feature _selective model extension_.

Hence, I believe this PR is fine. Moving it out of _Draft_ state would seem like a good start.

**Comment by GallLeo** [comment]
MAP-LIB meeting 2024-02-02:
We already agreed to not open up to all Modelica 3.6 features.
But, we bumped the version in order to e.g. use figure annotations (as long as no tool vendor complains).
Therefore, syntax check should also be bumped to Modelica 3.6.

**Comment by beutlich** [comment]
> MAP-LIB meeting 2024-02-02: We already agreed to not open up to all Modelica 3.6 features. But, we bumped the version in order to e.g. use figure annotations (as long as no tool vendor complains). Therefore, syntax check should also be bumped to Modelica 3.6.

Sorry, I cannot follow. Enabling MoLang 3.6 syntax also opens all MoLang 3.6 features (as the new break keyword).

**Comment by maltelenz** [comment]
That was what was decided last year, that we would open up for 3.6 generally. However, for each individual pull request that uses new features, tool vendors can object that they are not ready.

**Comment by Harisankar-Allimangalath** [comment]
@maltelenz @beutlich  How should this be proceeded ?

**Comment by maltelenz** [comment]
@Harisankar-Allimangalath please create a pull request to backport to 4.1.0 maint branch.

**Comment by beutlich** [comment]
> @Harisankar-Allimangalath please create a pull request to backport to 4.1.0 maint branch.

Really? I hope that we do not do this.

**Comment by maltelenz** [comment]
> > @Harisankar-Allimangalath please create a pull request to backport to 4.1.0 maint branch.
> 
> Really? I hope that we do not do this.

Could you explain why not?

**Comment by beutlich** [comment]
Because we do not want to allow new syntax features in the branched-off maint branch, do we?

**Comment by Harisankar-Allimangalath** [comment]
@beutlich @maltelenz so should I backport this

**Comment by beutlich** [comment]
> This delays the tool vendor testing.

I am afraid I cannot follow. This a CI feature and tool vendors can test with or w/o it already.

**Comment by Harisankar-Allimangalath** [comment]
@beutlich  ok ,  so once #4299 and #4298 is merged I can tagout the beta tag right .

**Comment by maltelenz** [comment]
@Harisankar-Allimangalath The real blocker for tool vendor testing (at least ours) is that we don't have new reference results.

**Comment by beutlich** [comment]
> @beutlich ok , so once #4299 and #4298 is merged I can tagout the beta tag right ?

IMO it is not yet there. The [changes](https://github.com/modelica/ModelicaStandardLibrary/compare/v4.1.0-alpha.1...da5c5de71f574b33a4f4631e09ba79682755f6d0) are hardly relevant so far whereas the actual open issue haven't be addressed yet.

**Comment by beutlich** [comment]
> The real blocker for tool vendor testing (at least ours) is that we don't have new reference results.

Unblocking -> Results by Dymola 2024x of MSL v4.1.0-beta.1 (with serveral necessary changes) are [here](https://github.com/beutlich/MAP-LIB_ReferenceResults).

**Comment by maltelenz** [comment]
> > The real blocker for tool vendor testing (at least ours) is that we don't have new reference results.
> 
> Unblocking -> Results by Dymola 2024x of MSL v4.1.0-beta.1 (with serveral necessary changes) are [here](https://github.com/beutlich/MAP-LIB_ReferenceResults).

While the effort is appreciated, I was hoping for these things before looking at correctness failures for System Modeler:

* Only updating the reference results for models where we have good reason (model changes)
* At least a categorization of the current failures in the regression testing with Dymola, which I think @GallLeo and @casella started on?

**Comment by beutlich** [comment]
> While the effort is appreciated, I was hoping for these things before looking at correctness failures for System Modeler:
> 
>     * Only updating the reference results for models where we have good reason (model changes)

Uff, not sure if this can be tackled at all while also updating the simulation tool.
 
>     * At least a categorization of the current failures in the regression testing with Dymola, which I think @GallLeo and @casella started on?

Well, #4296 only touched four models and there was no vibrant discussion going on which I would have expected before releasing a beta release.

**Comment by maltelenz** [comment]
> Well, #4296 only touched four models and there was no vibrant discussion going on which I would have expected before releasing a beta release.

Right. I don't know what the intention is with the beta, but if it is a signal that it is ready for tool vendor testing, it's clearly not the case yet :(

**Comment by beutlich** [comment]
Yes, intention of the beta is to trigger tool vendor testing. However with reference results being avialble only now, the process is already broken. Still, you should not be blocked anymore.

**Pull request merged**
