### PR TITLE
Remove unused code (#3622)

### PR DESCRIPTION
**Pull request by adrpo**
There are some components defined that are not used in the blocks or functions.
This PR removes them.

### CODE REVIEW

**Comment by HansOlsson** [comment]
Removing protected parameters (even if unused) seems problematic with current versioning rules.

**Comment by beutlich** [comment]
> 
> 
> Removing protected parameters (even if unused) seems problematic with current versioning rules.

Indeed. It is not covered by conversion rules. For that reason, we mentioned every removed component as backward-compatibility breaking change in the release notes and require a new major version.

**Review by christiankral — APPROVED** [review]
Remove obsolete code is OK

**Comment by christiankral** [comment]
So we could remove the protected parameters from functions, as these quantities cannot be accessed from outside and keep them in models and blocks. Additionally, all commented code fragments shall be removed.

**Comment by christiankral** [comment]
See https://github.com/adrpo/Modelica/pull/1

**Review by AHaumer — COMMENTED** [review]
I'm against removing the unused code. 
It is written as comment and makes the code easier to understand.
So I'm against this PR.

**Comment by christiankral** [comment]
@AHaumer @adrpo Would you agree to better document the code lines? I understand that @ahaumer wants to keep the commented code as it represents an alternative (inverse) representation of the used equations. 

Example: Change

```modelica
  Real RotationMatrix[2, 2]={{+cos(-angle),-sin(-angle)},{+sin(-angle),+
      cos(-angle)}};
  //Real InverseRotator[2,2] = {{+cos(+angle),-sin(+angle)},{+sin(+angle),+cos(+angle)}};
  ...
  //u = InverseRotator*y;
```

to 

```modelica
  Real RotationMatrix[2, 2]={{+cos(-angle),-sin(-angle)},{+sin(-angle),+
      cos(-angle)}};
  // Alternative equivalent implementation:
  // Real InverseRotator[2,2] = {{+cos(+angle),-sin(+angle)},{+sin(+angle),+cos(+angle)}};
  ...
  // Alternative equivalent implementation:
  // u = InverseRotator*y;

```

**Comment by adrpo** [comment]
Is OK from my side, I thought it was some left over code, but if this is documentation, of course we should keep it.
@AHaumer just let us know how you want it.

**Comment by AHaumer** [comment]
I'd prefer to keep the comments as internal documentation - thanks.

**Comment by christiankral** [comment]
> I'd prefer to keep the comments as internal documentation - thanks.

@AHaumer Yes, shall we add

```modelica
// Alternative equivalent implementation:
```

as proposed [above](https://github.com/modelica/ModelicaStandardLibrary/pull/3623#issuecomment-841881148) to make the documentation character more clear to the users?

**Comment by AHaumer** [comment]
> @AHaumer OK, but shall we add
> 
> ```modelica
> // Alternative equivalent implementation:
> ```
> 
> as proposed [above](https://github.com/modelica/ModelicaStandardLibrary/pull/3623#issuecomment-841881148) to make the documentation character more clear to the users?

Fine with me.

**Comment by arunkumar-narasimhan** [comment]
@AHaumer @christiankral, we have made the `Alternative equivalent implementation` comment in relevant places. Could you please review?

**Review by AHaumer — APPROVED** [review]
ok for me

**Review by christiankral — APPROVED** [review]
OK with me.

**Pull request merged**
