### PR TITLE
Rename Machines Controllers

### PR DESCRIPTION
**Pull request by AHaumer**
Naming of controllers is misleading, has to be clarified:
Electrical.Machines.Utilities.CurrentController -> DQToThreePhase
Electrical.Machines.Utilities.CurrentController.{id_rms, iq_rms} -> DQToThreePhase.{d, q}
Electrical.Machines.Utilities.VoltageController -> CurrentController
Electrical.Machines.Utilities.VoltageController,{id_rms, iq_rms} -> CurrentController,{id, iq}
Renaming and conversion script done, test cases follow.

### CODE REVIEW

**Comment by christiankral** [comment]
We could rename the "new" `CurrentController` to `DQCurrentController`.

**Comment by AHaumer** [comment]
@beutlich good point ... followd @christiankral 's advice.

**Comment by beutlich** [comment]
After merging #3059 this is now conflicting.

**Comment by AHaumer** [comment]
@beutlich conflicts should be resolved

**Comment by AHaumer** [comment]
@beutlich sorry don't know how this could happen, resolved.

**Comment by beutlich** [comment]
Might be off-topic: Why are Modelica.Electrical.Machines.Utilities.SynchronousMachineData and Modelica.Electrical.Machines.Utilities.TransformerData not in Modelica.Electrical.Machines.Utilities.ParameterRecords?

**Pull request merged**
