### PR TITLE
Remove discrete input

### PR DESCRIPTION
**Pull request by HansOlsson**
Since it doesn't make sense, see https://github.com/modelica/ModelicaSpecification/issues/3220

### CODE REVIEW

**Comment by henrikt-ma** [comment]
Why isn't this a useful way of declaring that the function requires these arguments to be discrete-time?  This would be a handy way of letting the tool check that a function that doesn't have `GenerateEvents = true` (perhaps because it isn't suitable for inlining) isn't being called in undefined ways.

**Comment by HansOlsson** [comment]
> Why isn't this a useful way of declaring that the function requires these arguments to be discrete-time?

That semantics isn't specified.

**Comment by henrikt-ma** [comment]
> That semantics isn't specified.

OK, but let's not close https://github.com/modelica/ModelicaSpecification/issues/3220 so quickly in that case.

**Comment by HansOlsson** [comment]
> > That semantics isn't specified.
> 
> OK, but let's not close [modelica/ModelicaSpecification#3220](https://github.com/modelica/ModelicaSpecification/issues/3220) so quickly in that case.

Well, it asked if using discrete had any semantics (which either it doesn't or possibly it has something that doesn't make sense for a function), and if not proposed to remove them.

Introducing something special in functions to require the input argument to have a specific variability would be quite complicated.

**Comment by henrikt-ma** [comment]
> Introducing something special in functions to require the input argument to have a specific variability would be quite complicated.

I don't know exactly how it would be done, but @qlambert-pro, would you agree that checking this could be complicated in any way?  Isn't this what we do all the time for built-in functions and operators?

(I see that one would need to state the rule that variability inside functions can't be trusted for purposes of calling functions with variability-constrained inputs, but I blame this problem on a misuse of the variability concepts inside functions, and what it means here is simply that calling functions with variability-constrained inputs can only be allowed outside functions.)

**Comment by qlambert-pro** [comment]
I think checking the variability of arguments given to function calls against the declared variability should be easy enough. My question referenced discrete but it wasn't limited to it. I think we should also address how we handle `parameter` and `constant`.

**Comment by HansOlsson** [comment]
> I think checking the variability of arguments given to function calls against the declared variability should be easy enough. 

But declared variability isn't that helpful. We cannot declare that a variable has discrete variability as `discrete Real` requires that the variable is given by a when-clause (which is clearly non-sensical for a variable in a function).

Its also contrary to the idea of having the same Add-block for continuous and clocked variables, since the goal is to  automatically derive that variables are clocked (or continuous-time, or discrete) which clashes with declaring it.

For clocked variables we have defined how to derive that they are clocked. For discrete-time variables that isn't even defined.

**Comment by henrikt-ma** [comment]
> > I think checking the variability of arguments given to function calls against the declared variability should be easy enough.
> 
> But declared variability isn't that helpful. We cannot declare that a variable has discrete variability as `discrete Real` requires that the variable is given by a when-clause (which is clearly non-sensical for a variable in a function).

This is about giving semantics for `discrete` being specified for a function `input` component, which is quite different from a component in a block.  The variability constraint is then defined in terms of the expression variability (which wouldn't require any change compared to today), not directly in terms of `discrete` applied to non-function component declarations.

**Comment by HansOlsson** [comment]
> > > I think checking the variability of arguments given to function calls against the declared variability should be easy enough.
> > 
> > 
> > But declared variability isn't that helpful. We cannot declare that a variable has discrete variability as `discrete Real` requires that the variable is given by a when-clause (which is clearly non-sensical for a variable in a function).
> 
> This is about giving semantics for `discrete` being specified for a function `input` component, which is quite different from a component in a block.

Having two different 'discrete' with different meanings would be confusing.

> The variability constraint is then defined in terms of the expression variability (which wouldn't require any change compared to today), not directly in terms of `discrete` applied to non-function component declarations.

That simply wouldn't work, since declared variability isn't that helpful. 

In practice that means that many expressions that formally have continuous-time variability are in fact 'discrete' (in the sense that they don't vary between events). At the moment that doesn't matter, since treating discrete expressions as continuous-time expressions is safe (the worst case is that we get spurious crossing functions); but if we want to impose a restriction that will not work.

**Review by hubertus65 — APPROVED** [review]

**Comment by HansOlsson** [comment]
Would be good with additional reviews

**Comment by HansOlsson** [comment]
> Can we get more reviews of this - so that it can be merged before release-branch on Friday January 12th?

@casella ?

**Review by MartinOtter — APPROVED** [review]

**Pull request merged**
