### PR TITLE
choicesAllMatching=true is the correct annotation!

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

**Review by casella — APPROVED** [review]
Indeed, see [Section 7.3.4](https://specification.modelica.org/maint/3.5/inheritance-modification-and-redeclaration.html#annotation-choices-for-suggested-redeclarations-and-modifications) of the language spec.

BTW, these invalid annotations were also present in MSL 3.2.3.

@adrpo, @beutlich, I guess we should push this to maint/3.2.3 and to maint/4.0.x, what do you think?

**Review by sjoelund — COMMENTED** [review]
Seems OK. I guess some other tool vendor should approve it though. I would backport it to the two maintained branches as well.

**Review by maltelenz — APPROVED** [review]
Looks like a good change (me being the representative of another tool vendor).

**Comment by adrpo** [comment]
#3780 for maint/3.2.3

**Comment by adrpo** [comment]
#3781 for maint/4.0.x

**Pull request merged**
