### PR TITLE
Merge PartialFMUadaptors to existing Adaptors

### PR DESCRIPTION
**Pull request by beutlich**
The adaptors are not solely designed to be used with FMUs, but FMU is one use case for it.

### CODE REVIEW

**Comment by AHaumer** [comment]
Could you describe for which other than generation of FMUs purposes they could be used?
I dislike the new name, its too generic.

**Comment by beutlich** [comment]
It feels strange for me to have the package called PartialFMUadaptors, when its components say X2YAdaptor, which is especially useful for FMUs.

**Comment by StephanZiegler** [comment]
Actually it is intended to be used for connecting something acausal with something causal, e.g model some sort of source block for a specific domain.

FMU will probably be the most common usage for these, but for sure not the only one. 

Therefore i agree with @beutlich in this case "FMU" should not be in the name. But just "PartialAdaptors" is a bit too generic. How about "PartialPhysicalAdaptors", "PartialCausalAdaptors" or "PartialDomainAdaptors".
 
If no better solution is found i'm fine with "PartialAdaptors", since it should be self explanatory from the context.

**Comment by tobolar** [comment]
Moreover, the documantation states
> ... especially as FMU ...

which I understand not being the only possibility.

**Comment by tobolar** [comment]
I would use the opportunity and vote for shortening the component names. Once the package reflects the "adaptor" in its name, it shell be omited in the component names, thus:
- FlowToPotentialAdaptor -> FlowToPotential
- PotentialToFlowAdaptor -> PotentialToFlow

**Comment by tobolar** [comment]
What about "ExchangeAdaptors"? It goes towards FMUadaptors but is more generic.
Not sure about necessity to reflect "partial" in the package name. There is some discussion whether use it in component names already, see #496 and #609.

**Comment by beutlich** [comment]
My first idea actually was to reuse the existing Modelica.Blocks.Interfaces.Adaptors package, which we declared obsolete because of the obsoleted blocks.

**Comment by HansOlsson** [comment]
So what about un-obsolete the Adaptors package and put them there?

**Comment by beutlich** [comment]
> So what about un-obsolete the Adaptors package and put them there?

Fine for me.

**Comment by tobolar** [comment]
The `Adaptors` package should be reordered in Blocks.Interfaces - either to be at the top or the bottom.

**Pull request merged**
