### PR TITLE
Fix SI units by introducing reference phase impedance ZsRef

### PR DESCRIPTION
**Pull request by HansOlsson**
Fix the unit for the inductances. 
Eliminates non-local unit errors based on https://github.com/modelica/ModelicaSpecification/pull/3266 (combined with other unit-changes.)

### CODE REVIEW

**Review by dietmarw — APPROVED** [review]

**Comment by HansOlsson** [comment]
Note that there are similar-looking examples of unit-errors in other classes that isn't corrected in this PR, like Modelica.Magnetic.FundamentalWave.BasicMachines.SynchronousMachines 

It would likely be possible to correct them as well in a similar way (but then there are messier ones as well - as the SquirrelCage).

**Comment by christiankral** [comment]
This PR shall actually affect the machine models of three different packages as they all have the same shortcomings:

- `Modelica.Electrical.Machines.BasicMachines`
- `Modelica.Magnetic.FundamentalWave.BasicMachines`
- `Modelica.Magnetic.QuasiStatic.FundamentalWave.BasicMachines`

Addirtionally I would like to discuss some aspects of this PR with @AHaumer first: I see three different "simple" fixes of this issue:

### Option 1

Follow the proposal of this PR but change `final constant SI.Resistance unitR=1`  to `final constant SI.Impedance unitZ=1`, as the inductances are calculated from impedances, not resistances. 

### Option 2

Add parameters of the reference phase voltage and current to the machine models, according to the documentation and the original intention of the used paramerterization:

image

```modelica
   parameter Modelica.Units.SI.Voltage VsRef = 100 " RMS reference phase voltage";
   parameter Modelica.Units.SI.Current IsRef = 100 " RMS reference phase current";
   final parameter Modelica.Units.SI.Impedance ZsRef = VsRef / IsRef "Reference phase impedance";
```
Use parameter `ZsRef` instead of `unitZ` then.

However, option 2. has the drawback, that additional parameters are used in the machine models. Even though this parameters do not change the model behavior it will most likely happen that a user model then shows the new parameters `VsRef = 100` and `IsRef = 100` which might not match the actual user parameters. This is a bad side effect which could confuse the users.

The parameters `VsRef` and `IsRef` could be made protected, but then it is questionable if there still exists and advantage over option 1.

### Option 3

Replace the division by `2*pi*fsNominal` by the term `100*pi` and thus fully ignore the units in the default paramters.

**Comment by dietmarw** [comment]
I agree that Option 2 is suboptimal if the new reference parameter has no function other than creating a new ZsRef to fix the unit. Although having them might finally explain to the user better what the Lx calculations in the data records of the examples are based on. So in I think:
 - Option 1: Pragmatic solution but seems like a "hack" to please the tool.
 - Option 2: Gives a bit more background info to the meaning and origin of the parameter calculations, more user friendly but at the same time also dangerous to be confusing (since Vref and Iref don't "do" anything).
 - Option 3: Makes it very hard to understand the equations and their physical meaning.

**Comment by HansOlsson** [comment]
An option 4 would be to use:
`   final parameter Modelica.Units.SI.Impedance ZsRef = 1 "Reference phase impedance based on nominal voltage 100 V and nominal current 100 A; per phase";`

(Possibly with better description.)

It avoids the extra variables of option 2.
Compared to option 1 it isn't just a magic unit conversion, but properly using a reference impedance (which happens to have the value 1).

**Comment by christiankral** [comment]
I agree with @HansOlsson. I think option 4 is the way to go.

**Comment by christiankral** [comment]
In order to provide a consistent solution

- the protected parameter `ZsRef` is moved into the partial model `Modelica.Electrical.Machines.Interfaces.PartialBasicInductionMachine`
- the resistances `Rs` and `Rr` are also multiplied by `ZsRef`, as this was the original intention of this default parameter set

**Comment by TManikantan** [comment]
This pull request requires second reviewer to approve the fix to merge it successfully.
@AHaumer   would you please review the fix and approve it?

**Comment by TManikantan** [comment]
@AHaumer Would you please review the fix?

**Review by AHaumer — APPROVED** [review]
fine with me.

**Comment by TManikantan** [comment]
@christiankral would you look into the fix and give a yes so we can go ahead and merge the PR?

**Pull request merged**
