### PR TITLE
Update CoupledClutches.mos

### PR DESCRIPTION
**Pull request by DagBruck**
Making this change to master branch, duplicate of commit b0f2a98.

### CODE REVIEW

**Comment by DagBruck** [comment]
Duplicated from https://github.com/modelica/ModelicaStandardLibrary/pull/4348 on the wrong branch.

**Review by HansOlsson — APPROVED** [review]
Ok.
We could later replace this (and others) with figure-annotations; but best to have a sensible starting point.

**Comment by Harisankar-Allimangalath** [comment]
@HansOlsson @DagBruck we want to backport this to maint\4.1.x  right .  #4348  was closed . so shall  I  backport this with a new PR

**Comment by DagBruck** [comment]
@Harisankar-Allimangalath yes, there is every reason to backport it. Thanks.

**Comment by Harisankar-Allimangalath** [comment]
FYI , created  PR to back port this @DagBruck @dietmarw @HansOlsson  #4371  . 

Thankyou

**Pull request merged**
