### PR TITLE
Fix links of the electrical and the magnetic domain 

### PR DESCRIPTION
**Pull request by christiankral**
Refs #3341

### CODE REVIEW

**Comment by beutlich** [comment]
@sjoelund Can you think of an extension of the OMC CI to check if modelica URIs can be resolved. That really would be nice.

**Comment by christiankral** [comment]
Everything shall be fixed by now

**Comment by beutlich** [comment]
> 
> 
> @sjoelund Can you think of an extension of the OMC CI to check if modelica URIs can be resolved. That really would be nice.

@sjoelund Can you think of any proposal? We even can award your development since we have dedicated budget for CI improvements.

**Comment by HansOlsson** [comment]
> 
> 
> OM did no longer complain.

Neither does Dymola.

**Pull request merged**
