### PR TITLE
MSL 4.1.0 Regressions: set FundamentalWave..SymmetricPolyphaseWinding.ZeroInductor.i0

### PR DESCRIPTION
**Pull request by beutlich**
Backport of #4486 from master to maint/4.1.x.

### CODE REVIEW

**Review by maltelenz — APPROVED** [review]
Confirmed this contains the changes it claims to backport.

**Review by AHaumer — APPROVED** [review]
I don't understand the changes moving if to the next line and replacing 1e-4 by 0.0001 but it's ok.

**Comment by MatthiasBSchaefer** [comment]
@AHaumer This topic not only concerns the example
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.InductionMachines.IMC_YD
but also the example  
Modelica.Magnetic.**QuasiStatic**.FundamentalWave.Examples.BasicMachines.InductionMachines.IMC_YD
Can you please care about this ?

**Comment by AHaumer** [comment]
Thanks @MatthiasBSchaefer you're right: The QuasiStatic exmaple also contains a transient machine for comparison and therefore should get the same treatment.

**Comment by AHaumer** [comment]
see #4532

**Pull request merged**
