### PR TITLE
Use ellipses instead of arcs by lines

### PR DESCRIPTION
**Pull request by tobolar**
Free continuation of #3730 for `Rotational.Sources`.

Test model:
```
model UseEllipsesRotational
  Modelica.Mechanics.Rotational.Sources.Torque torque annotation (Placement(transformation(extent={{-80,60},{-60,80}})));
  Modelica.Mechanics.Rotational.Sources.Torque2 torque1 annotation (Placement(transformation(extent={{-40,60},{-20,80}})));
  Modelica.Mechanics.Rotational.Sources.InverseSpeedDependentTorque inverseSpeedDependentTorque annotation (Placement(transformation(extent={{-80,0},{-60,20}})));
  Modelica.Mechanics.Rotational.Sources.LinearSpeedDependentTorque linearSpeedDependentTorque annotation (Placement(transformation(extent={{-80,-30},{-60,-10}})));
  Modelica.Mechanics.Rotational.Sources.QuadraticSpeedDependentTorque quadraticSpeedDependentTorque annotation (Placement(transformation(extent={{-80,-60},{-60,-40}})));
  Modelica.Mechanics.Rotational.Sources.ConstantTorque constantTorque annotation (Placement(transformation(extent={{-80,-90},{-60,-70}})));
  Modelica.Mechanics.Rotational.Sources.SignTorque signTorque annotation (Placement(transformation(extent={{-40,0},{-20,20}})));
  Modelica.Mechanics.Rotational.Sources.ConstantSpeed constantSpeed annotation (Placement(transformation(extent={{-40,-30},{-20,-10}})));
  Modelica.Mechanics.Rotational.Sources.TorqueStep torqueStep annotation (Placement(transformation(extent={{-40,-60},{-20,-40}})));
  Modelica.Mechanics.Rotational.Sources.EddyCurrentTorque eddyCurrentTorque annotation (Placement(transformation(extent={{-40,-90},{-20,-70}})));
  Modelica.Mechanics.Rotational.Interfaces.PartialTorque partialTorque annotation (Placement(transformation(extent={{-40,30},{-20,50}})));
end UseEllipsesRotational;
```

This is how the changes render in Dymola 2021x. (Previously: arcs by lines; now: by ellipses)

iconsSources

__Note:__ There is still a white rectangle in the `partialTorque` for it is considered being a background of "diagrams" of torques by functions (such as `constantTorque`, etc.). I have nevertheless reduced its size.

### CODE REVIEW

**Review by maltelenz — APPROVED** [review]
Nice!

In System Modeler, before:
image

After:
image

**Review by beutlich — COMMENTED** [review]
This is the diagram view SimulationX. The black curve in Modelica.Mechanics.Rotational.Sources.SignTorque should probably also be blue (to match all other icons).

grafik

**Comment by tobolar** [comment]
> The black curve in Modelica.Mechanics.Rotational.Sources.SignTorque should probably also be blue
@beutlich Fixed, thanks.

**Review by beutlich — APPROVED** [review]
>> The black curve in Modelica.Mechanics.Rotational.Sources.SignTorque should probably also be blue

> @beutlich Fixed, thanks.

Thanks.

**Pull request merged**
