### PR TITLE
Remove incorrect unit-casting

### PR DESCRIPTION
**Pull request by HansOlsson**
The basic issue is that `H0` shouldn't be seen as a magnetic field strength, but as a dimensionless value (which makes sense given that it is the result of a logarithm). That implies that the argument to tanh is already dimensionless - when M has the unit of inverse magnetic field strength.

The commit also makes the two models more similar.
As far as I can tell this issue was already present in the original commit of these models.

### CODE REVIEW

**Review by hubertus65 — APPROVED** [review]

**Comment by AHaumer** [comment]
Sorry this is a task for @ThomasBoedrich and Johannes Ziske.

**Review by christiankral — APPROVED** [review]
Looks OK

**Comment by HansOlsson** [comment]
> Two comments:
> 
> 1. The constant `unitH` is then not needed any more and can be removed from both models

True, but that would sort of break compatibility (using an inherited unitH is bad; but formally allowed) - so I delay that.

> 2. The parameter `parameter Real M = 10/Hc` could be changed to `parameter Real(final unit="m/A") M = 10/Hc`

Ok, but doesn't seem that necessary.

**Comment by HansOlsson** [comment]
Adding unit just in case.

**Comment by HansOlsson** [comment]
> Looks OK

Can you re-examine - it seems that a new approval is needed after change.

**Review by christiankral — APPROVED** [review]
Look all good.

**Pull request merged**
