### PR TITLE
Revert "Fix position prescribed friction"

### PR DESCRIPTION
**Pull request by MartinOtter**
Reverts modelica/ModelicaStandardLibrary#4129

When simulating a model with the changed friction model the following error appears in Dymola 2023x:

Compiling and linking the model (Visual C++). 

dsmodel.c
dsmodel.c(176): error C2065: "ModelicaStandardTables_CombiTable1D_init3": nichtdeklarierter Bezeichner
dsmodel.c(176): error C2064: Ausdruck ergibt keine Funktion, die 337 Argumente bernimmt

Error generating Dymosim.

### CODE REVIEW

**Comment by tobolar** [comment]
Duplicate to #3911

**Comment by tobolar** [comment]
@beutlich Is it documented how to proceed in such cases or where to find up-to-date binaries? https://github.com/modelica/ModelicaStandardLibrary/issues/4178#issuecomment-1673710607 is well and good but not that easy to find it.

**Comment by beutlich** [comment]
> Is it documented how to proceed in such cases or where to find up-to-date binaries?

They are usually updated by a library officer before tagging a release. See #4250.

**Comment by beutlich** [comment]
I wonder why this PR was merged bypassing the review process. This is not ideal. 😕

**Comment by tobolar** [comment]
> > Is it documented how to proceed in such cases or where to find up-to-date binaries?
> 
> They are usually updated by a library officer before tagging a release. See #4250.

Is there any procedure how to handle this *before* the update of binaries?
What about to e.g. handle PRs regarding binaries' changes differently to common PRs? (This is just a spontaneous idea.)

**Comment by MartinOtter** [comment]
> I wonder why this PR was merged bypassing the review process. This is not ideal. 😕

Because "external_c_checks" and "deprecation_checks" failed and there was no information why this failed.

As I understand from the discussion above, these checks will further fail until
https://github.com/beutlich/ModelicaStandardLibrary/tree/update-binaries
is moved to main (so any pull request that involves test/example models with tables will fail).
Please, can you move these binaries to main, so that  "external_c_checks" does no longer fail.

**Comment by MartinOtter** [comment]
> I do not see that the checks failed: https://github.com/modelica/ModelicaStandardLibrary/actions/runs/7499083151/job/20415248489 and https://github.com/modelica/ModelicaStandardLibrary/actions/runs/7499083151/job/20415248013
> 
> The CI always builds all libraries as needed.

See: https://github.com/modelica/ModelicaStandardLibrary/pull/4129

grafik

and in "Details" I did not find more details and especially no link to the github actions.

I did not manage to get tables from master to run locally on my machine
(I copied c/h files and lib files from https://github.com/beutlich/ModelicaStandardLibrary/tree/update-binaries but did not help.
Could you just make master self-contained, so that the Resources directory is correct.
I don't understand how a feature freeze can be done, if such an import feature is not included in the master branch)

**Comment by beutlich** [comment]
It says in https://github.com/modelica/ModelicaStandardLibrary/actions/runs/6865804143

> The hosted runner: GitHub Actions 2 lost communication with the server.

and

> The hosted runner: GitHub Actions 3 lost communication with the server.

which should not be a reason to to revert a PR without proper review in a rush. CI should have just be triggered again.

**Pull request merged**
